### ISSUE TITLE
`dev-haskell/tar-conduit-0.3.2` might have missing deps

### ISSUE THREAD

**Issue by metiulekm** [gentoo-haskell/gentoo-haskell#1007]
Most dependencies of `tar-conduit` are marked as test-only; the only build dependencies are `ghc` and `cabal`:
```
RDEPEND=">=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.24
	test? ( dev-haskell/conduit
		>=dev-haskell/conduit-combinators-1.0.8.1
		dev-haskell/conduit-extra
		dev-haskell/safe-exceptions
		dev-haskell/hspec
		dev-haskell/quickcheck
		dev-haskell/weigh )
"
```
But then I get during (re)build:
```
There are problems in package tar-conduit-0.3.2:
  Warning: haddock-interfaces: /usr/share/doc/tar-conduit-0.3.2/html/tar-conduit.haddock doesn't exist or isn't a file
  Warning: haddock-html: /usr/share/doc/tar-conduit-0.3.2/html doesn't exist or isn't a directory
  dependency "conduit-combinators-1.3.0-E73kxSR3UE2RSmB7MjN4R" doesn't exist
  dependency "safe-exceptions-0.1.7.0-KDPPzH6jemjKt0yyowjiQ" doesn't exist
```
Indeed, `tar-conduit` needs the following:
```
  build-depends:       base >= 4.9.0.0 && < 5
                     , bytestring
                     , conduit
                     , conduit-combinators >= 1.0.8.1
                     , directory
                     , filepath
                     , safe-exceptions
                     , text
```

**Comment by pbarill** [comment]
Looking at who last dealt with that package: That would be me!

What happened: The ebuild was generated with hackport, and as I operate with test enabled, it did not pose problem with this very questionable arrangement.

I'll look into this and push a fix asap. Sorry about that, and thanks for reporting!

**Comment by pbarill** [comment]
Ok, this one in the pull request should do it. It works on my no-test system.

I had to rub my eyes a bit. Somehow, originally hackport added `safe-exceptions` as a test dependency. And just now it ignored it altogether. Odd.

**Comment by metiulekm** [comment]
Thanks a lot for your help! :)

**Comment by metiulekm** [comment]
One more small thing: I think that, if I understand correctly, at least `safe-exceptions` should also be a runtime dependency. Running `emerge --with-bdeps=n --depclean` on my system removes both `conduit-combinators` and `safe-exceptions` but I then get a preserved lib from `safe-exceptions`.

**Comment by metiulekm** [comment]
I don't get preserved libs now. Thanks a lot! :smile:
