### ISSUE TITLE
Port to network-3

### ISSUE THREAD

**Issue by solpeth** [gentoo-haskell/gentoo-haskell#1052]
Track packages which depend on `dev-haskell/network`.
---

**Packages to bump**
- [x] _x11-misc_/taffybar-**3.2.1** -> **3.2.2**
- [x] _dev-haskell_/status-notifier-item-**0.3.0.4** -> **0.3.0.5**
- [x] _dev-vcs_/git-annex-**7.20191024** -> **8.20200330**
- [x] _dev-haskell_/network-**2.8.0.1** -> **3.0.1.1**
- [x] _dev-haskell_/missingh-**1.4.2.1** -> **1.4.3**
- [x] _dev-lang_/purescript-**0.12** -> **0.13.6**
- [x] _dev-haskell_/happstack-server-**7.5.4** -> **7.6.0**

**Packages to unmask**
- [x] ~~_x11-misc_/taffybar-**3.2.2** (requires `time-1.9` from `ghc-8.8.1`, or replacing the use of `diffLocalTime` and `addLocalTime`. See https://github.com/taffybar/taffybar/commit/2731998d02289f7fad56dbffcd3015ee010dde73)~~ (redundant. **3.2.1** works with slotted `network-2`)
- [x] ~~_dev-haskell_/mysql-haskell-**0.8.4.2** (reverse dependency `mysql-haskell-openssl` needs patching for `network-3`)~~ (made redundant by patching **0.8.3** for `network-3`)
- [x] >=_dev-haskell_/dbus-**1.2.8**
- [x] _dev-haskell_/aws-**0.22**[_+network-3_]
- [x] _dev-haskell_/network-bsd-**2.8.1.0**

**Packages to update USE flag defaults**
- [x] _dev-haskell_/bson[_-old-network_]
- [x] _dev-haskell_/mongodb[_-old-network_]

**Packages to patch**
- [x] _dev-haskell_/network-protocol-xmpp-**0.4.9** (works with slotted `network-2`)
- [x] _dev-haskell_/tcp-streams-openssl-**1.0.1.0** (dependency of `mysql-haskell-openssl`)
- [x] _dev-haskell_/cabal-install-**2.4.0.0**
- [x] _www-apps_/gitit-**0.12.3.2** (depends on `happstack-server`)
- [x] _dev-haskell_/icalendar-**0.4.0.5** (works with slotted `network-2`)
- [x] _dev-haskell_/ircbot-**0.6.5.3** (works with slotted `network-2`)
- [x] _dev-lang_/idris-**1.3.2** (works with slotted `network-2`)
- [x] _media-sound_/live-sequencer-**0.0.6.2** (works with slotted `network-2`)
- [x] _dev-haskell_/digestive-functors-happstack-**0.6.1.2**
- [x] _dev-haskell_/hstatsd-**0.1**

**Comment by solpeth** [comment]
Refer to https://github.com/gentoo-haskell/gentoo-haskell/pull/1053

**Comment by solpeth** [comment]
The above list of packages is reporting 100% compatibility, either with `network-3` or `network-2` in a slotted configuration.

I'll leave this open for now should any other incompatibilities pop up.

**Comment by l29ah** [comment]
`dns`:
```
[ 7 of 15] Compiling Network.DNS.IO   ( Network/DNS/IO.hs, dist/build/Network/DNS/IO.o )

Network/DNS/IO.hs:62:49: error:
    • Couldn't match expected type ‘network-2.8.0.1:Network.Socket.Types.Socket’
                  with actual type ‘Socket’
      NB: ‘Socket’
            is defined in ‘Network.Socket.Types’ in package ‘network-3.0.1.1’
          ‘network-2.8.0.1:Network.Socket.Types.Socket’
            is defined in ‘Network.Socket.Types’ in package ‘network-2.8.0.1’
    • In the first argument of ‘sourceSocket’, namely ‘sock’
      In the first argument of ‘(.|)’, namely ‘sourceSocket sock’
      In the first argument of ‘runConduit’, namely
        ‘(sourceSocket sock .| sink)’
   |
62 | receive sock = fst <$> runConduit (sourceSocket sock .| sink)
   |                                                 ^^^^

Network/DNS/IO.hs:69:37: error:
    • Couldn't match expected type ‘network-2.8.0.1:Network.Socket.Types.Socket’
                  with actual type ‘Socket’
      NB: ‘Socket’
            is defined in ‘Network.Socket.Types’ in package ‘network-3.0.1.1’
          ‘network-2.8.0.1:Network.Socket.Types.Socket’
            is defined in ‘Network.Socket.Types’ in package ‘network-2.8.0.1’
    • In the first argument of ‘sourceSocket’, namely ‘sock’
      In the first argument of ‘($$+)’, namely ‘sourceSocket sock’
      In a stmt of a 'do' block:
        (src, lenbytes) <- sourceSocket sock $$+ CB.take 2
   |
69 |     (src, lenbytes) <- sourceSocket sock $$+ CB.take 2
   |                                     ^^^^
```

**Comment by solpeth** [comment]
@l29ah I can deduce that you're having an issue building `dns`, but I can't tell why.

The slotting I've put in place with `network` is more or less a hack, unlike how the Python team have gone about it. But we should be able to manually intervene into packages' dependency version ranges to tighten things up when these problems arise.

But again, I think I need a bit more info with what's going on here.

**Comment by l29ah** [comment]
What info do you need?

**Comment by solpeth** [comment]
Could you attach a full build log?

**Comment by l29ah** [comment]
I've retested it, and it works fine now. Probably some `dns` dependency needed to be rebuilt first against network-3, and portage messed up the ordering? Dunno.
