### ISSUE TITLE
=dev-haskell/store-0.4.3.2 fails to merge

### ISSUE THREAD

**Issue by houseofsuns** [gentoo-haskell/gentoo-haskell#1061]
I'm on ~amd64 and just added the haskell overlay. Overall it worked very well but store is the odd one out. Below is the error message. Let me know if I can provide anything else.

<pre>
[ 5 of 11] Compiling Data.Store.Internal ( src/Data/Store/Internal.hs, dist/build/Data/Store/Internal.o )

src/Data/Store/Internal.hs:710:3: error:
    • Expected kind ‘* -> *’, but ‘f’ has kind ‘*’
    • In the first argument of ‘Alt’, namely ‘f’
      In the first argument of ‘Data.Vector.Unboxed.Base.Vector’, namely
        ‘(Alt f a)’
      In the first argument of ‘Store’, namely
        ‘(Data.Vector.Unboxed.Base.Vector (Alt f a))’
    |
710 | $(deriveManyStoreUnboxVector)
    |   ^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Data/Store/Internal.hs:710:3: error:
    • Expected kind ‘k0 -> *’, but ‘f’ has kind ‘*’
    • In the first argument of ‘Data.Functor.Compose.Compose’, namely
        ‘f’
      In the first argument of ‘Data.Vector.Unboxed.Base.Vector’, namely
        ‘(Data.Functor.Compose.Compose f g a)’
      In the first argument of ‘Store’, namely
        ‘(Data.Vector.Unboxed.Base.Vector (Data.Functor.Compose.Compose f g a))’
    |
710 | $(deriveManyStoreUnboxVector)
    |   ^^^^^^^^^^^^^^^^^^^^^^^^^^
[10 of 11] Compiling System.IO.ByteBuffer ( src/System/IO/ByteBuffer.hs, dist/build/System/IO/ByteBuffer.o )
</pre>

**Comment by solpeth** [comment]
Thanks for the report! Looks like it needs an update. I'll get that sorted in a bit.

**Comment by houseofsuns** [comment]
Thanks for the quick fix, works like a charm.
