### ISSUE TITLE
dev-haskell/hlint-2.1.17: wrong deps (hackport bug?)

### ISSUE THREAD

**Issue by l29ah** [gentoo-haskell/gentoo-haskell#1062]
```
setup: Encountered missing dependencies:
haskell-src-exts ==1.21.*
```

In the RDEPEND i see this: `>=dev-haskell/haskell-src-exts-1.21:=[profile?] <dev-haskell/haskell-src-exts-1.22:=[profile?]`
Both of them are satisfied, by 1.20.3 and 1.23.0.

**Comment by solpeth** [comment]
I'm confused. When I run `ebuild hlint-2.1.17.ebuild clean configure` it configures against `haskell-src-exts-1.21.1`. What is happening in your case?

**Comment by l29ah** [comment]
Probably because you have 1.21.1 installed.

**Comment by solpeth** [comment]
Now that I think about it I vaguely remember something like this happening when I started slotting `haskell-src-exts`. But I'm unsure as to why it would satisfy itself against a version outside of the version range. Does anything change if you explicitly define the slot in the `RDEPEND`? E.g. `>=dev-haskell/haskell-src-exts-1.21:1.21=[profile?] <dev-haskell/haskell-src-exts-1.22:1.22=[profile?]`?

**Comment by l29ah** [comment]
Because it is not a version range. Also, peeps on #gentoo-dev-help tell there's no such thing as version ranges in Gentoo, so hackport can't do the right thing automagically, at least w/o looking at existing ebuilds and grabbing the desired slot specs from them.

**Comment by solpeth** [comment]
Okay. So, if we manually adjust the ebuild to say something like `dev-haskell/haskell-src-exts:1.21=[profile?]` does that resolve correctly?

**Comment by trofi** [comment]
Yes, dependencies like `>=foo-1 <foo-2` can be satisfied by multislot packages as two packages, for example: `foo-3:3` (matches `>=foo-1`) and `foo-0:0` (matches `<foo-2`).

Usually that means that we (or hackport) need to pick a particular slot and consistently use it across all depends.

**Comment by solpeth** [comment]
6d66e21 is not a complete solution to this problem, only for this package. Unfortunately the slotting may have caused more headaches than it solves, implemented as it currently is, so I'll try to deal with those issues as they pop up.
