### ISSUE TITLE
dev-haskell/git-0.3.0 fails to compile

### ISSUE THREAD

**Issue by houseofsuns** [gentoo-haskell/gentoo-haskell#1067]
I'm on ~amd64 + haskell-overlay and since the update to ghc-8.8.3 I see the following failure (I don't know whether it's related to ghc). Please advise on how to proceed.

<pre>
[24 of 25] Compiling Data.Git.Monad   ( Data/Git/Monad.hs, dist/build/Data/Git/Monad.o )

Data/Git/Monad.hs:243:5: error:
    ‘fail’ is not a (visible) method of class ‘Monad’
    |
243 |     fail   = failGitM
    |     ^^^^

Data/Git/Monad.hs:316:5: error:
    ‘fail’ is not a (visible) method of class ‘Monad’
    |
316 |     fail   = failCommitAccessM
    |     ^^^^

Data/Git/Monad.hs:477:5: error:
    ‘fail’ is not a (visible) method of class ‘Monad’
    |
477 |     fail   = failCommitM
    |     ^^^^
</pre>

**Comment by solpeth** [comment]
`git` needs patching for the MonadFail proposal which was fully implemented as of `ghc-8.8.1`. It doesn't seem patched upstream, so I might have a play with it.

**Comment by solpeth** [comment]
@houseofsuns please let me know if you experience any failures or changes in runtime behaviour.

**Comment by houseofsuns** [comment]
Thanks a lot for the quick fix. :)
