### ISSUE TITLE
dev-haskell/ghc-pkg-lib-0.3.1fails to compile

### ISSUE THREAD

**Issue by houseofsuns** [gentoo-haskell/gentoo-haskell#1068]
I'm on ~amd64 + haskell-overlay and since the update to ghc-8.8.3 I see the following failure (I don't know whether it's related to ghc). Please advise on how to proceed.

<pre>
[1 of 1] Compiling Language.Haskell.Packages ( src/Language/Haskell/Packages.hs, dist/build/Language/Haskell/Packages.o )

src/Language/Haskell/Packages.hs:207:17: error:
    Not in scope: data constructor ‘ParseOk’
    |
207 |                 ParseOk _ info -> return [info]
    |                 ^^^^^^^

src/Language/Haskell/Packages.hs:208:17: error:
    Not in scope: data constructor ‘ParseFailed’
    |
208 |                 ParseFailed err  -> do
    |                 ^^^^^^^^^^^
</pre>

**Comment by solpeth** [comment]
Thanks for the report. According to the author this package has not been maintained since 2015. I'm happy to keep it alive if someone wants to write a patch, otherwise I think I'll mask and schedule its deletion.

**Comment by solpeth** [comment]
This is now closed by the commit masking this package, but like I said feel free to submit a patch and I'll gladly unmask it! Thanks again for your report.
