### ISSUE TITLE
cabal-bin + hadock-bin + LLVM patching

### ISSUE THREAD

**Issue by necrose99** [gentoo-haskell/gentoo-haskell#1070]
llvm 7 is the dope spot for ghc/cabal/ etc..  however gripes to no end. 

https://github.com/sakaki-/gentoo-on-rpi-64bit 

cabal dies on build as dose ghc even after emerging the one few , USE="binary" 
cabal-binaries for arm/arm64 might be of use in bootstrapping. 

hadock is supposedly their porting layer.  however might enable more builds dunno ? 

for 9-13 LLVM in gentoo tree, hopefully upstream patches they support llvm 7 , but not much else... 

[cabal-3.2.0.0-build.log](https://github.com/gentoo-haskell/gentoo-haskell/files/4928956/cabal-3.2.0.0-build.log)

[6715](https://github.com/haskell/cabal/issues/6715)

**Comment by trofi** [comment]
ghc-8.8 really needs llvm-7. llvm-10 will not do. You might want to restore old llvm ebuilds locally.

I'm not sure what you mean by "cabal binaries". ghc needs ghc binary and it's dependencies for bootstrapping.

I'm not sure what you mean by "had[d]ock is supposedly their porting layer".

**Comment by necrose99** [comment]
i'm hoping upstream will patch to use more llvm since 7.x ,  
however if they had an **initial statically compiled cabal** would be of use  is possible ... 

ele i can force bins .... see if **eselect is up for llvm** ,... as i have few version.

**Comment by trofi** [comment]
There is not much use of having cabal-bin if ghc does not work.

**Comment by necrose99** [comment]
https://github.com/gentoo-haskell/gentoo-haskell/blob/master/dev-lang/ghc/ghc-8.0.2.ebuild binary works 
i'll have to test  llvm to get cabal as previously mentioned.  
[Sakai's Gentoo](https://github.com/sakaki-/gentoo-on-rpi-64bit) on RPI still has a few vaulted LLVM's /clang versions on slots. 


**just the fact llvm 7 is ram-rod-ed down the gullet .... leaves a sour taste..**. hopefully fixable. latter. 

many of the other things ie for dev-lang/helium build , just dies cause LLVM:7 isnt thier and >LLVM:7's are installed.

**Comment by necrose99** [comment]
https://debian.pkgs.org/10/debian-main-amd64/cabal-install_2.2.0.0-2_amd64.deb.html
