### ISSUE TITLE
llvm-hs packaged 

### ISSUE THREAD

**Issue by necrose99** [gentoo-haskell/gentoo-haskell#1072]
[llvm-hs.zip](https://github.com/gentoo-haskell/gentoo-haskell/files/4972119/llvm-hs.zip)
http://github.com/llvm-hs/llvm-hs/

llvm-hs: General purpose LLVM bindings

hackport'ed manifested good to go.

**Comment by necrose99** [comment]
[llvm-hs-pure.zip](https://github.com/gentoo-haskell/gentoo-haskell/files/4972164/llvm-hs-pure.zip)

**Comment by trofi** [comment]
If you have working ebuilds you can do a pull request against this repository.

**Comment by trofi** [comment]
> [llvm-hs.zip](https://github.com/gentoo-haskell/gentoo-haskell/files/4972119/llvm-hs.zip)

It's hard to review attached `zip` file. The ebuild dependencies don't look complete:

1. `sys-devel/llvm` is only in `DEPEND`. It should probably be in `DEPEND` if final result links against the tools or calls external tools.

2. `sys-devel/llvm` is a slotted package in Gentoo. You'll need to look at llvm.eclass to pull in supported version: https://gitweb.gentoo.org/repo/gentoo.git/tree/eclass/llvm.eclass.

**Comment by necrose99** [comment]
i just ran it against hackport , 
arm64 node other than main desktop main llvm was 10.x , trying to build ghc::haskell 844 ?  it groaned alot..  
was hoping the llvm lib might make building againt newer llvm less complaining..  8 works ish still gripes  a touch .. 

since i'm at breaking the warranty on shiz anyway....  i'll take a run it soon..
