### ISSUE TITLE
dev-haskell/gifcurry depends on broken =dev-haskell/gtk3-0.14.9-r3

### ISSUE THREAD

**Issue by redblade7** [gentoo-haskell/gentoo-haskell#1077]
dev-haskell/gifcurry depends on =dev-haskell/gtk3-0.14.9-r3, which does not compile.

See https://bugs.gentoo.org/736563 which was "fixed" by adding =dev-haskell/gtk3-0.15.5 to the main repo.

**Comment by solpeth** [comment]
It appears that `gifcurry` has not had a release on `hackage` for more than two years. Its dependencies are out of date and need porting, so I'm honestly inclined to remove this package at some point in the future.

I had a quick look at what would be required, and assuming no changes to the `gifcurry` codebase are required it will simply be a matter of loosening dependency upper bounds such as on `base` and `process`. On top of that, `gi-gst-1.0.19` and `gi-gstvideo-1.0.19` will need to be added to the overlay as new dependencies of `gifcurry`.

But I didn't get much further than that. Happy to take a PR though :) [This doc is helpful](https://github.com/gentoo-haskell/gentoo-haskell/blob/master/projects/doc/maintaining-tips.rst#upper-bounds) for dealing with dependency upper bounds, if you would like to have a go yourself.

The process (again, assuming no code changes) should roughly be:

1. `hackport update && hackport merge gifcurry`
2. `hackport merge gi-gst-1.0.19`
3. Fix the dependency on `gstreamer` in `gi-gst` to be `>=media-libs/gstreamer-1.0:=`
4. `hackport merge gi-gstvideo-1.0.19`
5. Repeat step 3 for `gi-gstvideo`
6. See if it builds. If not, something needs to be patched.

Happy to help diagnose things along the way.

**Comment by trofi** [comment]
https://github.com/gentoo-haskell/gentoo-haskell/commit/05edb67f3896a2f7abfc0420ad4bdfe79e9dc9fb one-liner seems to be enough to get `gifcurry` to build against most recent `gtk3` version.

I agree it should be ported to `gi-*` libraries. Ideally I'd like to see it upstream or in a fork instead of an overlay.

**Comment by solpeth** [comment]
Oh, that is great! I did not think to try that. Thank you!

And yes, I agree on the porting.
