### ISSUE TITLE
xmonad and xmonad-contrib live builds

### ISSUE THREAD

**Issue by caseyavila** [gentoo-haskell/gentoo-haskell#1084]
I have noticed the xmonad and xmonad-contrib live builds have been unmaintained and dropped from this overlay. Are there any efforts to get new live builds for these packages?

Perhaps it is irrelevant, but I had been using them successfully before they were dropped.

**Comment by trofi** [comment]
There is no effort to bring live ebuilds back. They were deleted as they did not get updates (otherwise we would just refresh them).

I suggest asking upstreams to release the current git trees and we'll bump the releases (AFAIU there is no active development happening in both projects).

**Comment by caseyavila** [comment]
I see, thanks for the clarification.
