### ISSUE TITLE
rstudio dependency on pandoc-citeproc

### ISSUE THREAD

**Issue by khumba** [gentoo-haskell/gentoo-haskell#1132]
Hello,

I'm not sure if this is too much of a corner case, but: sci-mathematics/rstudio::gentoo has a dependency on dev-haskell/pandoc-citeproc, whose ::haskell version was recently masked for removal.  This is fine, pandoc-citeproc-0.17.0.1::gentoo works, except that 0.17.0.1 doesn't build with ghc-8.10 from this overlay; pandoc-citeproc-0.17.0.2 is needed for that.  So if this overlay is enabled and is globally accepted in package.accept_keywords (`*/*::haskell ~arch`), rstudio (also ~arch) can't be built.

There are fixes in in rstudio's git master to use the replacement citeproc package, but no release of rstudio has it yet.  I'm wondering if perhaps a pandoc-citeproc-0.17.0.2 ebuild can be kept live until a new version of rstudio is released?  Or should I just copy the ebuild locally?

(I'm also eyeing https://bugs.gentoo.org/531996.  I've done a successful build of rstudio without pandoc installed at all, I haven't tested the result out yet though.)

Thanks!

**Comment by ezzieyguywuf** [comment]
This isn't an edge case at all things like this matter.

I think if upstream has fixes that are unreleased, then we're in a very good place.

I've used got before to create a patch for the appropriate files (assuming the changes aren't too huge) and added those patches to the ebuild.

This may be an option here...

**Comment by khumba** [comment]
The commands below show the rstudio branch that did the main pandoc-2.9 to 2.11 bump.  It's not the smallest patch.  There are a bunch of commits after that bump minor Pandoc versions afterward but those commits are trivial.  I might also be missing other changes before this branch.  

    $ git clone https://github.com/rstudio/rstudio.git && cd rstudio
    $ git diff $(git merge-base origin/feature/pandoc-2-11 origin/master)^2..origin/feature/pandoc-2-11

**Comment by markwright** [comment]
Thanks for the instructions on obtaining the pandoc-2.9 to 2.11 bump. It appears that pandoc-citeproc is no longer required in the rstudio 1.4.1103 released on Jan 14 2021.

https://rstudio.com/products/rstudio/release-notes/

However to bump rstudio to 1.4.1103 in portage requires bumping pandoc to >=2.11 in portage.

**Comment by khumba** [comment]
I see!  I first looked into this a couple of weeks back and RStudio hadn't been released at that point.  That's good news.  In that case it's not worth trying to preserve pandoc-citeproc any longer, and yes we'll need pandoc-2.11 in the main tree.  RStudio 1.4.1103 claims a dependency on `PANDOC_VERSION="2.11.2"`; hopefully the PVP is followed and the newer pandoc-2.11.3.1 in the tree will work.

**Comment by trofi** [comment]
Ideally we should not mask packages in `::haskell` until they are masked in `::gentoo`.

**Comment by trofi** [comment]
Pulled `pandoc-citeproc-0.17.0.2` to `::gentoo` as https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=564651cbf5e2c3f6c8e53cfa4632060179650b54. Will also check what it takes to pull `pandoc-2.11` to `::gentoo`.

**Comment by trofi** [comment]
Pulled `pandoc-2.11` into `::gentoo` as https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=21b6084d4c5727afafa8e811343452139fe42705

**Comment by solpeth** [comment]
`pandoc-citeproc` has been last-rited in `::gentoo` with `rstudio` also last-rited as a reverse dependency. Having said that @markwright may be able to get `rstudio` working in the future. Closing this for now as getting `rstudio` working in the future doesn't seem to depend on `pandoc-citeproc` either way.
