### ISSUE TITLE
Merge `parser-combinators-tests` into `parser-combinators`

### ISSUE THREAD

**Issue by ezzieyguywuf** [gentoo-haskell/gentoo-haskell#1136]
Currently, the two are split because that's how upstream does it. This is non-ideal, though, because when `parser-combinators` is emerged with `USE=test`, nothing happens.

We should be able to merge the two by adding the `parser-combinators-tests` package to the `SRC_URI` in `parser-combinators`.

Once we have the source, though, some work will need do be done to ensure things work correctly - it may be as easy as merging the two source directories, but I'm not really sure...

**Comment by solpeth** [comment]
Good luck! I tried to have a play with this long ago, so if I can help let me know.

**Comment by trofi** [comment]
> Currently, the two are split because that's how upstream does it. This is non-ideal, though, because when parser-combinators is emerged with USE=test, nothing happens.

I think the standard answer here is to use `PDEPEND="test? ( parser-combinators-tests )` dependency.

**Comment by ezzieyguywuf** [comment]
> I think the standard answer here is to use `PDEPEND="test? ( parser-combinators-tests )` dependency.

That's how it was done previously, but this seems wrong though - what would cause the `parser-combinators-tests` executable to run? just call it directly from `src_test`? Per my (limited) understanding of `PDEPEND`, I don't think we can rely on the `PDEPEND` atom to be installed in time in order to execute it in `src_test`.

My idea was to simply fetch both sources, compile both, run both.
