### ISSUE TITLE
Cyclic dependency on Gentoo

### ISSUE THREAD

**Issue by peigongdsd** [gentoo-haskell/gentoo-haskell#1141]
When I try to emerge haskell-platform I got this

 * Error: circular dependencies:

(dev-haskell/semigroups-0.18.5-r1:0/0.18.5::haskell, ebuild scheduled for merge) depends on
 (dev-haskell/unordered-containers-0.2.13.0:0/0.2.13.0::haskell, ebuild scheduled for merge) (buildtime_slot_op)
  (dev-haskell/cabal-3.2.1.0-r1:0/3.2.1.0::haskell, ebuild scheduled for merge) (buildtime)
   (dev-haskell/parsec-3.1.14.0:0/3.1.14.0::haskell, ebuild scheduled for merge) (buildtime_slot_op)
    (dev-haskell/semigroups-0.18.5-r1:0/0.18.5::haskell, ebuild scheduled for merge) (buildtime_slot_op)

**Comment by ezzieyguywuf** [comment]
Can you post `emerge --info` please?

**Comment by peigongdsd** [comment]
I don't think it's a problem of haskell-platform. In fact, in this situation, I can install neither of semigroups, unordered-containers, cabal, or parsec. 

emerge --info 
krusl@KruslPC ~/Downloads $ emerge --info
Portage 3.0.14 (python 3.8.7-final-0, default/linux/amd64/17.1/desktop/gnome/systemd, gcc-9.3.0, glibc-2.32-r7, 5.4.80-gentoo-r1kruslpc x86_64)
=================================================================
System uname: Linux-5.4.80-gentoo-r1kruslpc-x86_64-Intel-R-_Xeon-R-_CPU_E5-2650_0_@_2.00GHz-with-glibc2.2.5
KiB Mem:    16308620 total,   7562004 free
KiB Swap:   17301500 total,  16860924 free
Timestamp of repository gentoo: Sun, 24 Jan 2021 07:45:01 +0000
Head commit of repository gentoo: a2bca8432509d86fb732a2af3372660cffdfa24d
Timestamp of repository haskell: Sun, 24 Jan 2021 01:33:22 +0000
Head commit of repository haskell: 48b794b45348720c1d68914ffeabd0f430eb4807

Timestamp of repository snapd: Sat, 23 Jan 2021 10:42:04 +0000
Head commit of repository snapd: 4884e99cfb109cb255339c53313f915dd3c2ab2a

sh bash 5.1_p4
ld GNU ld (Gentoo 2.34 p6) 2.34.0
app-shells/bash:          5.1_p4::gentoo
dev-lang/perl:            5.32.0-r1::gentoo
dev-lang/python:          2.7.18-r5::gentoo, 3.8.7-r1::gentoo, 3.9.1-r1::gentoo
dev-util/cmake:           3.19.3::gentoo
sys-apps/baselayout:      2.7-r1::gentoo
sys-apps/sandbox:         2.20::gentoo
sys-devel/autoconf:       2.13-r1::gentoo, 2.69-r5::gentoo
sys-devel/automake:       1.16.3-r1::gentoo
sys-devel/binutils:       2.34-r2::gentoo, 2.35.1-r1::gentoo
sys-devel/gcc:            9.3.0-r2::gentoo, 10.2.0-r5::gentoo
sys-devel/gcc-config:     2.3.3::gentoo
sys-devel/libtool:        2.4.6-r6::gentoo
sys-devel/make:           4.3::gentoo
sys-kernel/linux-headers: 5.10::gentoo (virtual/os-headers)
sys-libs/glibc:           2.32-r7::gentoo
Repositories:

gentoo
    location: /var/db/repos/gentoo
    sync-type: rsync
    sync-uri: rsync://mirrors.tuna.tsinghua.edu.cn/gentoo-portage
    priority: -1000
    sync-rsync-verify-metamanifest: yes
    sync-rsync-extra-opts: 
    sync-rsync-verify-max-age: 24
    sync-rsync-verify-jobs: 1

haskell
    location: /var/db/repos/haskell
    sync-type: git
    sync-uri: https://github.com/gentoo-mirror/haskell.git
    masters: gentoo

snapd
    location: /var/db/repos/snapd
    sync-type: git
    sync-uri: https://github.com/gentoo-mirror/snapd.git
    masters: gentoo

ACCEPT_KEYWORDS="amd64 ~amd64"
ACCEPT_LICENSE="*"
CBUILD="x86_64-pc-linux-gnu"
CFLAGS="-march=native -O2 -pipe"
CHOST="x86_64-pc-linux-gnu"
CONFIG_PROTECT="/etc /usr/share/gnupg/qualified.txt"
CONFIG_PROTECT_MASK="/etc/ca-certificates.conf /etc/dconf /etc/env.d /etc/fonts/fonts.conf /etc/gconf /etc/gentoo-release /etc/revdep-rebuild /etc/sandbox.d /etc/terminfo"
CXXFLAGS="-march=native -O2 -pipe"
DISTDIR="/var/cache/distfiles"
ENV_UNSET="CARGO_HOME DBUS_SESSION_BUS_ADDRESS DISPLAY GOBIN GOPATH PERL5LIB PERL5OPT PERLPREFIX PERL_CORE PERL_MB_OPT PERL_MM_OPT XAUTHORITY XDG_CACHE_HOME XDG_CONFIG_HOME XDG_DATA_HOME XDG_RUNTIME_DIR"
FCFLAGS="-march=native -O2 -pipe"
FEATURES="assume-digests binpkg-docompress binpkg-dostrip binpkg-logs config-protect-if-modified distlocks ebuild-locks fixlafiles ipc-sandbox merge-sync multilib-strict network-sandbox news parallel-fetch pid-sandbox preserve-libs protect-owned qa-unresolved-soname-deps sandbox sfperms strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync xattr"
FFLAGS="-march=native -O2 -pipe"
GENTOO_MIRRORS="https://mirrors.tuna.tsinghua.edu.cn/gentoo"
LANG="en_US.utf8"
LDFLAGS="-Wl,-O1 -Wl,--as-needed"
MAKEOPTS="-j32"
PKGDIR="/var/cache/binpkgs"
PORTAGE_CONFIGROOT="/"
PORTAGE_RSYNC_OPTS="--recursive --links --safe-links --perms --times --omit-dir-times --compress --force --whole-file --delete --stats --human-readable --timeout=180 --exclude=/distfiles --exclude=/local --exclude=/packages --exclude=/.git"
PORTAGE_TMPDIR="/var/tmp"
USE="X a52 aac acl acpi alsa amd64 berkdb bluetooth branding bzip2 cairo cdda cdr cli colord crypt cups dbus dri dts dvd dvdr eds emboss encode evo exif flac fortran gdbm gif gnome gnome-keyring gnome-online-accounts gpm gstreamer gtk gui iconv icu initramfs introspection ipv6 jpeg lcms libglvnd libnotify libsecret libtirpc mad mng mp3 mp4 mpeg multilib nautilus ncurses networkmanager nls nptl ogg opengl openmp pam pango pcre pdf png policykit ppds pulseaudio readline sdl seccomp spell split-usr ssl startup-notification svg sysprof systemd tcpd threads tiff tracker truetype udev udisks unicode upower usb vorbis wayland wxwidgets x264 xattr xcb xml xv xvid zlib" ABI_X86="64" ADA_TARGET="gnat_2018" ALSA_CARDS="ali5451 als4000 atiixp atiixp-modem bt87x ca0106 cmipci emu10k1x ens1370 ens1371 es1938 es1968 fm801 hda-intel intel8x0 intel8x0m maestro3 trident usb-audio via82xx via82xx-modem ymfpci" APACHE2_MODULES="authn_core authz_core socache_shmcb unixd actions alias auth_basic authn_alias authn_anon authn_dbm authn_default authn_file authz_dbm authz_default authz_groupfile authz_host authz_owner authz_user autoindex cache cgi cgid dav dav_fs dav_lock deflate dir disk_cache env expires ext_filter file_cache filter headers include info log_config logio mem_cache mime mime_magic negotiation rewrite setenvif speling status unique_id userdir usertrack vhost_alias" CALLIGRA_FEATURES="karbon sheets words" COLLECTD_PLUGINS="df interface irq load memory rrdtool swap syslog" CPU_FLAGS_X86="aes avx mmx mmxext pclmul popcnt sse sse2 sse3 sse4_1 sse4_2 ssse3" ELIBC="glibc" GPSD_PROTOCOLS="ashtech aivdm earthmate evermore fv18 garmin garmintxt gpsclock greis isync itrax mtk3301 nmea ntrip navcom oceanserver oldstyle oncore rtcm104v2 rtcm104v3 sirf skytraq superstar2 timing tsip tripmate tnt ublox ubx" INPUT_DEVICES="libinput" KERNEL="linux" LCD_DEVICES="bayrad cfontz cfontz633 glk hd44780 lb216 lcdm001 mtxorb ncurses text" LIBREOFFICE_EXTENSIONS="presenter-console presenter-minimizer" LUA_SINGLE_TARGET="lua5-1" LUA_TARGETS="lua5-1" OFFICE_IMPLEMENTATION="libreoffice" PHP_TARGETS="php7-3 php7-4" POSTGRES_TARGETS="postgres10 postgres11" PYTHON_SINGLE_TARGET="python3_8" PYTHON_TARGETS="python2_7 python3_8" RUBY_TARGETS="ruby25 ruby26 ruby27" USERLAND="GNU" VIDEO_CARDS="radeon r600" XTABLES_ADDONS="quota2 psd pknock lscan length2 ipv4options ipset ipp2p iface geoip fuzzy condition tee tarpit sysrq steal rawnat logmark ipmark dhcpmac delude chaos account"
Unset:  CC, CPPFLAGS, CTARGET, CXX, EMERGE_DEFAULT_OPTS, INSTALL_MASK, LC_ALL, LINGUAS, PORTAGE_BINHOST, PORTAGE_BUNZIP2_COMMAND, PORTAGE_COMPRESS, PORTAGE_COMPRESS_FLAGS, PORTAGE_RSYNC_EXTRA_OPTS


emerge output:
krusl@KruslPC ~/Downloads $ cabal install semigroups-0.18.5 --lib
Resolving dependencies...
Up to date
krusl@KruslPC ~/Downloads $ sudo emerge parsec

 * IMPORTANT: 9 news items need reading for repository 'gentoo'.
 * Use eselect news read to view new items.


 * IMPORTANT: config file '/etc/portage/package.use/vim' needs updating.
 * See the CONFIGURATION FILES and CONFIGURATION FILES UPDATE TOOLS
 * sections of the emerge man page to learn how to update config files.
Calculating dependencies... done!


[ebuild  N     ] dev-haskell/parsec-3.1.14.0:0/3.1.14.0::haskell  USE="doc profile -hoogle -hscolour" 35 KiB
[ebuild  N     ]  dev-haskell/semigroups-0.18.5-r1:0/0.18.5::haskell  USE="binary doc profile transformers -hoogle -hscolour" 20 KiB
[ebuild  N     ]   dev-haskell/unordered-containers-0.2.13.0:0/0.2.13.0::haskell  USE="doc profile -debug -hoogle -hscolour -test" 53 KiB
[ebuild  N     ]    dev-haskell/cabal-3.2.1.0-r1:0/3.2.1.0::haskell  USE="doc profile -hoogle -hscolour" 805 KiB
[ebuild  N     ]   dev-haskell/nats-1.1.2-r1:0/1.1.2::haskell  USE="binary hashable profile template-haskell" 11 KiB
[ebuild  N     ]    dev-haskell/hashable-1.3.0.0:0/1.3.0.0::haskell  USE="doc profile -examples -hoogle -hscolour -test" CPU_FLAGS_X86="sse2 sse4_1" 35 KiB

Total: 6 packages (6 new), Size of downloads: 956 KiB

 * Error: circular dependencies:

(dev-haskell/semigroups-0.18.5-r1:0/0.18.5::haskell, ebuild scheduled for merge) depends on
 (dev-haskell/unordered-containers-0.2.13.0:0/0.2.13.0::haskell, ebuild scheduled for merge) (buildtime_slot_op)
  (dev-haskell/cabal-3.2.1.0-r1:0/3.2.1.0::haskell, ebuild scheduled for merge) (buildtime)
   (dev-haskell/parsec-3.1.14.0:0/3.1.14.0::haskell, ebuild scheduled for merge) (buildtime_slot_op)
    (dev-haskell/semigroups-0.18.5-r1:0/0.18.5::haskell, ebuild scheduled for merge) (buildtime_slot_op)

 * Note that circular dependencies can often be avoided by temporarily
 * disabling USE flags that trigger optional dependencies.

**Comment by ezzieyguywuf** [comment]
Great, thank you for the extra information. I will work to replicate the issue and try to find a solution.

**Comment by peigongdsd** [comment]
em... I think the proper solution may be 1. install cabal binary manually 2. emerge unordered-containers while ignoring the absence of the cabal package 3.emerge cabal. Is this possible? can portage just ignore some package like dpkg does?

**Comment by ezzieyguywuf** [comment]
Confirmed with `*/*::haskell doc` in `package.use` and `emerge -1av semigroups` in a clean gentoo environment.

Also confirmed that 33a43f09070b638c33afeab108908dae186daf5c fixes the problem.

**Comment by trofi** [comment]
I think I fixed at least one circle at: https://github.com/gentoo-haskell/gentoo-haskell/commit/33a43f09070b638c33afeab108908dae186daf5c

And `find-dep-loops.bash` reports a lot more loops we should fix. Incomplete list:

```
dev-haskell/xml-1.3.14
tsort: -: input contains a loop:
tsort: dev-haskell/ansi-wl-pprint-0.6.9
tsort: dev-haskell/cabal-3.2.1.0-r1
tsort: dev-haskell/parsec-3.1.14.0
tsort: dev-haskell/semigroups-0.18.5-r1
tsort: dev-haskell/unordered-containers-0.2.13.0
tsort: dev-haskell/test-framework-hunit-0.3.0.2-r1
tsort: dev-haskell/test-framework-0.8.2.0-r2
tsort: -: input contains a loop:
tsort: dev-haskell/ansi-wl-pprint-0.6.9
tsort: dev-haskell/cabal-3.2.1.0-r1
tsort: dev-haskell/parsec-3.1.14.0
tsort: dev-haskell/semigroups-0.18.5-r1
tsort: dev-haskell/unordered-containers-0.2.13.0
tsort: dev-haskell/test-framework-hunit-0.3.0.2-r1
tsort: dev-haskell/test-framework-0.8.2.0-r2
tsort: -: input contains a loop:
tsort: dev-haskell/ansi-wl-pprint-0.6.9
tsort: dev-haskell/cabal-3.2.1.0-r1
tsort: dev-haskell/parsec-3.1.14.0
tsort: dev-haskell/semigroups-0.18.5-r1
tsort: dev-haskell/unordered-containers-0.2.13.0
tsort: dev-haskell/test-framework-hunit-0.3.0.2-r1
tsort: dev-haskell/test-framework-0.8.2.0-r2
tsort: -: input contains a loop:
tsort: dev-haskell/ansi-wl-pprint-0.6.9
tsort: dev-haskell/cabal-3.2.1.0-r1
tsort: dev-haskell/parsec-3.1.14.0
tsort: dev-haskell/semigroups-0.18.5-r1
tsort: dev-haskell/unordered-containers-0.2.13.0
tsort: dev-haskell/test-framework-hunit-0.3.0.2-r1
tsort: dev-haskell/test-framework-0.8.2.0-r2
dev-haskell/ansi-wl-pprint-0.6.9
tsort: -: input contains a loop:
tsort: dev-haskell/base-orphans-0.8.4
tsort: dev-haskell/cabal-3.2.1.0-r1
tsort: dev-haskell/parsec-3.1.14.0
tsort: dev-haskell/semigroups-0.18.5-r1
tsort: dev-haskell/unordered-containers-0.2.13.0
tsort: dev-haskell/test-framework-hunit-0.3.0.2-r1
tsort: dev-haskell/test-framework-0.8.2.0-r2
tsort: -: input contains a loop:
tsort: dev-haskell/base-orphans-0.8.4
tsort: dev-haskell/cabal-3.2.1.0-r1
tsort: dev-haskell/parsec-3.1.14.0
tsort: dev-haskell/semigroups-0.18.5-r1
tsort: dev-haskell/unordered-containers-0.2.13.0
tsort: dev-haskell/test-framework-hunit-0.3.0.2-r1
tsort: dev-haskell/test-framework-0.8.2.0-r2
```

**Comment by ezzieyguywuf** [comment]
Here's a list of remaining circular dependencies. I've created it using e4dda99ccbe66785e08dd6ef5567de1782a32338 as well as [this new helper script](https://github.com/gentoo-haskell/gentoo-haskell/blob/master/projects/format_dep_loops.py).

The list is very small now compared to a few hours ago, thank you @trofi!

- [ ] aeson → these → aeson
- [ ] temporary → test?=base-compat → test?=hspec → hspec-core → test?=temporary

**Comment by ezzieyguywuf** [comment]
For the last one, looks like we need to remove `these-1.0.1-r1`, however:

-  `reflex-0.6.3-r2` still needs it, and the newer `reflex-0.8.0.0` was only recently unmasked
- `reflex-backend-socket-0.2.0.0` needs it too, but this is already masked for removal

**Comment by trofi** [comment]
We should have a handle on at least initially reported lookps.
