### ISSUE TITLE
cryptohash-sha256: tasty dependency conflict

### ISSUE THREAD

**Issue by ezzieyguywuf** [gentoo-haskell/gentoo-haskell#1144]
With `USE=test emerge -pve1 hledger-lib cryptohash-sha256`, a dependency conflict occurs because `hledger-lib` wants `>=dev-haskell/tasty-1.2.3` but `cryptohash-sha256` wants `<dev-haskell/tasty-1.2`

**Comment by solpeth** [comment]
Thank you both for spotting and sorting this.
