### ISSUE TITLE
Unmask random-1.2

### ISSUE THREAD

**Issue by ezzieyguywuf** [gentoo-haskell/gentoo-haskell#1165]
I think it's time to unmask random-1.2. `cabal-install-3.4.0.0` was released
recently, and it requires `~dev-haskell/random-1.2`, which in my opinion is a
good enough reason to figure this out.

I've done large updates like this via PR's in the past, but I'm going to try to
use an issue this time. This first comment will be used to set a plan, and will
be updated as necessary.

For any package that has an issue, I will try (in this order):

1. See if it's an older version, and the newer version is good. If so, just get
   rid of the old version
2. See if there's a newer version that solves the conflict - if so, create  list
   for the updated package to see if any OTHER revdeps are affected. That list
   will be added to this comment
3. See if we can patch or `cabal_chdep` things to resolve the conflict
4. See if we can remove the package 😮 (don't worry, I'll ask first)

All changes can be tracked on [this branch][1] in my personal gentoo-haskell
fork. I can go ahead and open a PR against this branch if anyone thinks that
will be helpful

[1]: https://github.com/ezzieyguywuf/gentoo-haskell/tree/update_random

Has dep for <dev-haskell/random-1.2
---------------------------------------
- [x] x11-misc/xmonad-wallpaper-0.0.1.4-r2
    - [ ] Needs testing, no test-suite. Used `cabal_chdep`
- [ ] app-text/pandoc-2.11.4
    - on hold, many many deps, and some transient deps on old random
    - also on tasty-1.4 list
- [ ] uuid-1.3.13-r1
    - uuid-1.3.14 is added but masked due to tasty-1.4.
    - need to try `cabal_chdep`, but i'll wait until I can get some opinions on
      the tasty thing
- [ ] hakyll-4.13.4.1
    - also on tasty-1.4 list
- [ ] cabal-install-3.0.0.0
- [ ] cabal-install-3.2.0.0
- [x] tidal-1.4.8
    - bumped to 1.7.2, will need to remove the old version
- [ ] polysemy-zoo-0.7.0.0
- [ ] snap-server-9999
- [ ] diagrams-contrib-1.4.4-r1
- [ ] gloss-examples-1.13.0.3
- [ ] ircbot-0.6.6
- [ ] parallel-io-0.3.3-r3
- [ ] haxml-1.25.5-r1
- [ ] network-transport-tests-0.2.4.3
- [ ] test-framework-quickcheck2-0.3.0.5-r1
- [ ] glut-2.7.0.15
- [ ] quickcheck-2.13.2
- [ ] vty-5.27
- [ ] reflex-0.6.3-r2
- [ ] reflex-0.8.0.0
- [ ] missingh-1.4.3.0
- [ ] test-framework-0.8.2.0-r2
- [ ] heist-1.1.0.1-r2
- [ ] synthesizer-alsa-0.5.0.5
- [ ] brittany-0.13.1.0

Has dep for <dev-haskell/tasty-1.4 (or less)
--------------------------------------------
Turns out that `uuid-1.3.14` has a lowerbound of `>=tasty-1.4.0.1`, so if we
want to update `uuid`, we get stuck with this huge list related to `tasty` as
well. hrm...

- [ ] pandoc-2.11.4
- [x] ~~purescript-0.13.6~~ this is masked already
- [ ] dhall-json-1.7.4
- [ ] lukku-0.1.1.2
- [ ] hakyll-4.13.1
- [ ] tar-0.4.5.0
- [ ] dhall-1.37.1
- [ ] cborg-0.2.4.0
- [ ] ghc-source-gen-0.4.0.0
- [ ] binary-instances-1.0.1
- [ ] psqueues-0.2.7.2
- [ ] indends-0.5.0.1
- [ ] diagrams-lib-1.4.3-r1
- [ ] ginger-0.10.1.0
- [ ] cabal-install-parsers-0.3.0.1
- [ ] cabal-install-parsers-0.4
- [ ] tree-diff-0.1-r2
- [ ] rere-0.1
- [ ] hackage-security-0.6.0.1-r1
    - [ ] hackage-security-0.5.4.0-r3 doesn't have an upper-bound, check if this is
          from upstream or cabal_chdep, and test with newer tasty
- [ ] stmonadtrans-0.4.4
- [ ] cabal-3.4.0.0 (oh boy...)
- [ ] msgpack-1.0.1.0-r1
- [ ] dbus-1.2.16
- [ ] haskell-names-0.9.9
- [ ] ghc-prof-1.4.1.7
- [ ] text-short-0.1.3
- [ ] serialise-0.2.3.0
- [ ] tasty-ant-xl-1.1.7
- [ ] natural-transformation-0.4-r7
- [ ] binary-orphans-1.0.1 (ohhhhh boiiii....)
- [ ] zlib-0.6.2.2
- [ ] tasty-lua-0.2.3.1
- [ ] time-parsers-0.1.2.1
- [ ] blaze-markup-0.8.2.7
- [ ] aeson-extra-0.4.1.3-r2
- [ ] lattices-2.0.2-r1
- [ ] lattices-2.0.2 (just get rid of this)
- [ ] insert-ordered-containers-0.2.3.1
- [ ] diagrams-solve-0.1.2

**Comment by solpeth** [comment]
This will be done as part of ghc-9.0.2 keywording. Thanks for your work on this so far, and for getting a list together!
