### ISSUE TITLE
log-base-0.8.0.0 fails to build against unliftio-core-0.2

### ISSUE THREAD

**Issue by trofi** [gentoo-haskell/gentoo-haskell#1170]
```
[8 of 9] Compiling Log.Monad        ( src/Log/Monad.hs, dist/build/Log/Monad.o, dist/build/Log/Monad.dyn_o )

src/Log/Monad.hs:126:3: error:
    ‘askUnliftIO’ is not a (visible) method of class ‘MonadUnliftIO’
    |
126 |   askUnliftIO = do
    |   ^^^^^^^^^^^
```

I suspect it's related to recent unmasking in e555dbf0a8e0ce1fba186d456c9317c1055d190f

**Comment by hololeap** [comment]
@trofi Can't we just upgrade `log-base` instead of reverting this commit? The latest version is compatible with `unliftio-core-0.2` and its only reverse dependency, `log-postgres` is compatible with the latest `log-base`.
