### ISSUE TITLE
problem building gi-gdkpixbuf 

### ISSUE THREAD

**Issue by HarryBroeken** [gentoo-haskell/gentoo-haskell#1173]
please have a look at https://github.com/haskell-gi/haskell-gi/issues/339

I found a way around it as mentioned in the link above
Hopefully this is of use to the overlay

>>greetings<<
    Harry

**Comment by solpeth** [comment]
Thanks! I'll try to take a look into it in the next day or so.

**Comment by solpeth** [comment]
I've closed this based on the discussion in your linked upstream issue, specifically that everything should work with `haskell-gi-0.25`. If it still doesn't work for you let me know.
