### ISSUE TITLE
dev-lang/ghc-bin

### ISSUE THREAD

**Issue by necrose99** [gentoo-haskell/gentoo-haskell#1182]
https://github.com/gentoo-haskell/gentoo-haskell/issues/939  
this might be useful also as one could use the upstream binaries and or build newer versions , without breaking the currently installed till full upgrade or the like would be readied/stable and functional 

**dev-lang/ghc-bin** 
 (**USE** upstream Binaries to bootstrap ghc if possible
 ie: like in similar fashion ;  **rust-bin , julia-bin** etc...)   
make install ie /usr/local..... will have base binaries , and build remaining 

ghc-9.0.1-x86_64-deb10-linux-dwarf.tar.xz / ghc-9.0.1-x86_64-deb10-linux.tar.xz, ghc-9.0.1-armv7-deb9-linux.tar.xz ghc-9.0.1-aarch64-deb9-linux.tar.xz and perhaps grave robbing a few debs for other platforms 

app-text/pandoc-bin : https://gitlab.com/src_prepare/src_prepare-overlay/-/tree/master/app-text/pandoc-bin
cabal-install-bin : https://downloads.haskell.org/cabal/cabal-install-3.4.0.0/

once the ghc-bin was installed , one could emerge its replacement 
IE :emerge ghc for arm64/etc would then build regular ghc etc with option to clean dev-lang/ghc-bin/ cabal-bin
emerge -C dev-lang/ghc-bin* cabal-install-bin 

this would make instaling ghc on gentoo bit more easy , and or bootstrapping ghc...

and hopefully the need package bootstrap ghc-gentoo-bins for as many systems .... would be lessened 
other admin/dev hell ...  on more common platforms.

**Comment by trofi** [comment]
Gentoo used to have a ghc-bin ebuild. It was hard to manage and required keeping not one but two ebuilds in sync. It also complicates scenarios of using non-bin ghc when bin was visible and the other way around.
