### ISSUE TITLE
dev-haskell/diagrams-core conflicts

### ISSUE THREAD

**Issue by trofi** [gentoo-haskell/gentoo-haskell#1192]
```
dev-haskell/diagrams-core:0

  (dev-haskell/diagrams-core-1.5.0:0/1.5.0::haskell, ebuild scheduled for merge) USE="doc hscolour profile -hoogle" ABI_X86="(64)" pulled in by
    (no parents that aren't satisfied by other packages in this slot)

  (dev-haskell/diagrams-core-1.4.2-r1:0/1.4.2::haskell, installed) USE="doc hscolour profile -hoogle" ABI_X86="(64)" pulled in by
    <dev-haskell/diagrams-core-1.5:=[profile?] required by (dev-haskell/diagrams-1.4-r1:0/1.4::haskell, ebuild scheduled for merge) USE="cairo gtk profile svg -canvas -postscript -rasterific" ABI_X86="(64)"
    ^                          ^^^ ^     
```

**Comment by markwright** [comment]
One way to fix it would be to bump the reverse dependencies of dev-haskell/diagrams-core-1.5.  Unfortunately some of them fail to build with ghc 9.0.1 so I'm not able to bump them, sorry.

**Comment by trofi** [comment]
No problem! Yeah, I'm slowly doing it locally. A bit hard to test the final result with multiple parallel conflicts.

Thank you for sorting out ghc-9 story! We really need it.

**Comment by trofi** [comment]
I hope I caught most of it with:

d0b209812a dev-haskell/diagrams: allow diagrams-core-1.5
c1f7df2a82 dev-haskell/diagrams-canvas: allow diagrams-core-1.5
0fedde8c43 dev-haskell/diagrams-cairo: allow diagrams-core-1.5
1879e6a51b dev-haskell/diagrams-pgf: allow diagrams-core-1.5
