### ISSUE TITLE
pkgcheck fails when VCS version visible for KEYWORDS="~amd64"

### ISSUE THREAD

**Issue by hololeap** [gentoo-haskell/gentoo-haskell#1205]
Is this always reasonable? Is there a way to turn it off?

```
FAILURE RESULTS
/opt/hostedtoolcache/Python/3.9.6/x64/bin/pkgcheck replay --color y /home/runner/failures.json
dev-haskell/ghc-api-compat
  VisibleVcsPkg: version 8.6.1_pre20210712: VCS version visible for KEYWORDS="~amd64", profile default/linux/amd64/17.0/x32 (56 total)
::error::pkgcheck failed with exit code 1
```

**Comment by trofi** [comment]
Yes. VCS ebuilds can't mirror their artifacts over Gentoo mirrors (or user's $DISTDIR). The solution is usually to make a snapshot and fetch tarball from SCM based on commit hash. Example eclass is https://devmanual.gentoo.org/eclass-reference/vcs-snapshot.eclass/index.html
