### ISSUE TITLE
Rename dev-haskell/hakyll* to www-apps/hakyll*

### ISSUE THREAD

**Issue by hololeap** [gentoo-haskell/gentoo-haskell#1211]
I think it would make sense to rename these packages:

```
dev-haskell/hakyll
dev-haskell/hakyll-agda
dev-haskell/hakyll-sass
```

to

```
www-apps/hakyll
www-apps/hakyll-agda
www-apps/hakyll-sass
```

`dev-haskell/hakyll` is in `::gentoo`, so it would need to be renamed there as well.

**Comment by trofi** [comment]
They are all pure libraries without readily runnable executables. They are not really apps.

**Comment by hololeap** [comment]
Hm, I thought the `hakyll` package came with a `hakyll` executable for generating HTML. I guess it doesn't. I've never used it, to be honest.

**Comment by trofi** [comment]
It always needs a bit of haskell boilerplate supplied by user like https://github.com/trofi/trofi.github.io.gen/blob/master/src/site.hs
