### ISSUE TITLE
Mask pandoc-citeproc for removal

### ISSUE THREAD

**Issue by hololeap** [gentoo-haskell/gentoo-haskell#1212]
> That, and previously masking it for removal in `::haskell` caused issues for `::gentoo`'s pandoc which still required pandoc-citeproc at the time. I think if we can remove all versions which require `pandoc-citeproc` from `::gentoo` and `::haskell` we can then mask for removal.

_Originally posted by @solpeth in https://github.com/gentoo-haskell/gentoo-haskell/issues/1207#issuecomment-885347473_

It looks like `pandoc-2.9.2.1` has been removed so it seems safe to mask `pandoc-citeproc` for removal.

**Comment by solpeth** [comment]
I masked this the other day as part of aeson bumping, and now matoro's PR is merged this should be good to close.
