### ISSUE TITLE
=dev-lang/ghc-8.10.6 very slow download speed

### ISSUE THREAD

**Issue by redblade7** [gentoo-haskell/gentoo-haskell#1216]
Updating to the recently stabilized =dev-lang/ghc-8.10.6 is taking a very long time because https://slyfox.uni.cx/~slyfox/distfiles/ghc-bin-8.10.6-x86_64-pc-linux-gnu.tbz2 is downloading at extremely slow speeds (in the bytes per second).

>13100K .......... .......... .......... .......... .......... 10%  450  2d13h

**Comment by hololeap** [comment]
I'm also seeing very slow connection speeds here:

```
>>> Downloading 'https://slyfox.uni.cx/~slyfox/distfiles/ghc-bin-8.10.6-i686-pc-linux-gnu.tbz2'
--2021-08-28 02:45:32--  https://slyfox.uni.cx/~slyfox/distfiles/ghc-bin-8.10.6-i686-pc-linux-gnu.tbz2
Resolving slyfox.uni.cx (slyfox.uni.cx)... 81.129.83.184
Connecting to slyfox.uni.cx (slyfox.uni.cx)|81.129.83.184|:443... connected.
HTTP request sent, awaiting response... Read error (Connection timed out) in headers.
Retrying.
```

@trofi  @solpeth Are you guys experiencing the same thing?

**Comment by trofi** [comment]
It will take a while to settle. That host has very little egress bandwidth and we currently have 26 concurrent clients.

https://gitweb.gentoo.org/repo/gentoo.git/commit/dev-lang/ghc?id=c3e9bd6f88b4d24a55bd8959f5248732077e376b will trigger binary mirroring to `::gentoo`. Once binary is landed on distfiles it should get better. One of the options is to unkeyword `8.10.6` in `::haskell` until mirroring is finished.

**Comment by Lucretia** [comment]
I had a 37d estimate yesterday. Any chance you can upload this file to github somewhere or mega or dropbox or googlesomething or just anywhere other than that site?

**Comment by trofi** [comment]
Until mirroring to `::gentoo` succeeds as a workaround you can try `USE=ghcbootstrap emerge -v1 ghc`. That should rely on ghc sources and already installed ghc compiler. `8.10.5` might be good enough as a bootstrap.

I don't really have extra bandwidth to upload the binary on top of existing egress load.

**Comment by hololeap** [comment]
@trofi Just make your internet faster

**Comment by hololeap** [comment]
@trofi Is there any sort of ETA on when the files will propagate to the `::gentoo` mirrors?

**Comment by solpeth** [comment]
I'll avoid this in future bumps. Sorry all. As a hands-on workaround, people should be able to download the appropriate binary from here and drop it in `/var/cache/distfiles/`: https://drive.google.com/drive/folders/1lylo-VkOpSMaTKfNtvye48VfUGO1-glD?usp=sharing

If the speeds are still no good, I can seed the files with torrents.

**Comment by trofi** [comment]
I masked `ghc-8.10.6` as https://github.com/gentoo-haskell/gentoo-haskell/commit/729da7d50cea5ea6659b62b90727799f9c95c981 and will unmask when http://distfiles.gentoo.org/distfiles/ start showing the binary.
