### ISSUE TITLE
panic! ModOrigin: hidden module redefined

### ISSUE THREAD

**Issue by hololeap** [gentoo-haskell/gentoo-haskell#1225]
I'm getting this error on a couple packages:

`dev-haskell/lsp-types`
`dev-haskell/optics-extra`:

```
./setup haddock --hyperlink-source

...

haddock: While creating Haddock interface for Data.Text.Optics:

While creating Haddock interface for Data.Text.Optics:

haddock: panic! (the 'impossible' happened)
  (GHC version 8.10.6:
        ModOrigin: hidden module redefined

x: unusable module
y: unusable module
Call stack:
    CallStack (from HasCallStack):
      callStackDoc, called at compiler/utils/Outputable.hs:1179:37 in ghc:Outputable
      pprPanic, called at compiler/main/Packages.hs:228:14 in ghc:Packages

Please report this as a GHC bug:  https://www.haskell.org/ghc/reportabug
```

This error even crops up if you try it as a normal user using `cabal`
(only using `v1` commands; `v2` doesn't seem to have the issue):

```
$ cabal unpack optics-extra
$ cd optics-extra-*
$ cabal v1-build
$ cabal v1-haddock
```

---

Strangely, the workaround seems to be:
1. emerge the package with `USE="-doc"`
2. emerge the package normally

After this, everything works normally.

**Comment by solpeth** [comment]
Does the `use-after-doc-workaround` `CABAL_FEATURES` option work? The naming might be wrong here, but I'm afk.

**Comment by hololeap** [comment]
`dev-haskell/lsp-types` likes to do this.

**Comment by solpeth** [comment]
Closing as assumed to be fixed by upstream ghc patch landed in `dev-lang/ghc-9.0.2-r1`.

**Comment by hololeap** [comment]
This bug is actually separate. I'm not 100% sure of the cause, but it happened even with that patch in `dev-lang/ghc-9.0.2-r1`. It seems to have something to do with the packages being already installed on the system, but in a broken state due to a bumped/changed dependency (pending a `haskell-updater` run). This is likely something we will have to fix on our end, as this is essentially an undefined state according to ghc devs.

**Comment by hololeap** [comment]
I'm working on a more manageable solution for several issues, such as this one, which would benefit from having a more slimmed-down/isolated ghc package index during build. Creating a temporary package index which only includes the packages needed for the build, but not the package being built, should allow us to sidestep this issue.

**Comment by l29ah** [comment]
I get this when i hit `tab` in ghci after `import `:
```
ghc: panic! (the 'impossible' happened)
  (GHC version 9.2.4:
	ModOrigin: hidden module redefined

x: unusable module
y: unusable module
Call stack:
    CallStack (from HasCallStack):
      callStackDoc, called at compiler/GHC/Utils/Panic.hs:181:37 in ghc:GHC.Utils.Panic
      pprPanic, called at compiler/GHC/Unit/State.hs:238:14 in ghc:GHC.Unit.State

Please report this as a GHC bug:  https://www.haskell.org/ghc/reportabug

Leaving GHCi.
```
No lsp or optics here.

**Comment by hololeap** [comment]
@l29ah have you run `haskell-updater` and/or `emerge @preserved-rebuild`?

**Comment by l29ah** [comment]
Sure i did, i can't recompile a bunch of stuff, for instance `skylighting-core`:
```
>>> Compiling source in /var/tmp/portage/dev-haskell/skylighting-core-0.12.3.1/work/skylighting-core-0.12.3.1 ...
./setup build
Preprocessing library for skylighting-core-0.12.3.1..
Building library for skylighting-core-0.12.3.1..
ghc: panic! (the 'impossible' happened)
  (GHC version 9.2.4:
	ModOrigin: hidden module redefined
  x: unusable module
  y: unusable module
  Call stack:
      CallStack (from HasCallStack):
        callStackDoc, called at compiler/GHC/Utils/Panic.hs:181:37 in ghc:GHC.Utils.Panic
        pprPanic, called at compiler/GHC/Unit/State.hs:238:14 in ghc:GHC.Unit.State

Please report this as a GHC bug:  https://www.haskell.org/ghc/reportabug
```

**Comment by l29ah** [comment]
Manually removing `skylighting-core` and reinstalling fixed all the problems.

**Comment by hololeap** [comment]
This probably is just a dupe of #1250 at this point. I thought it was separate since we applied the patch.

**Comment by hololeap** [comment]
Reported by `Arsen` on `#gentoo-haskell`:

```
Building library for skylighting-core-0.13.2..
ghc: panic! (the 'impossible' happened)
  (GHC version 9.2.7:
        ModOrigin: hidden module redefined
  x: unusable module
  y: unusable module
  Call stack:
      CallStack (from HasCallStack):
        callStackDoc, called at compiler/GHC/Utils/Panic.hs:181:37 in ghc:GHC.Utils.Panic
        pprPanic, called at compiler/GHC/Unit/State.hs:238:14 in ghc:GHC.Unit.State
```
