### ISSUE TITLE
Keyword GHC 9.2.4

### ISSUE THREAD

**Issue by hololeap** [gentoo-haskell/gentoo-haskell#1233]
I created a new [branch](https://github.com/gentoo-haskell/gentoo-haskell/tree/ghc-9.2.1) and built `dev-lang/ghc-9.2.1` bootstrapping off of `8.10.6`. So far it seems to be working.

I ran the following succesfully:

```
emerge -1u \
    =dev-haskell/binary-0.8.9.0 \
    =dev-haskell/cabal-3.6.0.0 \
    =dev-haskell/exceptions-0.10.4 \
    =dev-haskell/haskeline-0.8.2 \
    =dev-haskell/mtl-2.2.2 \
    =dev-haskell/parsec-3.1.14.0 \
    =dev-haskell/stm-2.5.0.0 \
    =dev-haskell/terminfo-0.4.1.5 \
    =dev-haskell/text-1.2.5.0 \
    =dev-haskell/transformers-0.5.6.2 \
    =dev-haskell/xhtml-3000.2.2.1
```

Here is my `/etc/portage/package.accept_keywords` I am using:

```
*/*::haskell
~dev-lang/ghc-9.2.1 **
~dev-haskell/binary-0.8.9.0 **
~dev-haskell/cabal-3.6.0.0 **
~dev-haskell/terminfo-0.4.1.5 **
~dev-haskell/text-1.2.5.0 **
```

**Comment by solpeth** [comment]
Cool! It would be interesting to see how up-to-date hackage is with modern ghc. I wonder how far we would get with the 75% rebuild task. I personally don't have time for it for the rest of the year at this stage but great that you've gotten us past the first hurdles.

Thanks!

**Comment by l29ah** [comment]
Any reasons not to merge it into master?

**Comment by hololeap** [comment]
@l29ah It's very much a work-in-progress and the Haskell ecosystem is in flux regarding ghc-9.2 support and aeson-2 support, so it wouldn't make sense to clutter up `master` with a ton of commits that are going to be amended/dropped in the near future.

**Comment by hololeap** [comment]
This is a ways off, closing.

**Comment by amano-kenji** [comment]
What's blocking ghc 9.2?

**Comment by hololeap** [comment]
@amano-kenji Nothing really. 9.2.6 seems to work fine and we could use more testers. I plan on keywording it this week after some more testing.

**Comment by hololeap** [comment]
9.4 is blocked because I can't seem to get `hadrian install` to work, but 9.2 can be built with 9.0, so it's not a big deal except for `USE=ghcbootstrap` needing `<ghc-9.1` installed.
