### ISSUE TITLE
dev-util/hoogle-5.0.18.2: Error: Action generate unknown

### ISSUE THREAD

**Issue by l29ah** [gentoo-haskell/gentoo-haskell#1240]
`hoogle` installs `/etc/cron.daily/hoogle-generate` that produces this error on launch.

**Comment by hololeap** [comment]
Please try replacing the contents of that file with this, and then try again:

```sh
#!/bin/sh

/etc/init.d/hoogle restart
```

This should have the effect of regenerating the database and restarting the `hoogle` daemon every time it's run.

**Comment by hololeap** [comment]
It should look like this in the browser:

![image](https://user-images.githubusercontent.com/5141476/150571990-2bdd41e5-b03e-4f96-9bf0-19a866a456c3.png)

**Comment by hololeap** [comment]
@l29ah Could you try out the new scripts in this revision bump?

**Comment by hololeap** [comment]
You can reopen this if you run into any more problems.
