### ISSUE TITLE
UPDATE: Gentoo mirror adds keywords? Old Title: dev-haskell/text: Ebuild author forgot an entry in...

### ISSUE THREAD

**Issue by dorrellmw** [gentoo-haskell/gentoo-haskell#1246]
Just upgraded GHC to 8.10.7. The first haskell package to be recompiled failed during the installation phase:

```
 * Cabal package 'text-1.2.4.1' is shipped with 'PM:8.10.7' ('8.10.7').
 * Ebuild author forgot an entry in CABAL_CORE_LIB_GHC_PV='PM:8.10.3 PM:8.10.4 PM:8.10.4-r1 PM:8.10.5 PM:8.10.5-r1 PM:8.10.6 PM:9.0.1 PM:9.0.1-r1 PM:9999'.
 * Found in /usr/lib64/ghc-8.10.7/package.conf.d.initial.
 * ERROR: dev-haskell/text-1.2.4.1::haskell failed (install phase):
 *   (no error message)
```

I haven't tried any other haskell packages, so I'm not sure if it's related to just dev-haskell/text or if everything's broken.

**Comment by dorrellmw** [comment]
UPDATE: Looks like it's not supposed to have keywords, but it does?
```
$ grep KEYWORDS /var/db/repos/haskell/dev-lang/ghc/ghc-8.10.7.ebuild
KEYWORDS="~amd64 ~x86"
```
Looks like the Gentoo mirror of this repository added the keywords. Does that make sense?
Compare this...

https://github.com/gentoo-haskell/gentoo-haskell/blob/3a082140434fd44cdf2a871fef3605dac1df876d/dev-lang/ghc/ghc-8.10.7.ebuild#L80

...to this...

https://github.com/gentoo-mirror/haskell/blob/656c70a105d657cb936a0bcf55fa230219eb453e/dev-lang/ghc/ghc-8.10.7.ebuild#L80

**Comment by hololeap** [comment]
I didn't remove the KEYWORDS at first and then I made the mistake of force-pushing the edit. I hoped nobody had synced in the minute or two between the push and the force push, but it seems to have been pulled into the `gentoo-mirror` repo. Sorry about the confusion.

**Comment by dorrellmw** [comment]
There's a sync issue now.

```
>>> Syncing repository 'haskell' into '/var/db/repos/haskell'...
/usr/bin/git fetch origin
remote: Enumerating objects: 10, done.
remote: Counting objects: 100% (10/10), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 6 (delta 4), reused 6 (delta 4), pack-reused 0
Unpacking objects: 100% (6/6), 10.61 KiB | 10.61 MiB/s, done.
From https://github.com/gentoo-haskell/gentoo-haskell
 + fcba0a47b0...3a08214043 master     -> origin/master  (forced update)
Auto-merging dev-lang/ghc/ghc-8.10.7.ebuild
CONFLICT (add/add): Merge conflict in dev-lang/ghc/ghc-8.10.7.ebuild
Automatic merge failed; fix conflicts and then commit the result.
!!! git merge error in /var/db/repos/haskell
```

and now emerge is angry too:
```
$ sudo emerge -avDNu @world

These are the packages that would be merged, in order:

Calculating dependencies //var/db/repos/haskell/dev-lang/ghc/ghc-8.10.7.ebuild: line 80: syntax error near unexpected token `<<<'
/var/db/repos/haskell/dev-lang/ghc/ghc-8.10.7.ebuild: line 80: `<<<<<<< HEAD'
 * ERROR: dev-lang/ghc-8.10.7::haskell failed (depend phase):
 *   error sourcing ebuild
 * 
 * Call stack:
 *   ebuild.sh, line 618:  Called die
 * The specific snippet of code:
 *   			source "$EBUILD" || die "error sourcing ebuild"
 * 
 * If you need support, post the output of `emerge --info '=dev-lang/ghc-8.10.7::haskell'`,
 * the complete build log and the output of `emerge -pqv '=dev-lang/ghc-8.10.7::haskell'`.
 * Working directory: '/usr/lib/python3.9/site-packages'
 * S: '/var/tmp/portage/dev-lang/ghc-8.10.7/work/ghc-8.10.7'                                                         -/var/db/repos/haskell/dev-lang/ghc/ghc-8.10.7.ebuild: line 80: syntax error near unexpected token `<<<'
/var/db/repos/haskell/dev-lang/ghc/ghc-8.10.7.ebuild: line 80: `<<<<<<< HEAD'
 * ERROR: dev-lang/ghc-8.10.7::haskell failed (depend phase):
 *   error sourcing ebuild
 * 
 * Call stack:
 *   ebuild.sh, line 618:  Called die
 * The specific snippet of code:
 *   			source "$EBUILD" || die "error sourcing ebuild"
 * 
 * If you need support, post the output of `emerge --info '=dev-lang/ghc-8.10.7::haskell'`,
 * the complete build log and the output of `emerge -pqv '=dev-lang/ghc-8.10.7::haskell'`.
 * Working directory: '/usr/lib/python3.9/site-packages'
 * S: '/var/tmp/portage/dev-lang/ghc-8.10.7/work/ghc-8.10.7'                                                         //var/db/repos/haskell/dev-lang/ghc/ghc-8.10.7.ebuild: line 80: syntax error near unexpected token `<<<'
/var/db/repos/haskell/dev-lang/ghc/ghc-8.10.7.ebuild: line 80: `<<<<<<< HEAD'
 * ERROR: dev-lang/ghc-8.10.7::haskell failed (depend phase):
 *   error sourcing ebuild
 * 
 * Call stack:
 *   ebuild.sh, line 618:  Called die
 * The specific snippet of code:
 *   			source "$EBUILD" || die "error sourcing ebuild"
 * 
 * If you need support, post the output of `emerge --info '=dev-lang/ghc-8.10.7::haskell'`,
 * the complete build log and the output of `emerge -pqv '=dev-lang/ghc-8.10.7::haskell'`.
 * Working directory: '/usr/lib/python3.9/site-packages'
 * S: '/var/tmp/portage/dev-lang/ghc-8.10.7/work/ghc-8.10.7'                                                         |/var/db/repos/haskell/dev-lang/ghc/ghc-8.10.7.ebuild: line 80: syntax error near unexpected token `<<<'
/var/db/repos/haskell/dev-lang/ghc/ghc-8.10.7.ebuild: line 80: `<<<<<<< HEAD'
 * ERROR: dev-lang/ghc-8.10.7::haskell failed (depend phase):
 *   error sourcing ebuild
 * 
 * Call stack:
 *   ebuild.sh, line 618:  Called die
 * The specific snippet of code:
 *   			source "$EBUILD" || die "error sourcing ebuild"
 * 
 * If you need support, post the output of `emerge --info '=dev-lang/ghc-8.10.7::haskell'`,
 * the complete build log and the output of `emerge -pqv '=dev-lang/ghc-8.10.7::haskell'`.
 * Working directory: '/usr/lib/python3.9/site-packages'
 * S: '/var/tmp/portage/dev-lang/ghc-8.10.7/work/ghc-8.10.7'                                                         
 * S: '/var/tmp/portage/dev-lang/ghc-8.10.7/work/ghc-8.10.7'                                                        ... done!
[ebuild     UD~] dev-lang/ghc-8.10.6:0/8.10.6::haskell [8.10.7:0/8.10.7::haskell] USE="ghcbootstrap gmp (-big-endian) -binary -doc -elfutils -ghcmakebinary -numa -profile -test" 0 KiB
<snip>
```

I'm fairly confident that I can fix this on my end, but hopefully there's something you can do to fix it for everyone.

**Comment by hololeap** [comment]
This is either because of my `git push --force` from earlier (sorry) or because you created a `ghc-8.10.7.ebuild` that would be overwritten by the version being pulled in. 

---

```
line 80: `<<<<<<< HEAD'
```

This occurs because git is trying to merge the two versions of `ghc-8.10.7.ebuild` and needs manual intervention. You can edit the file manually, or use `git mergetool` to help assist you.

My recommendation is to move the `ghc-8.10.7.ebuild` somewhere safe (so you have a backup) and then run `git reset --hard origin/master` to force the tree to the upstream state.

**Comment by dorrellmw** [comment]
I never interfered with `ghc-8.10.7.ebuild`. I don't know how widely-used this overlay is, but presumably everyone who ran `emerge --sync` today will have an angry portage if they synchronized it during the few hours between the force-push and the fix.

For me, I can run `git reset --hard origin/master`, but do you expect everyone else to know to do this? I'm not trying to be critical, but if you have to implement a different fix anyway, I'd rather be in the same boat as everyone else instead of being the one user who already applied a local fix.

**Comment by hololeap** [comment]
`git reset --hard origin/master` will make sure your tree is synchronized with the upstream. Anyone who happened to sync in the minute or two between my `git push` and my `git push --force` will have to do the same.

**Comment by hololeap** [comment]
> Just upgraded GHC to 8.10.7. The first haskell package to be recompiled failed during the installation phase:

These latest commits should fix this. I am currently installing `ghc-8.10.7` in a sandbox, so I'll be doing a bit of testing on my end as well.

**Comment by dorrellmw** [comment]
> `git reset --hard origin/master` will make sure your tree is synchronized with the upstream. Anyone who happened to sync in the minute or two between my `git push` and my `git push --force` will have to do the same.

Ok, but to be clear: that is not when I synchronized. I ran `emerge --sync` sometime after your `git push --force` and before you did whatever you did to fix the Gentoo mirror. From what I can tell, I think that was between 3:09pm EST and 6:26pm EST... which is a bit over three hours, not just a minute or two.

github.com/gentoo-haskell/gentoo-haskell only had the keywords for a couple of minutes, but github.com/gentoo-mirror/haskell had the keywords for a couple hours.

Thanks for the fixes!

**Comment by hololeap** [comment]
Ok. Thanks for the info. I was already scolded for the `git push --force`, so the people running the mirror know about it. Hopefully nobody else runs into the problem, but they can contact us on IRC or open up a bug if they have issues.

**Comment by hololeap** [comment]
You may want to add this to your configs so that you don't accidentally upgrade to `ghc-9.0.2` when we finally "keyword" that version:

`/etc/portage/package.mask/haskell`
```
>=dev-lang/ghc-9
```

**Comment by dorrellmw** [comment]
I can confirm that `git reset --hard origin/master` does fix my local copy of the repo. Thanks again!

(By the way, I use git repositories with my job, and I was unaware of `git push --force`. If it weren't for today, I wouldn't have known about its dangers, either. Also, I never meant to be harsh, I just wanted everyone on the same page regarding the timeline.)

That's good to know, but why wouldn't I want to upgrade to ghc-9? I don't follow Haskell news.

**Comment by hololeap** [comment]
Oh, if you want to upgrade to `ghc-9`, then by all means do so! You stated in the other bug report that you needed to run `ghc-8.10.7` because that was what was installed at your work. Currently we do not support installing multiple versions of GHC simultaneously, so you will have to decide if you want to stay with `8.10.7` or upgrade to `9.0.2` when the time comes.

**Comment by dorrellmw** [comment]
Hm, I think that might have been someone else. Either that or I was submitting bug reports in my sleep (not impossible).

**Comment by hololeap** [comment]
Oh, you're right! That was a different person who opened up #1226

**Comment by dorrellmw** [comment]
Sorry for the confusion!

**Comment by hololeap** [comment]
No problem. If you wouldn't mind, close this bug once you are satisfied that everything is working on your end.

**Comment by dorrellmw** [comment]
I just downgraded `ghc` back to the latest keyworded version, and then I rebuilt `text`, which went well. I'll close the ticket now.

Also, if it's important to stay on a _specific_ version, I would probably do `sudo emerge -av --noreplace =dev-lang/ghc-8.10.6`, since that tells portage I want to keep that version installed. I do this with kernel sources to keep depclean from removing the version I'm actually running. Actually, `sudo emerge -av --noreplace dev-lang/ghc:0/8.10.6` might be even better, since that should allow `-rX` revisions (but I haven't tried it myself). If upgrading to 8.10.7 is OK though, then I'd do as you suggested and just mask versions `>=9`.

**Comment by hololeap** [comment]
Sorry, there was a lot of confusion because I thought you were the person who was requesting `ghc-8.10.7` be added. 

It is unlikely that `ghc-8.10.7` will be keyworded at any point. However, we are actively working on keywording `ghc-9.0.2` and will do so when we deem the rest of the ecosystem ready. You can stay on the latest `~amd64` version, which will be `ghc-8.10.6` until `ghc-9.0.2` is ready.

**Comment by dorrellmw** [comment]
Yep, that was just an FYI since a lot of people don't know that portage can add specific versions of packages to the world file.

9.0.2 will be fine for me once you guys deem it ready. :-)

**Comment by hololeap** [comment]
The reason why we have not given `ghc-8.10.7` any attention is because it does not affect Linux users in any meaningful way, so it would require a rebuild of every `::haskell` package for no reason than to get a pointless version bump. However, someone has been bugging us to add it to the tree.

You just happened to sync at the wrong time and pulled in my mistake :)
