### ISSUE TITLE
compile phase: panic! ModOrigin: hidden module redefined

### ISSUE THREAD

**Issue by hololeap** [gentoo-haskell/gentoo-haskell#1250]
Edit:

This has been fixed in `dev-lang/ghc-9.0.2-r1`. If still happen to come across this error after upgrading, please let us know.

---

Could be related to https://github.com/gentoo-haskell/gentoo-haskell/issues/1225

This happens from time to time. The package will get past its `configure` phase but then panic during compilation:

```
>>> Compiling source in /var/tmp/portage/dev-haskell/singletons-th-3.0/work/singletons-th-3.0 ...
./setup build
Preprocessing library for singletons-th-3.0..
Building library for singletons-th-3.0..
ghc: panic! (the 'impossible' happened)
  (GHC version 9.0.2:
        ModOrigin: hidden module redefined
  x: unusable module
     [broken [th-desugar-1.12-38pMzdTomrxEiZqPzmIQgA,
              th-orphans-0.13.11-3a5TrBSBlpr61R5SKoSoaI]]
  y: unusable module
     [broken [singletons-th-3.0-YpuaOMJykLFT3elCeEPZP,
              th-desugar-1.12-38pMzdTomrxEiZqPzmIQgA]]
  Call stack:
      CallStack (from HasCallStack):
        callStackDoc, called at compiler/GHC/Utils/Outputable.hs:1230:37 in ghc:GHC.Utils.Outputable
        pprPanic, called at compiler/GHC/Unit/State.hs:239:14 in ghc:GHC.Unit.State

Please report this as a GHC bug:  https://www.haskell.org/ghc/reportabug
```

**Comment by hololeap** [comment]
[This patch](https://gist.github.com/hololeap/c605c597dcda46a7aee9ded38fdd8823) seems to help provide some more useful info:

```
>>> Compiling source in /var/tmp/portage/dev-haskell/singletons-th-3.0/work/singletons-th-3.0 ...
./setup build
Preprocessing library for singletons-th-3.0..
Building library for singletons-th-3.0..
ghc: panic! (the 'impossible' happened)
  (GHC version 9.0.2:
        ModOrigin: hidden module redefined
  x: unusable module
     [broken [th-desugar-1.12-38pMzdTomrxEiZqPzmIQgA,
              th-orphans-0.13.11-3a5TrBSBlpr61R5SKoSoaI]]
  y: unusable module
     [broken [singletons-th-3.0-YpuaOMJykLFT3elCeEPZP,
              th-desugar-1.12-38pMzdTomrxEiZqPzmIQgA]]
  Call stack:
      CallStack (from HasCallStack):
        callStackDoc, called at compiler/GHC/Utils/Outputable.hs:1230:37 in ghc:GHC.Utils.Outputable
        pprPanic, called at compiler/GHC/Unit/State.hs:239:14 in ghc:GHC.Unit.State

Please report this as a GHC bug:  https://www.haskell.org/ghc/reportabug
```

**Comment by hololeap** [comment]
I was given some info from @hsyl20 in [#ghc](ircs://irc.libera.chat/#ghc):

```
[2022-02-17 00:38:11] <hololeap> there's a transient bug that we're getting while compiling some packages using ghc-9.0.2 in gentoo. here's the full build output: http://sprunge.us/N4z2Ni?text
[2022-02-17 00:38:22] <hololeap> you can see the panic at line 114
[2022-02-17 00:38:51] <hololeap> this is using ghc patched with this commit: https://gitlab.haskell.org/ghc/ghc/-/commit/c7e801991dc9d4f702e92caf6d6347bbff6a8f3c
[2022-02-17 00:39:39] <hololeap> I'm wondering what could be the underlying cause of this panic and how we can debug it further
[2022-02-17 00:48:16] <hololeap> it looks like the ModuleOrigins would have to both be ModUnusable to produce this output: https://hackage.haskell.org/package/ghc-9.0.2/docs/src/GHC.Unit.State.html#line-197
[2022-02-17 00:48:55] <hololeap> how can we determine what is broken and how to fix it in this scenario?
[2022-02-17 05:53:38] <hsyl20> hololeap the Semigroup instance for ModuleOrigin looks wrong. Combining two ModUnusable should produce another ModUnusable instead of panicing
[2022-02-17 05:56:25] <hsyl20> hololeap looks like an oversight from https://gitlab.haskell.org/ghc/ghc/-/commit/df0f148feae4c3b9653260edff843d561d6d5918
[2022-02-17 05:58:08] <hsyl20> hololeap could you open a ticket?
[2022-02-17 06:01:11] <hsyl20> there are already #16996 and #11050 which are related. Combining two ModHidden shouldn't panic too...
```

**Comment by hololeap** [comment]
There seems to be a workaround that works for both of these bugs simultaneously. The steps are to unmerge _all_ of the packages referenced in the GHC panic (with GHC patched with what I provided earlier), then emerge the package that had the panic. After that, reinstalling the package normally doesn't cause any problems.

For instance, using my example above:

```bash
emerge --oneshot --unmerge \
    dev-haskell/th-desugar \
    dev-haskell/th-orphans \
    dev-haskell/singletons-th \
    && emerge --oneshot dev-haskell/singletons-th
```

Now, this behaves properly:

```
emerge --oneshot dev-haskell/singletons-th
```

I am uncertain if this bug will come back whenever the dependencies of the package get broken again.

**Comment by hsyl20** [comment]
Could you try with (not tested):

```patch
From bad99a0bb7981c0287dbc383176338acea98a2d5 Mon Sep 17 00:00:00 2001
From: Sylvain Henry <sylvain@haskus.fr>
Date: Fri, 18 Feb 2022 11:01:04 +0100
Subject: [PATCH] Quick and dirty fix for ModuleOrigin SemiGroup instance

---
 compiler/GHC/Unit/State.hs | 8 ++++++++
 1 file changed, 8 insertions(+)

diff --git compiler/GHC/Unit/State.hs compiler/GHC/Unit/State.hs
index 2900be0716..a36d77f20f 100644
--- compiler/GHC/Unit/State.hs
+++ compiler/GHC/Unit/State.hs
@@ -235,6 +235,14 @@ instance Semigroup ModuleOrigin where
                 | otherwise = panic "ModOrigin: package both exposed/hidden"
             g Nothing x = x
             g x Nothing = x
+    ModHidden     <> ModHidden      = ModHidden
+    ModUnusable x <> ModUnusable _y = ModUnusable x
+
+    ModUnusable _  <> ModHidden      = ModHidden
+    ModHidden      <> ModUnusable _  = ModHidden
+    ModUnusable _x <> y@ModOrigin{}  = y
+    x@ModOrigin{}  <> ModUnusable _y = x
+
     _x <> _y = panic "ModOrigin: hidden module redefined"
 
 instance Monoid ModuleOrigin where
-- 
2.33.1

```

**Comment by solpeth** [comment]
I've run into this issue again. I'll give the patch a go and report back.

**Comment by hololeap** [comment]
@hsyl20 Thank you so much for taking the time to investigate this. Your patch definitely fixed it. I had two packages that were refusing to compile due to this panic and now they are happily compiling with no errors whatsoever!

**Comment by hololeap** [comment]
@hsyl20 Unfortunately, I spoke too soon. There seems to be a different panic that I'm running into now on packages that were building before:

```
>>> Compiling source in /var/tmp/portage/dev-haskell/generic-lens-2.1.0.0/work/generic-lens-2.1.0.0 ...
./setup build
Preprocessing test suite 'doctests' for generic-lens-2.1.0.0..
Building test suite 'doctests' for generic-lens-2.1.0.0..
[1 of 1] Compiling Main             ( examples/doctest.hs, dist/build/doctests/doctests-tmp/Main.dyn_o )
Linking dist/build/doctests/doctests ...
Preprocessing library for generic-lens-2.1.0.0..
Building library for generic-lens-2.1.0.0..
ghc: panic! (the 'impossible' happened)
  (GHC version 9.0.2:
	lookupModuleWithSuggestions
  generic-lens-2.1.0.0-6iTOoWE6WVL7S58OfNr6Eq Data.Generics.Internal.VL.Prism
  Call stack:
      CallStack (from HasCallStack):
        callStackDoc, called at compiler/GHC/Utils/Outputable.hs:1230:37 in ghc:GHC.Utils.Outputable
        pprPanic, called at compiler/GHC/Unit/State.hs:2022:48 in ghc:GHC.Unit.State

Please report this as a GHC bug:  https://www.haskell.org/ghc/reportabug
```

I have noticed a trend with doctests causing strange panics, even on `ghc-8.10.6`. This package is being rebuilt because of a broken dependency. In the past, this could sometimes be worked around by removing all remnants of the package from the system and then re-compile/install it. I will try that again.

**Comment by hsyl20** [comment]
Ah yes `doctest` is particular because it runs GHC independently of Cabal. Hence it tries to set the correct package flags by itself (see https://hackage.haskell.org/package/doctest-0.20.0/docs/src/PackageDBs.html) but it's fragile.

Also if several builds are going on at the same time, the "package environment file" can be overwritten resulting in weird errors: https://github.com/sol/doctest/issues/239#issuecomment-568165863

**Comment by hololeap** [comment]
@hsyl20 Ok, it sounds like this is something we can try to fix per-package by making sure doctest/cabal-doctest has the right flags/environment.

**Comment by mpickering** [comment]
@hololeap How are you building your package databases? (https://gitlab.haskell.org/ghc/ghc/-/issues/21097)

**Comment by hololeap** [comment]
@mpickering Here is the build log, which should give you most of the answers you're looking for:
https://gist.github.com/hololeap/14975b1320c290b9a22612450f02d02a

Whenever you see one of these lines, it's running `ghc-pkg recache`:
```
* Recaching GHC package DB
```

Let me know if you need any more specific info.

**Comment by hololeap** [comment]
This seems to be resolved. Closing.

**Comment by hololeap** [comment]
Reopening due to bugs filed in `::gentoo` and for `ghc-9.2.4`

From @solpeth:

> (In reply to Khumba from [comment #10](https://bugs.gentoo.org/show_bug.cgi?id=843968#c10))
> 
> > Would it matter that I have USE=binary set on ghc?
> 
> That would be the issue - but it is not your fault.
> 
> ghc-9.0.2 was released upstream with a bug causing the panic you are getting. When we were generating the ghc-9.0.2 bootstrap binaries (which can be directly installed with USE=binary), the upstream bug wasn't found yet. We ended up running into the issue later on, reporting upstream, receiving a patch and applying it to ghc-9.0.2 - but the binary was not rebuilt to carry the patch as we had not run into the issue when building ghc-9.0.2 without USE=binary.
> 
> Until I can regenerate the binaries you may need to disable USE=binary. But I shouldn't be long if you are okay to wait.
> 
> Newer versions of ghc fix this problem upstream, so this shouldn't be an issue again in the future.
> 
> Thanks for reporting!

[Source](https://bugs.gentoo.org/843968#c14)

--- 

From @l29ah:

> I get this when i hit `tab` in ghci after `import `:
> 
> ```
> ghc: panic! (the 'impossible' happened)
>   (GHC version 9.2.4:
> 	ModOrigin: hidden module redefined
> 
> x: unusable module
> y: unusable module
> Call stack:
>     CallStack (from HasCallStack):
>       callStackDoc, called at compiler/GHC/Utils/Panic.hs:181:37 in ghc:GHC.Utils.Panic
>       pprPanic, called at compiler/GHC/Unit/State.hs:238:14 in ghc:GHC.Unit.State
> 
> Please report this as a GHC bug:  https://www.haskell.org/ghc/reportabug
> 
> Leaving GHCi.
> ```
> 
> No lsp or optics here.

[Source](https://github.com/gentoo-haskell/gentoo-haskell/issues/1225#issuecomment-1262874832)
