### ISSUE TITLE
dev-haskell/stack-2.7.4_pre20220125 - Fetched file: stack-9a0683679ad49982fcfb036f87c0f99a78916d2a.tar.gz VERIFY FAILED!

### ISSUE THREAD

**Issue by devurandom** [gentoo-haskell/gentoo-haskell#1259]
dev-haskell/stack-2.7.4_pre20220125 fails to build here:

```
!!! Fetched file: stack-9a0683679ad49982fcfb036f87c0f99a78916d2a.tar.gz VERIFY FAILED!
!!! Reason: Filesize does not match recorded size
!!! Got:      690838
!!! Expected: 690961
```

[build.log](https://github.com/gentoo-haskell/gentoo-haskell/files/8107567/build.log)

**Comment by hololeap** [comment]
It looks like they renamed the inner directory on this tarball from `stack-master` to `stack-9a0683679ad49982fcfb036f87c0f99a78916d2a`. Thanks for reporting.
