### ISSUE TITLE
dev-haskell/gifcurry error: Ambiguous occurrence ‘elem’

### ISSUE THREAD

**Issue by redblade7** [gentoo-haskell/gentoo-haskell#1260]
After recent updates to my system, dev-haskell/gifcurry is no longer rebuilding or installing.
Attached is the build log and emerge --info.

[gifcurry-build.log](https://github.com/gentoo-haskell/gentoo-haskell/files/8112048/gifcurry-build.log)
[gifcurry-emerge-info.txt](https://github.com/gentoo-haskell/gentoo-haskell/files/8112054/gifcurry-emerge-info.txt)

**Comment by hololeap** [comment]
I'm going to take this opportunity to bump `dev-haskell/gi-*`

**Comment by hololeap** [comment]
FYI, the package has been renamed to `media-gfx/gifcurry` and there is now a `gtk` flag for building the GUI.
