### ISSUE TITLE
Can't build stack-2.7.3 with ghc-8.10.*

### ISSUE THREAD

**Issue by Anrock** [gentoo-haskell/gentoo-haskell#1262]
Stack depends on `>=dev-haskell/pantry-0.5.2:=[profile?] <dev-haskell/pantry-0.5.3:=[profile?]`
But ebuild for pantry-0.5.2 was dropped in 9a3c92e7d940a407e031eb5875489977e4d809ed for some reason
And pantry-0.5.3 depends on `>=dev-lang/ghc-9.0.2:=`

So there is no way to build stack with ghc 8.10.*?

**Comment by hololeap** [comment]
Hi, sorry there hasn't been much testing to make sure 8.10 would still work. Is stack the only package you need, or are there any others?

**Comment by Anrock** [comment]
So far I've encountered a problem only with stack since I guess it's the only package that uses pantry. I've recovered pantry ebuild and the deps resolved fine but there was a build failure in sqlite-persistent (or something like that) package, so maybe there are more troubles

**Comment by hololeap** [comment]
You should be able to get portage to resolve `stack-2.7.3` successfully with this latest update: https://github.com/gentoo-haskell/gentoo-haskell/commit/010fc9ed2c024807cdbafde9f554293621d0ba96

**Comment by hololeap** [comment]
Also relevant:

https://github.com/gentoo-haskell/gentoo-haskell/commit/ae9df90ce82dce85ff46b688b5c82a544c4751ac
https://github.com/gentoo-haskell/gentoo-haskell/commit/568b0f36f3ef454e78b637c7892c618c4dc284d6

**Comment by hololeap** [comment]
It will take me a while to spin up a `ghc-8.10.7` sandbox, so feel free to paste any build failures you get here.

**Comment by hololeap** [comment]
I'm getting a build error with `dev-haskell/mustache` and `ghc-8.10.6`, but it's not obvious what is going on.

**Comment by hololeap** [comment]
This is working on my end. You can choose either the latest `stack` with `cabal-3.4`, or `stack-2.7.3` with `cabal-3.2`. Both build successfully in my `ghc-8.10.6` sandbox.
