### ISSUE TITLE
Bump `aeson` to version 2

### ISSUE THREAD

**Issue by hololeap** [gentoo-haskell/gentoo-haskell#1264]
This list will keep track of which packages in the tree do not currently support `>=dev-haskell/aeson-2` so we can see when it is acceptable to bump/unmask:

- [x] dev-haskell/aeson-yaml
- [x] dev-haskell/blank-canvas
- [ ] dev-haskell/cabal-install-parsers
- [x] dev-haskell/cborg-json
- [x] dev-haskell/chronos
- [x] dev-haskell/clash-lib
- [x] dev-haskell/clckwrks-plugin-page
- [x] dev-haskell/clckwrks
- [ ] dev-haskell/ekg
- [ ] dev-haskell/engine-io
- [ ] dev-haskell/fay
- [x] dev-haskell/ginger
- [ ] dev-haskell/git-lfs
- [x] dev-haskell/hackage-security
- [x] dev-haskell/happstack-authenticate
- [ ] dev-haskell/haskell-names
- [x] dev-haskell/hnix
- [ ] dev-haskell/hoauth2
- [x] dev-haskell/hsyaml-aeson
- [ ] dev-haskell/hvega
- [ ] dev-haskell/influxdb
- [ ] dev-haskell/insert-ordered-containers
- [x] dev-haskell/ipv6addr
- [ ] dev-haskell/jsaddle-warp
- [x] dev-haskell/jsaddle-wkwebview
- [x] dev-haskell/jsaddle
- [ ] dev-haskell/kansas-comet
- [ ] dev-haskell/microstache
- [x] dev-haskell/opaleye
- [x] dev-haskell/pandoc-citeproc
- [ ] dev-haskell/persistent
- [ ] dev-haskell/profiteur
- [x] dev-haskell/purescript-ast
- [x] dev-haskell/scotty
- [x] dev-haskell/servant-client-core
- [x] dev-haskell/servant-server
- [x] dev-haskell/servant
- [x] dev-haskell/stylish-haskell
- [ ] dev-haskell/themoviedb
- [x] dev-haskell/threepenny-gui
- [ ] dev-haskell/userid
- [ ] dev-haskell/vimeta
- [ ] dev-haskell/zxcvbn-hs
- [ ] dev-lang/idris
- [x] dev-lang/purescript
- [x] dev-util/brittany
- [x] dev-util/hsdev
- [x] sci-mathematics/agda

**Comment by ragreener1** [comment]
dev-haskell/cborg-json can be marked as done also

**Comment by ragreener1** [comment]
Both done:
- dev-haskell/chronos
- dev-haskell/stylish
