### ISSUE TITLE
Need hmatrix bump to 0.20.2

### ISSUE THREAD

**Issue by waivio** [gentoo-haskell/gentoo-haskell#1266]
Something about the difference between (!k) and (! k)

```
    src/Internal/Util.hs:635:48: error:
          Bang pattern in expression context: !k
          Did you mean to add a space after the '!'?
          |
      635 |             . sortBy (flip compare `on` (abs. (!k)))
          |
```
With commit message: Add a space after ! to adapt to the new rules in ghc-9.0.1
In commit: ddb49febd9216a8775a79d0fa940b1897214912b

**Comment by solpeth** [comment]
Is this fix present in hmatrix 0.20.2? If so, would you like to try creating the new ebuild using hackport and opening a PR for the new version of hmatrix? We can help along the way.

Otherwise we will get around to it eventually.
