### ISSUE TITLE
`CABAL_CORE_LIB_GHC_PV` not matching

### ISSUE THREAD

**Issue by formula-spectre** [gentoo-haskell/gentoo-haskell#1342]
```
 * Package:    dev-haskell/exceptions-0.10.4-r1:0/0.10.4
 * Repository: haskell
 * Maintainer: haskell@gentoo.org
 * USE:        abi_x86_64 amd64 elibc_musl kernel_linux userland_GNU
 * FEATURES:   network-sandbox preserve-libs sandbox userpriv usersandbox
>>> Unpacking source...
>>> Unpacking exceptions-0.10.4.tar.gz to /var/tmp/portage/dev-haskell/exceptions-0.10.4-r1/work
>>> Source unpacked in /var/tmp/portage/dev-haskell/exceptions-0.10.4-r1/work
>>> Preparing source in /var/tmp/portage/dev-haskell/exceptions-0.10.4-r1/work/exceptions-0.10.4 ...
 * CHDEP: 'QuickCheck                 >= 2.5      && < 2.14' -> 'QuickCheck                 >= 2.5'
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/dev-haskell/exceptions-0.10.4-r1/work/exceptions-0.10.4 ...
 * Using cabal-3.4.1.0.
/usr/bin/ghc -hide-all-packages -package Cabal -package base -package binary -package bytestring -package containers -package deepseq -package directory -package exceptions -package filepath -package haskeline -package mtl -package parsec -package pretty -package process -package stm -package template-haskell -package terminfo -package text -package time -package transformers -package unix -package xhtml --make /var/tmp/portage/dev-haskell/exceptions-0.10.4-r1/work/exceptions-0.10.4/Setup.lhs -j4 +RTS -A256M -qb0 -RTS -threaded -dynamic -o setup
[1 of 1] Compiling Main             ( /var/tmp/portage/dev-haskell/exceptions-0.10.4-r1/work/exceptions-0.10.4/Setup.lhs, /var/tmp/portage/dev-haskell/exceptions-0.10.4-r1/work/exceptions-0.10.4/Setup.o )
Linking setup ...
 * Filter '-flto=thin' out of CFLAGS (avoid lto partial linking)
./setup configure --ghc --prefix=/usr --with-compiler=/usr/bin/ghc --with-hc-pkg=/usr/bin/ghc-pkg --prefix=/usr --libdir=/usr/lib --libsubdir=exceptions-0.10.4/ghc-9.0.2 --datadir=/usr/share/ --datasubdir=exceptions-0.10.4/ghc-9.0.2 --disable-tests --ghc-options=-j4 +RTS -A256M -qb0 -RTS --with-ar=x86_64-gentoo-linux-musl-ar --ghc-option=-optc-O3 --ghc-option=-optc-pipe --ghc-option=-optl-Wl,-O1 --ghc-option=-optl-Wl,--as-needed --disable-executable-stripping --docdir=/usr/share/doc/exceptions-0.10.4-r1 --verbose --enable-shared --enable-executable-dynamic --sysconfdir=/etc --disable-library-stripping
Using Parsec parser
Configuring exceptions-0.10.4...

setup: Encountered missing or private dependencies:
template-haskell >=2.2 && <2.17

 * ghc-pkg check: 'checking for other broken packages:'
 * ERROR: dev-haskell/exceptions-0.10.4-r1::haskell failed (configure phase):
 *   setup configure failed
 * 
 * Call stack:
 *     ebuild.sh, line  122:  Called src_configure
 *   environment, line 1916:  Called haskell-cabal_src_configure
 *   environment, line 1584:  Called cabal-configure
 *   environment, line  579:  Called cabal-show-brokens-and-die 'setup configure failed'
 *   environment, line  699:  Called die
 * The specific snippet of code:
 *       die "$@"
 * 
 * If you need support, post the output of `emerge --info '=dev-haskell/exceptions-0.10.4-r1::haskell'`,
 * the complete build log and the output of `emerge -pqv '=dev-haskell/exceptions-0.10.4-r1::haskell'`.
 * The complete build log is located at '/var/tmp/portage/dev-haskell/exceptions-0.10.4-r1/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/dev-haskell/exceptions-0.10.4-r1/temp/environment'.
 * Working directory: '/var/tmp/portage/dev-haskell/exceptions-0.10.4-r1/work/exceptions-0.10.4'
 * S: '/var/tmp/portage/dev-haskell/exceptions-0.10.4-r1/work/exceptions-0.10.4'

```
> template-haskell >=2.2 && <2.17 

in the ebuild there is no dependency on dev-haskell/template, and also, the latest version in repo is 0.2.0.10-r1  
I think there is a missing dep here. Or maybe not and I'm missing a step.  
at any case, I'm on musl-clang, trying to install termonad. Hope this is helpful!

**Comment by hololeap** [comment]
Both `template-haskell` and `exceptions` come [bundled with GHC](https://gitlab.haskell.org/ghc/ghc/-/wikis/commentary/libraries/version-history) and we handle those packages a little differently. 

Some of them, like `exceptions`, we expose as an ebuild but there is a check to see if it already comes bundled with your GHC version:

```bash
CABAL_CORE_LIB_GHC_PV="PM:8.10.5-r1 PM:8.10.6 PM:8.10.7 PM:9.0.1-r1 PM:9.0.2-r1 PM:9.2.4 PM:9999"
```

Others, like `template-haskell`, we do not have an ebuild so it relies on the version that comes bundled with your GHC:

```console
$ ghc-pkg describe template-haskell
name:                 template-haskell
version:              2.17.0.0
...
```

The [`exceptions.cabal`](https://hackage.haskell.org/package/exceptions-0.10.4/revision/0.cabal) that is bundled in the package's tarball has an upper bound on the `template-haskell` package:

```cabal
    template-haskell           >= 2.2      && < 2.17,
```

This is an easy fix, and presumably nobody has ran into it so far because we are all using versions of GHC that come with this version of `exceptions` bundled. Which GHC version are you using?

**Comment by formula-spectre** [comment]
I am using https://github.com/clang-musl-overlay/clang-musl-overlay/blob/master/dev-lang/ghc/ghc-9.0.2.ebuild this version of ghc

**Comment by hololeap** [comment]
It seems to me that `CABAL_CORE_LIB_GHC_PV` should ignore revision numbers, as it is extremely unlikely that the set of bundled libraries will change with a revision bump. That would solve this and other related headaches.

**Comment by hololeap** [comment]
I would also be willing to see if we could merge the `clang-musl-overlay` version of ghc into our version so that you can just use `dev-lang/ghc::haskell`, but that is a separate issue.

**Comment by solpeth** [comment]
@hololeap: we currently write `CABAL_CORE_LIB_GHC_PV` with full ebuild versions, but I believe we can just rely on ghc upstream version numbers if we drop the `PM:` part of the version.

**Comment by hololeap** [comment]
@formula-spectre 8abcb9249c949b15637b44e3097f6973cedb9af3 should take care of the build issue. I'll investigate to see if what @solpeth says is true and then update all the `CABAL_CORE_LIB_GHC_PV`s.

**Comment by formula-spectre** [comment]
all right.. so in the meantime what can I do to help?

**Comment by hololeap** [comment]
@formula-spectre you could test with [my `cabal-core-lib` branch](https://github.com/hololeap/gentoo-haskell/tree/cabal-core-lib).

**Comment by formula-spectre** [comment]
@hololeap will do! I install ghc from your branch and then test if every goes smooth when installing packages from your overlay right?
