### ISSUE TITLE
agda pulls emacs even with USE=-emacs

### ISSUE THREAD

**Issue by l29ah** [gentoo-haskell/gentoo-haskell#1348]
Due to `inherit elisp`.

**Comment by l29ah** [comment]
Seems like other ebuilds that are conditional on `emacs` utilize `elisp-common`.

**Comment by solpeth** [comment]
Possibly related to this? https://bugs.gentoo.org/735148

**Comment by solpeth** [comment]
Oh sorry, completely unrelated. Thanks for your diagnostics. Are you able to fix this and open a PR?

**Comment by l29ah** [comment]
Probably not this year.

**Comment by hololeap** [comment]
It looks like this will be as simple as switching to `elisp-common.eclass`. I'll test.
