### ISSUE TITLE
Stack is no longer supported ?

### ISSUE THREAD

**Issue by apraga** [gentoo-haskell/gentoo-haskell#1353]
Hi,

I cannot find dev-haskell/stack in packages.gentoo.org and it looks like it was removed last month by this commit : https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=f81369cb21bc6792878ffae32a245fcb42b988b7 .

Is there a reason why it was removed ? If that's so, would it be possible to add it back to the GURU overlay ?

Thanks,

**Comment by solpeth** [comment]
Hey @apraga , stack was removed as part of pruning many haskell packages from the ::gentoo repo. This was done to minimise duplication between the ::haskell repo and ::gentoo repo, and helps us to keep the two repos more in sync and less broken and outdated.

`dev-haskell/stack` is still available in the ::haskell repo. Add the haskell repo to your system (e.g. eselect repository enable haskell) and `emerge dev-haskell/stack` should work.
