### ISSUE TITLE
Update dev-haskell/haskell-language-server

### ISSUE THREAD

**Issue by amano-kenji** [gentoo-haskell/gentoo-haskell#1373]
With GHC-9.0.2, haskell-language-server-1.8.0.0 cannot apply code actions to a haskell source file.

https://github.com/haskell/haskell-language-server/issues/3241 is the relevant issue fixed by a more recent version of haskell-language-server.

**Comment by hololeap** [comment]
Thanks for pointing out the bug. I didn't know about that.
