### ISSUE TITLE
dev-haskell/cabal-install-3.6.2.0: now demands time >=1.5.0.1 && <1.11

### ISSUE THREAD

**Issue by l29ah** [gentoo-haskell/gentoo-haskell#1379]
I'm no longer able to rebuild it with ghc-9.2.4:
```
Configuring cabal-install-3.6.2.0...

setup: Encountered missing or private dependencies:
time >=1.5.0.1 && <1.11
```
While i have time-1.11.1.1.

**Comment by hololeap** [comment]
Looks like the `CABAL_CHDEPS` line was removed in d49249aaef015847368954cf269ca48a87780bff, which was a few months ago. That said, they have [a new revision on hackage](https://hackage.haskell.org/package/cabal-install-3.6.2.0/revisions/) that should fix this for you. I'll get the ebuild updated to use this.
