### ISSUE TITLE
dev-haskell/co-log-core fails to compile: cannot satisfy -package cabal-doctest

### ISSUE THREAD

**Issue by Thymelizabeth** [gentoo-haskell/gentoo-haskell#1391]
Just updated to dev-lang/ghc-9.2.6. When rebuilding, dev-haskell/co-log-core failed.

Build log:
 * Package:    dev-haskell/co-log-core-0.3.1.0:0/0.3.1.0
 * Repository: haskell
 * Maintainer: haskell@gentoo.org
 * USE:        abi_x86_64 amd64 elibc_glibc kernel_linux userland_GNU
 * FEATURES:   network-sandbox preserve-libs sandbox userpriv usersandbox
>>> Unpacking source...
>>> Unpacking co-log-core-0.3.1.0.tar.gz to /var/tmp/portage/dev-haskell/co-log-core-0.3.1.0/work
>>> Source unpacked in /var/tmp/portage/dev-haskell/co-log-core-0.3.1.0/work
>>> Preparing source in /var/tmp/portage/dev-haskell/co-log-core-0.3.1.0/work/co-log-core-0.3.1.0 ...
dos2unix: converting file /var/tmp/portage/dev-haskell/co-log-core-0.3.1.0/work/co-log-core-0.3.1.0/co-log-core.cabal to Unix format...
 * Applying co-log-core-0.3.1.0-cabal-doctest.patch ...
 [ ok ]
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/dev-haskell/co-log-core-0.3.1.0/work/co-log-core-0.3.1.0 ...
 * Using cabal-3.6.3.0.
/usr/bin/ghc -hide-all-packages -package Cabal -package base -package binary -package bytestring -package containers -package deepseq -package directory -package exceptions -package filepath -package haskeline -package mtl -package parsec -package pretty -package process -package stm -package template-haskell -package terminfo -package text -package time -package transformers -package unix -package xhtml -package cabal-doctest --make /var/tmp/portage/dev-haskell/co-log-core-0.3.1.0/work/co-log-core-0.3.1.0/Setup.hs -j16 +RTS -A256M -qb0 -RTS -threaded -dynamic -o setup
<command line>: cannot satisfy -package cabal-doctest
    (use -v for more information)
/usr/bin/ghc -hide-all-packages -package Cabal -package base -package binary -package bytestring -package containers -package deepseq -package directory -package exceptions -package filepath -package haskeline -package mtl -package parsec -package pretty -package process -package stm -package template-haskell -package terminfo -package text -package time -package transformers -package unix -package xhtml -package cabal-doctest --make /var/tmp/portage/dev-haskell/co-log-core-0.3.1.0/work/co-log-core-0.3.1.0/Setup.hs -j16 +RTS -A256M -qb0 -RTS -threaded -o setup
<command line>: cannot satisfy -package cabal-doctest
    (use -v for more information)
 * ERROR: dev-haskell/co-log-core-0.3.1.0::haskell failed (configure phase):
 *   compiling /var/tmp/portage/dev-haskell/co-log-core-0.3.1.0/work/co-log-core-0.3.1.0/Setup.hs failed
 * 
 * Call stack:
 *     ebuild.sh, line  136:  Called src_configure
 *   environment, line 1928:  Called haskell-cabal_src_configure
 *   environment, line 1595:  Called cabal-bootstrap
 *   environment, line  498:  Called die
 * The specific snippet of code:
 *           } || make_setup "$@" || die "compiling ${setupmodule} failed";
 * 
 * If you need support, post the output of `emerge --info '=dev-haskell/co-log-core-0.3.1.0::haskell'`,
 * the complete build log and the output of `emerge -pqv '=dev-haskell/co-log-core-0.3.1.0::haskell'`.
 * The complete build log is located at '/var/tmp/portage/dev-haskell/co-log-core-0.3.1.0/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/dev-haskell/co-log-core-0.3.1.0/temp/environment'.
 * Working directory: '/var/tmp/portage/dev-haskell/co-log-core-0.3.1.0/work/co-log-core-0.3.1.0'
 * S: '/var/tmp/portage/dev-haskell/co-log-core-0.3.1.0/work/co-log-core-0.3.1.0'

emerge --info:
Portage 3.0.44 (python 3.10.10-final-0, default/linux/amd64/17.1/desktop, gcc-12, glibc-2.36-r5, 6.1.12-gentoo-x86_64 x86_64)
=================================================================
System uname: Linux-6.1.12-gentoo-x86_64-x86_64-AMD_Ryzen_7_5800H_with_Radeon_Graphics-with-glibc2.36
KiB Mem:    15696304 total,   7511708 free
KiB Swap:   16777212 total,  16777212 free
Timestamp of repository gentoo: Mon, 06 Mar 2023 07:30:01 +0000
Head commit of repository gentoo: bfb6b9334648561502ac4607afeeec33a98ee7b0
Timestamp of repository guru: Sat, 04 Mar 2023 15:16:54 +0000
Head commit of repository guru: 14c02679e5b9a84e2f9485008f6638bd86d5c92b

Timestamp of repository haskell: Mon, 06 Mar 2023 01:46:47 +0000
Head commit of repository haskell: 541bf234c390ed75d454832e17e36a00b07493b9

Timestamp of repository pentoo: Sun, 05 Mar 2023 15:31:49 +0000
Head commit of repository pentoo: 76bcd1b35d0021011f9f98d85c527e9042970c53

Timestamp of repository steam-overlay: Thu, 23 Feb 2023 13:47:16 +0000
Head commit of repository steam-overlay: 5dbabcc794ef909f45c8fb40eec07cebf569e0d1

Timestamp of repository wayland-desktop: Fri, 03 Mar 2023 06:02:36 +0000
Head commit of repository wayland-desktop: 9a4fdbda0cf3bbbb31daa5ab26084fd0e057986c

sh bash 5.1_p16-r2
ld GNU ld (Gentoo 2.39 p5) 2.39.0
app-misc/pax-utils:        1.3.5::gentoo
app-shells/bash:           5.1_p16-r2::gentoo
dev-java/java-config:      2.3.1::gentoo
dev-lang/perl:             5.36.0-r1::gentoo
dev-lang/python:           3.10.10_p2::gentoo, 3.11.2_p1::gentoo
dev-lang/rust:             1.66.1::gentoo
dev-lang/rust-bin:         1.66.1-r1::gentoo
dev-util/cmake:            3.25.2::gentoo
dev-util/meson:            1.0.0::gentoo
sys-apps/baselayout:       2.13-r1::gentoo
sys-apps/openrc:           0.45.2-r2::gentoo
sys-apps/sandbox:          2.29::gentoo
sys-devel/autoconf:        2.13-r7::gentoo, 2.71-r5::gentoo
sys-devel/automake:        1.16.5::gentoo
sys-devel/binutils:        2.39-r4::gentoo
sys-devel/binutils-config: 5.4.1::gentoo
sys-devel/clang:           15.0.7-r1::gentoo
sys-devel/gcc:             11.3.1_p20230120-r1::gentoo, 12.2.1_p20230304::gentoo
sys-devel/gcc-config:      2.8::gentoo
sys-devel/libtool:         2.4.7-r1::gentoo
sys-devel/lld:             15.0.7::gentoo
sys-devel/llvm:            15.0.7::gentoo
sys-devel/make:            4.3::gentoo
sys-kernel/linux-headers:  6.1::gentoo (virtual/os-headers)
sys-libs/glibc:            2.36-r5::gentoo
Repositories:

gentoo
    location: /var/db/repos/gentoo
    sync-type: rsync
    sync-uri: rsync://rsync.gentoo.org/gentoo-portage
    priority: -1000
    volatile: True
    sync-rsync-extra-opts: 
    sync-rsync-verify-metamanifest: yes
    sync-rsync-verify-jobs: 1
    sync-rsync-verify-max-age: 24

guru
    location: /var/db/repos/guru
    sync-type: git
    sync-uri: https://github.com/gentoo-mirror/guru.git
    masters: gentoo
    volatile: True

haskell
    location: /var/db/repos/haskell
    sync-type: git
    sync-uri: https://github.com/gentoo-mirror/haskell.git
    masters: gentoo
    volatile: True

pentoo
    location: /var/db/repos/pentoo
    sync-type: git
    sync-uri: https://github.com/gentoo-mirror/pentoo.git
    masters: gentoo
    volatile: True

steam-overlay
    location: /var/db/repos/steam-overlay
    sync-type: git
    sync-uri: https://github.com/gentoo-mirror/steam-overlay.git
    masters: gentoo
    volatile: True

wayland-desktop
    location: /var/db/repos/wayland-desktop
    sync-type: git
    sync-uri: https://github.com/gentoo-mirror/wayland-desktop.git
    masters: gentoo
    volatile: True

thymelizabeth
    location: /var/db/repos/thymelizabeth
    masters: gentoo
    priority: 100
    volatile: True

ACCEPT_KEYWORDS="amd64"
ACCEPT_LICENSE="*"
CBUILD="x86_64-pc-linux-gnu"
CFLAGS="-O2 -pipe -march=native"
CHOST="x86_64-pc-linux-gnu"
CONFIG_PROTECT="/etc /usr/lib64/libreoffice/program/sofficerc /usr/share/config /usr/share/gnupg/qualified.txt"
CONFIG_PROTECT_MASK="/etc/ca-certificates.conf /etc/dconf /etc/env.d /etc/fonts/fonts.conf /etc/gconf /etc/gentoo-release /etc/revdep-rebuild /etc/sandbox.d /etc/terminfo /etc/texmf/language.dat.d /etc/texmf/language.def.d /etc/texmf/updmap.d /etc/texmf/web2c"
CXXFLAGS="-O2 -pipe -march=native"
DISTDIR="/var/cache/distfiles"
ENV_UNSET="CARGO_HOME DBUS_SESSION_BUS_ADDRESS DISPLAY GDK_PIXBUF_MODULE_FILE GOBIN GOPATH PERL5LIB PERL5OPT PERLPREFIX PERL_CORE PERL_MB_OPT PERL_MM_OPT XAUTHORITY XDG_CACHE_HOME XDG_CONFIG_HOME XDG_DATA_HOME XDG_RUNTIME_DIR XDG_STATE_HOME"
FCFLAGS="-O2 -pipe -march=native"
FEATURES="assume-digests binpkg-docompress binpkg-dostrip binpkg-logs binpkg-multi-instance buildpkg-live config-protect-if-modified distlocks ebuild-locks fixlafiles ipc-sandbox merge-sync multilib-strict network-sandbox news parallel-fetch pid-sandbox preserve-libs protect-owned qa-unresolved-soname-deps sandbox sfperms strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync xattr"
FFLAGS="-O2 -pipe -march=native"
GENTOO_MIRRORS="http://mirror.aarnet.edu.au/pub/gentoo/ http://ftp.swin.edu.au/gentoo http://mirror.lagoon.nc/gentoo/ https://mirror.aarnet.edu.au/pub/gentoo/ https://mirror.lagoon.nc/gentoo/"
LANG="mi_NZ.utf8"
LDFLAGS="-Wl,-O1 -Wl,--as-needed"
LEX="flex"
MAKEOPTS="-j16"
PKGDIR="/var/cache/binpkgs"
PORTAGE_CONFIGROOT="/"
PORTAGE_RSYNC_OPTS="--recursive --links --safe-links --perms --times --omit-dir-times --compress --force --whole-file --delete --stats --human-readable --timeout=180 --exclude=/distfiles --exclude=/local --exclude=/packages --exclude=/.git"
PORTAGE_TMPDIR="/var/tmp"
SHELL="/bin/zsh"
USE="X a52 aac acl acpi alsa amd64 bluetooth branding bzip2 cairo cdda cdr cjk cli crypt cups dbus dri dts dvd dvdr elogind encode exif flac fortran gdbm gif gnome-keyring gpm gstreamer gtk gui iconv icu idn ipv6 jpeg lcms libglvnd libnotify libtirpc mad mng mp3 mp4 mpeg multilib ncurses nls nptl ogg opencl opengl openmp pam pango pcre pdf pipewire png policykit ppds pulseaudio qt5 readline sdl seccomp sound spell split-usr ssl startup-notification svg test-rust tiff truetype udev udisks unicode upower usb v4l vaapi vdpau verify-sig vorbis vulkan wayland wxwidgets x264 xattr xcb xft xml xv xvid zlib zsh-completions" ABI_X86="64" ADA_TARGET="gnat_2021" APACHE2_MODULES="authn_core authz_core socache_shmcb unixd actions alias auth_basic authn_alias authn_anon authn_dbm authn_default authn_file authz_dbm authz_default authz_groupfile authz_host authz_owner authz_user autoindex cache cgi cgid dav dav_fs dav_lock deflate dir disk_cache env expires ext_filter file_cache filter headers include info log_config logio mem_cache mime mime_magic negotiation rewrite setenvif speling status unique_id userdir usertrack vhost_alias" CALLIGRA_FEATURES="karbon sheets words" COLLECTD_PLUGINS="df interface irq load memory rrdtool swap syslog" CPU_FLAGS_X86="mmx mmxext sse sse2 aes avx avx2 f16c fma3 pclmul popcnt rdrand sha sse3 sse4_1 sse4_2 sse4a ssse3" ELIBC="glibc" GPSD_PROTOCOLS="ashtech aivdm earthmate evermore fv18 garmin garmintxt gpsclock greis isync itrax mtk3301 nmea ntrip navcom oceanserver oldstyle oncore rtcm104v2 rtcm104v3 sirf skytraq superstar2 timing tsip tripmate tnt ublox ubx" INPUT_DEVICES="libinput" KERNEL="linux" LCD_DEVICES="bayrad cfontz cfontz633 glk hd44780 lb216 lcdm001 mtxorb ncurses text" LIBREOFFICE_EXTENSIONS="presenter-console presenter-minimizer" LUA_SINGLE_TARGET="lua5-1" LUA_TARGETS="lua5-1" OFFICE_IMPLEMENTATION="libreoffice" PHP_TARGETS="php7-4 php8-0" POSTGRES_TARGETS="postgres12 postgres13" PYTHON_SINGLE_TARGET="python3_10" PYTHON_TARGETS="python3_10" RUBY_TARGETS="ruby27 ruby30" USERLAND="GNU" VIDEO_CARDS="amdgpu radeonsi" XTABLES_ADDONS="quota2 psd pknock lscan length2 ipv4options ipset ipp2p iface geoip fuzzy condition tee tarpit sysrq proto steal rawnat logmark ipmark dhcpmac delude chaos account"
Unset:  ADDR2LINE, AR, ARFLAGS, AS, ASFLAGS, CC, CCLD, CONFIG_SHELL, CPP, CPPFLAGS, CTARGET, CXX, CXXFILT, ELFEDIT, EMERGE_DEFAULT_OPTS, EXTRA_ECONF, F77FLAGS, FC, GCOV, GPROF, INSTALL_MASK, LC_ALL, LD, LFLAGS, LIBTOOL, LINGUAS, MAKE, MAKEFLAGS, NM, OBJCOPY, OBJDUMP, PORTAGE_BINHOST, PORTAGE_BUNZIP2_COMMAND, PORTAGE_COMPRESS, PORTAGE_COMPRESS_FLAGS, PORTAGE_RSYNC_EXTRA_OPTS, RANLIB, READELF, RUSTFLAGS, SIZE, STRINGS, STRIP, YACC, YFLAGS

**Comment by hololeap** [comment]
Thanks for reporting

**Comment by hololeap** [comment]
The new `co-log-core` ebuild should work for you
