### ISSUE TITLE
dev-haskell/haddock-api is not compatible with =dev-lang/ghc-9.2*

### ISSUE THREAD

**Issue by amano-kenji** [gentoo-haskell/gentoo-haskell#1394]
I tried to install dev-haskell/haddock and got this build error.

```
Configuring haddock-api-2.25.1...

setup: Encountered missing or private dependencies:
base >=4.15.0 && <4.16, ghc >=9.0 && <9.1
```

**Comment by l29ah** [comment]
Should be fixed by https://github.com/gentoo-haskell/gentoo-haskell/commit/fe195161291168d211d6bed56b6fc709bd84c037

**Comment by amano-kenji** [comment]
Yes, it's been fixed.
