### ISSUE TITLE
hackport-0.8.2.0 fails to build if dev-haskell/cabal-doctest is not all ready installed

### ISSUE THREAD

**Issue by waivio** [gentoo-haskell/gentoo-haskell#1403]
`hackport-0.8.2.0` fails to build if `dev-haskell/cabal-doctest` is not all ready installed.
The ebuild seems to require `dev-haskell/cabal-doctest` even if the use flag -test is set, but it does not bring the dependency in.
Installing `dev-haskell/cabal-doctest` seems to resolve the issue and allows `hackport-0.8.2.0` to build.

**Comment by hololeap** [comment]
Beyond adding `cabal-doctest` to `DEPEND`, there may be a way to make this togglable with a flag.

**Comment by waivio** [comment]
Works good when I tested it!
Thanks!
