### ISSUE TITLE
skylighting-core:  ghc: panic! (the 'impossible' happened)   (GHC version 9.2.6:         ModOrigin: hidden module redefined   x: unusable module   y: unusable module

### ISSUE THREAD

**Issue by formula-spectre** [gentoo-haskell/gentoo-haskell#1407]
attached to this message is the build.log
[build.log](https://github.com/gentoo-haskell/gentoo-haskell/files/11132633/build.log)
I'm using this ghc: https://github.com/clang-musl-overlay/clang-musl-overlay/blob/master/dev-lang/ghc/ghc-9.2.6.ebuild
i'm on the llvm+musl profile, if any more help is needed tell me!

**Comment by l29ah** [comment]
The bug report is a duplicate. ghc-9.2.6 is broken and long gone from the overlay. The problem doesn't occur with ghc-9.2.7-r1.
I guess we should merge the clang-musl-overlay changes someday.
