### ISSUE TITLE
=dev-haskell/alex-3.2.7.2 fails to build with USE=doc

### ISSUE THREAD

**Issue by redblade7** [gentoo-haskell/gentoo-haskell#1409]
=dev-haskell/alex-3.2.7.2 fails to build with USE=doc

Build log and emerge --info attached.

[alex-build.log](https://github.com/gentoo-haskell/gentoo-haskell/files/11183369/alex-build.log)
[alex-emerge-info.txt](https://github.com/gentoo-haskell/gentoo-haskell/files/11183370/alex-emerge-info.txt)

**Comment by hololeap** [comment]
It looks like they stopped packaging the `doc` directory on Hackage:

**Comment by hololeap** [comment]
It also looks like the went from docbook to sphinx:

- https://github.com/haskell/alex/commit/b603324f967989d7934cbea015c47d5f625e561d
- https://github.com/haskell/alex/commit/9586a1aab4653666db744fad434ab763d3b0354b

**Comment by solpeth** [comment]
Thanks @hololeap
