### ISSUE TITLE
dev-haskell/cabal-install-3.6.2.0-r1 fails to build

### ISSUE THREAD

**Issue by amano-kenji** [gentoo-haskell/gentoo-haskell#1424]
```
src/Distribution/Client/FetchUtils.hs:195:36: error:
    • Couldn't match type ‘Distribution.Types.PackageId.PackageIdentifier’
                     with ‘Cabal-syntax-3.8.1.0:Distribution.Types.PackageId.PackageIdentifier’
      Expected: Cabal-syntax-3.8.1.0:Distribution.Types.PackageId.PackageIdentifier
        Actual: PackageId
      NB: ‘Cabal-syntax-3.8.1.0:Distribution.Types.PackageId.PackageIdentifier’
            is defined in ‘Distribution.Types.PackageId’
                in package ‘Cabal-syntax-3.8.1.0’
          ‘Distribution.Types.PackageId.PackageIdentifier’
            is defined in ‘Distribution.Types.PackageId’
                in package ‘Cabal-3.6.3.0’
    • In the second argument of ‘Sec.downloadPackage'’, namely ‘pkgid’
      In a stmt of a 'do' block: Sec.downloadPackage' rep pkgid path
      In the second argument of ‘($)’, namely
        ‘do info verbosity ("Writing " ++ path)
            Sec.downloadPackage' rep pkgid path’
    |
195 |           Sec.downloadPackage' rep pkgid path
    |                                    ^^^^^
```
Occasionall issues like this break the entire development tool chain and prevent me from doing any work. I'm thinking of moving to ghcup.

**Comment by Thymelizabeth** [comment]
[cabal-install-build.log](https://github.com/gentoo-haskell/gentoo-haskell/files/11781210/cabal-install-build.log)

**Comment by hololeap** [comment]
@amano-kenji gentoo-haskell shouldn't be considered stable. It has always been an experimental testbed and we honestly don't have much in the way of volunteers or time right now, so PRs are welcome.

As far as the bug, this doesn't make any sense to me. Nothing is pulling in `Cabal-syntax` so it shouldn't even be considered.

**Comment by hololeap** [comment]
That said, I haven't gotten to building `cabal-install` with `ghc-9.2.8` because of the work I've been doing with `ghc-9.4.5`, so it is my fault for pushing without testing these important packages. This is a strange error, though.

**Comment by hololeap** [comment]
This doesn't make any sense to me. Nothing is pulling in Cabal-syntax so it shouldn't even be considered. I haven't gotten to building cabal-install with ghc-9.2.8 because of the work I've been doing with ghc-9.4.5, so it is my fault for pushing without testing these important packages.

**Comment by hololeap** [comment]
This might be coming from 10ddecc12359f6cc65227cb5f2f78e993d2b8988

**Comment by hololeap** [comment]
Is anyone able to test https://github.com/hololeap/gentoo-haskell/commit/3ee451b5a722773f86dacc1e97a4227685e3f051? I can't test right now but I'll pull it into `master` once I have confirmation that it fixes this issue.

**Comment by hololeap** [comment]
Seems to be working on my end. I'll pull it into `master`.

**Comment by hololeap** [comment]
I opened up a discussion/survey so that we can get a better idea of what packages should be frequently build-tested. `cabal-install` is obvious (sorry) but there might be others that we need to know people are actually using:

https://github.com/orgs/gentoo-haskell/discussions/1426

**Comment by amano-kenji** [comment]
It is fixed now.
