### ISSUE TITLE
[FIXED] Building foundation 0.0.28 fails with basement 0.0.16

### ISSUE THREAD

**Issue by escalopoulet** [gentoo-haskell/gentoo-haskell#1440]
On my machine, Building foundation 0.0.28 fails when basement 0.0.16 is installed
(which is the version on the gentoo-overlay).

Temp fix for me : after masking basement 0.0.16, basement 0.0.14 is installed instead
and foundation 0.0.28 can be emerged.

It seems that foundation 0.0.28 requires exactly basement 0.0.14 in the 
foundation/foundation.cabal file.

I hope this helps,
Best,
François.

PS: I found no reference to this problem in the other issues, I hope I am not
creating an bad issue.

**Comment by escalopoulet** [comment]
Sory for the noise, this is already fixed. I missed an update of foundation 13hours ago.
Best.

**Comment by solpeth** [comment]
No apology necessary! I'm glad you reported this. I missed your report, but running into the issue myself I pushed a fix.

Keep the reports coming on anything else you find. :)
