### ISSUE TITLE
dev-haskell/connection: change x509-* deps to crypton-x509-*

### ISSUE THREAD

**Issue by vimproved** [gentoo-haskell/gentoo-haskell#1441]
Currently the package is failing to build with `>=tls-1.7.0`, revision 2 of the cabal file sets the upper bound of the tls dependency to <1.7.0.

**Comment by vimproved** [comment]
Nevermind, the only version in tree is tls 1.7.0. Changing the deps from `x509-*` to `crypton-x509-*` seems to make it build with TLS 1.7 though.

**Comment by solpeth** [comment]
Hi vimproved, I've pulled in the hackage revision to `connection` such that it depends on tls < 1.7. However, `connection` should no longer be needed in the repo as all previous reverse dependencies have migrated to `crypton-connection`. A depclean should clear it out going forward.

**Comment by vimproved** [comment]
Oh, alright. Thanks.
