### ISSUE TITLE
Cannot compile hoogle - probably because of dev-haskell/connection and tls ?

### ISSUE THREAD

**Issue by escalopoulet** [gentoo-haskell/gentoo-haskell#1446]
Dear maintainers,

I am troubles compiling hoogle. I am no expert, I am trying to guess the problem
below.

haskell-updater is failing with:
Found the following broken packages:
  * dev-haskell/casa-client:0
  * dev-haskell/crypton-connection:0
  * dev-haskell/hpack:0
  * dev-haskell/http-client-tls:0
  * dev-haskell/http-conduit:0
  * dev-haskell/http-download:0
  * dev-haskell/pantry:0
  * dev-haskell/tls-session-manager:0

Updater's past history:
Pass 1 : dev-haskell/casa-client:0 dev-haskell/crypton-connection:0 dev-haskell/hpack:0 dev-haskell/http-client-tls:0 dev-haskell/http-conduit:0 dev-haskell/http-download:0 dev-haskell/pantry:0 dev-haskell/tls-session-manager:0
Pass 2 : dev-haskell/connection:0
ERROR: Updater stuck in the loop and can't progress

My guess is that there is a conflict between 
* connection-0.3.1-r1 (requiring <tls-1.7)
* crypton-connection-0.3.1 (>=tls-1.7)

$ equery  depends tls
* These packages depend on tls:
dev-haskell/connection-0.3.1-r1 (>=dev-haskell/tls-1.4[profile?])
                                (<dev-haskell/tls-1.7[profile?])
dev-haskell/crypton-connection-0.3.1 (>=dev-haskell/tls-1.7[profile?])
dev-haskell/http-client-tls-0.3.6.2 (>=dev-haskell/tls-1.2[profile?])
dev-haskell/tls-session-manager-0.0.4 (dev-haskell/tls[profile?])

Best,
François.

**Comment by solpeth** [comment]
Fixed in df39dd04e50be63560cf35c1fade7d995c9436bd.
