### ISSUE TITLE
`dev-haskell/connection::gentoo`: types from mismatched packages

### ISSUE THREAD

**Issue by formula-spectre** [gentoo-haskell/gentoo-haskell#1447]
I know the package is not from ::haskell, but everything else is, and I'm kinda lost
here is the full log:
https://bpa.st/RZM5W
and the full error
```
Network/Connection.hs:122:43: error:
    • Couldn't match expected type ‘crypton-x509-store-1.6.9:Data.X509.CertificateStore.CertificateStore’
                  with actual type ‘Data.X509.CertificateStore.CertificateStore’
      NB: ‘crypton-x509-store-1.6.9:Data.X509.CertificateStore.CertificateStore’
            is defined in ‘Data.X509.CertificateStore’
                in package ‘crypton-x509-store-1.6.9’
          ‘Data.X509.CertificateStore.CertificateStore’
            is defined in ‘Data.X509.CertificateStore’
                in package ‘x509-store-1.6.9’
    • In the ‘sharedCAStore’ field of a record
      In the ‘clientShared’ field of a record
      In the expression:
        (TLS.defaultParamsClient (fst cid) portString)
          {TLS.clientSupported = def
                                   {TLS.supportedCiphers = TLS.ciphersuite_default},
           TLS.clientShared = def
                                {TLS.sharedCAStore = globalCertificateStore cg,
                                 TLS.sharedValidationCache = validationCache}}
    |
122 |             { TLS.sharedCAStore         = globalCertificateStore cg
    |                                           ^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by solpeth** [comment]
I will fix this as part of porting everything over to `crypton-connection` from `connection`. I'm testing this in `::haskell` for now, and then will deal with `::gentoo`.

**Comment by solpeth** [comment]
As the `::haskell` repo stands as of 3fb5d602210c3c65a57f1c216c4e875b5d0a3899, the situation should be the following:

- If you are on `::gentoo` only, everything works as it did before
- If you have the `::haskell` repo enabled, every package relying on `dev-haskell/connection` from ::gentoo now has a version available in `::haskell` relying on `crypton-connection`, thus avoiding pulling in `dev-haskell/connection` at all.

If that does not happen (i.e. Portage keeps trying to pull in `dev-haskell/connection`), let me know.

**Comment by formula-spectre** [comment]
can confirm, dev-haskell/connection is not pulled in anymore  
thanks!
