### ISSUE TITLE
Dependency restriction in 'dev-lang/ghc-9.2.8::haskell' restrains updating sphinx to 'dev-python/sphinx-7.0.1::gentoo'

### ISSUE THREAD

**Issue by hereGittyGitty** [gentoo-haskell/gentoo-haskell#1449]
Hi,

I am unable to update `sphinx-6.2.1::gentoo` because
`dev-lang/ghc-9.2.8::haskell` requires `<dev-python/sphinx-7`.

Here is the output of calling `emerge -avp dev-python/sphinx`:

```
These are the packages that would be merged, in order:

Calculating dependencies  ... ... done!
Dependency resolution took 19.20 s.

[ebuild   R   ~] dev-python/sphinx-6.2.1::gentoo  USE="latex -doc -test" PYTHON_TARGETS="python3_10 python3_11 -pypy3 -python3_12" 0 KiB

Total: 1 package (1 reinstall), Size of downloads: 0 KiB

WARNING: One or more updates/rebuilds have been skipped due to a dependency conflict:

dev-python/sphinx:0

  (dev-python/sphinx-7.0.1:0/0::gentoo, ebuild scheduled for merge) USE="latex -doc -test" ABI_X86="(64)" PYTHON_TARGETS="python3_10 python3_11 -pypy3 -python3_12" conflicts with
    <dev-python/sphinx-7[python_targets_python3_10(-),python_targets_python3_11(-)] required by (dev-python/sphinx-rtd-theme-1.2.2:0/0::gentoo, installed) USE="-test" ABI_X86="(64)" PYTHON_TARGETS="python3_10 python3_11 -pypy3 -python3_12"
    ^                  ^                                                           
```

The dependency conflict does not show up here (already added a bug ticket for `dev-python/sphinx-rtd-theme-1.2.2:gentoo`) so this is (part of) the output of `emerge --deep --with-bdeps=y --newuse --update --backtrack=50 @world`

```
[...]
dev-python/sphinx:0

  (dev-python/sphinx-7.0.1:0/0::gentoo, ebuild scheduled for merge) USE="latex -doc -test" ABI_X86="(64)" PYTHON_TARGETS="python3_10 python3_11 -pypy3 -python3_12" conflicts with
    <dev-python/sphinx-7[python_targets_python3_10(-),python_targets_python3_11(-)] required by (dev-python/sphinx-rtd-theme-1.2.2:0/0::gentoo, installed) USE="-test" ABI_X86="(64)" PYTHON_TARGETS="python3_10 python3_11 -pypy3 -python3_12"
    ^                  ^
    <dev-python/sphinx-7 required by (dev-lang/ghc-9.2.8:0/9.2.8::haskell, installed) USE="doc gmp (-big-endian) -binary -elfutils -ghcbootstrap -ghcmakebinary -llvm -numa -profile -test -unregisterised" ABI_X86="(64)"
    ^                  ^
[...]
```

Please update 'dev-lang/ghc' to require '>=dev-python/sphinx-7' if possible.

Thank you :)

Attachments:

- [emerge_info_ghc.log](https://github.com/gentoo-haskell/gentoo-haskell/files/11928998/emerge_info_ghc.log) 
- [emerge_pqv_ghc.log](https://github.com/gentoo-haskell/gentoo-haskell/files/11929000/emerge_pqv_ghc.log)

**Comment by hololeap** [comment]
See:

> ghc 9.4/9.6 documentation build fails with Sphinx 7.0.x

https://gitlab.haskell.org/ghc/ghc/-/issues/23444

---

Looks like they have a MR that might fix this. I'll test it out when I get a chance:

> Update rdt-theme to latest upstream version

https://gitlab.haskell.org/ghc/ghc/-/merge_requests/10520
