### ISSUE TITLE
dev-lang/ghc-9.4.5: hadrian segfaults

### ISSUE THREAD

**Issue by l29ah** [gentoo-haskell/gentoo-haskell#1461]
The place in the build process where it happens seems quite random, but here's the last build log: https://tinystash.undef.im/il/24YP2e6gDXQ9wjXXGwMLNHNRmfSdpozFGHsmd2eeUzDpz9q7P6QqF9P2USbKerFvoFjxTpa7Pqd4FroEFmKNjy3e.txt
Last time it crashed, gdb says:
```
#0  0x00007f52cb2998e9 in shakezm0zi19zi7zmIRv7y5SKm47CHzzmp90YQla_DevelopmentziShakeziInternalziCoreziDatabase_zdfMonadLocked_closure ()
   from /usr/lib64/x86_64-linux-ghc-9.2.8/libHSshake-0.19.7-IRv7y5SKm47CHzmp90YQla-ghc9.2.8.so
#1  0x0000000000000000 in ?? ()
```

**Comment by l29ah** [comment]
Meanwhile i built ghc-9.4.5 fine on another machine that has only 2 HT threads (and single core), not 8.

**Comment by l29ah** [comment]
Also might have something to do with less SIMD ability.

**Comment by l29ah** [comment]
Tried to build it again, and now hadrian just hanged, fully consuming 3 CPU threads.

**Comment by hololeap** [comment]
Unfortunately, it doesn't look like anyone has been able to reproduce this (so far), so it's hard to know what's going on. If I come across any RTS options that might help debug it, I'll let you know.

**Comment by l29ah** [comment]
Also observed with 9.6.2 with `-j8`.
Seems to work fine with `-j2`.

**Comment by hololeap** [comment]
@l29ah, do you still run into this, or do you just set `-j2` by default for ghc on that machine now? I'm trying to get a sense for if this should be closed or not at this point.

**Comment by l29ah** [comment]
I'm no longer using 9.4 anywhere and don't really remember if it was solved or not.

**Comment by l29ah** [comment]
Probably it isn't an issue on 9.8 at least since i routinely build it with -j9.
