### ISSUE TITLE
dev-haskell/hls-overloaded-record-dot-plugin fails to build.

### ISSUE THREAD

**Issue by amano-kenji** [gentoo-haskell/gentoo-haskell#1465]
```
src/Ide/Plugin/OverloadedRecordDot.hs:114:10: error:
    • No instance for (NFData Extension)
        arising from a use of ‘Control.DeepSeq.$dmrnf’
    • In the expression:
        Control.DeepSeq.$dmrnf @(CollectRecordSelectorsResult)
      In an equation for ‘rnf’:
          rnf = Control.DeepSeq.$dmrnf @(CollectRecordSelectorsResult)
      In the instance declaration for
        ‘NFData CollectRecordSelectorsResult’
    |
114 | instance NFData CollectRecordSelectorsResult
    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Every week or two, I encounter errors from haskell overlay. Is there a way to prevent errors of this kind from happening again?

**Comment by l29ah** [comment]
> Is there a way to prevent errors of this kind from happening again?

Tell the authors of the software you use to specify dependencies as described in https://pvp.haskell.org/

**Comment by amano-kenji** [comment]
Maybe, the maintainer should have an automated build bot for every updated package?

**Comment by hololeap** [comment]
@amano-kenji I _did_ build this package and it's currently installed on my system.

**Comment by hololeap** [comment]
You're going to have to provide more details, such as the full build log. Expecting this overlay to be bug-free for every configuration is completely unrealistic.

**Comment by hololeap** [comment]
Looks like https://github.com/gentoo-haskell/hackport/issues/116 struck again and it didn't add the dependencies. That could prevent portage from upgrading the dependencies in the right order.

This could be what @amano-kenji ran into (but who knows, since they didn't provide any context.)

(This plugin can easily be disabled via `USE` flags, btw.)

**Comment by amano-kenji** [comment]
Today, I ran `emerge --sync`, and all haskell packages were built. I think I can close it.
