### ISSUE TITLE
Multiple ebuild failures do to `integer-logarithms-1.0.3.1`

### ISSUE THREAD

**Issue by alecStewart1** [gentoo-haskell/gentoo-haskell#1470]
Hello,

I've only recently started using the gentoo-haskell repo, and the main thing I wanted to install was `hledger`.

That's failed due to another issue I'll open up, but one things I'm noticing is `integer-logarithms-1.0.3.1` causes issues in at least two packages: `hledger` and `stack`.

Ebuild reports:

```
Using Parsec parser
Configuring integer-logarithms-1.0.3.1...

setup: Encountered missing or private dependencies:
base >=4.15 && <4.16, ghc-prim <0.8

 * ghc-pkg check: 'checking for other broken packages:'
 * ERROR: dev-haskell/integer-logarithms-1.0.3.1-r1::gentoo failed (configure phase):
 *   setup configure failed
 *
 * Call stack:
 *     ebuild.sh, line  136:  Called src_configure
 *   environment, line 1840:  Called haskell-cabal_src_configure '--flag=-check-bounds'
 *   environment, line 1515:  Called cabal-configure '--flag=-check-bounds'
 *   environment, line  570:  Called cabal-show-brokens-and-die 'setup configure failed'
 *   environment, line  642:  Called die
 * The specific snippet of code:
 *       die "$@"
```

For both of those packages. According to `equery depeneds dev-haskell/integer-logarithms -a`, the following packages depend on it:

```
 * These packages depend on dev-haskell/integer-logarithms:
dev-haskell/aeson-2.0.3.0 (test ? >=dev-haskell/integer-logarithms-1)
                          (test ? <dev-haskell/integer-logarithms-1.1)
dev-haskell/aeson-2.1.2.1 (test ? >=dev-haskell/integer-logarithms-1)
                          (test ? <dev-haskell/integer-logarithms-1.1)
dev-haskell/arithmoi-0.12.0.0 (>=dev-haskell/integer-logarithms-1.0[profile?])
dev-haskell/bytebuild-0.3.10.0 (>=dev-haskell/integer-logarithms-1.0.3[profile?])
                               (<dev-haskell/integer-logarithms-1.1[profile?])
dev-haskell/cabal-fmt-0.1.6 (test ? >=dev-haskell/integer-logarithms-1.0.3.1)
                            (test ? <dev-haskell/integer-logarithms-1.1)
dev-haskell/lattices-2.0.3 (>=dev-haskell/integer-logarithms-1.0.3[profile?])
                           (<dev-haskell/integer-logarithms-1.1[profile?])
dev-haskell/quickcheck-instances-0.3.27 (>=dev-haskell/integer-logarithms-1.0.3[profile?])
                                        (<dev-haskell/integer-logarithms-1.1[profile?])
dev-haskell/quickcheck-instances-0.3.29.1-r1 (>=dev-haskell/integer-logarithms-1.0.3[profile?])
                                             (<dev-haskell/integer-logarithms-1.1[profile?])
dev-haskell/scientific-0.3.7.0-r1 (>=dev-haskell/integer-logarithms-1.0.3.1[profile?])
                                  (<dev-haskell/integer-logarithms-1.1[profile?])
dev-haskell/scientific-0.3.7.0-r1 (>=dev-haskell/integer-logarithms-1.0.3.1[profile?])
                                  (<dev-haskell/integer-logarithms-1.1[profile?])
```

But I'm not 100% if all of those package has issues when building.

I did _seem_ to resolve this when attempting to install `hledger` by running `haskell-updater --all -- =dev-lang/ghc-9.2.8`. Why that fixes anything I'm not really sure, nor am I sure if it actually fixed the problem.

**Comment by alecStewart1** [comment]
@l29ah your commit for issue #1471 seemed to work but this didn't seem to work as I'm still getting:

```
Configuring integer-logarithms-1.0.3.1...

setup: Encountered missing or private dependencies:
base >=4.15 && <4.16, ghc-prim <0.8

 * ghc-pkg check: 'checking for other broken packages:'
 * ERROR: dev-haskell/integer-logarithms-1.0.3.1-r1::gentoo failed (configure phase):
 *   setup configure failed
 *
 * Call stack:
 *     ebuild.sh, line  136:  Called src_configure
 *   environment, line 1840:  Called haskell-cabal_src_configure '--flag=-check-bounds'
 *   environment, line 1515:  Called cabal-configure '--flag=-check-bounds'
 *   environment, line  570:  Called cabal-show-brokens-and-die 'setup configure failed'
 *   environment, line  642:  Called die
 * The specific snippet of code:
 *       die "$@"
```

**Comment by l29ah** [comment]
Sorry, i thought your issue is about ::haskell. This is not an issue tracker for ::gentoo packages.

**Comment by alecStewart1** [comment]
It is an issue for ::haskell. `dev-haskell/integer-logaritms` is a package in ::haskell. 

I'm saying ee51c8f doesn't seem to fix the issue of `dev-haskell/integer-logaritms` failing to build.

**Comment by l29ah** [comment]
The quoted log features a ::gentoo package. Please provide the log for the ::haskell package.

**Comment by alecStewart1** [comment]
`eix integer-logarithms`:

```
* dev-haskell/integer-logarithms
     Available versions:  (~)1.0.3.1-r1(0/1.0.3.1)^t[1] 1.0.3.1-r1(0/1.0.3.1)^t {doc hoogle hscolour profile test}
     Homepage:            https://github.com/haskellari/integer-logarithms
     Description:         Integer logarithms

[1] "haskell" /var/db/repos/haskell
```

**Comment by alecStewart1** [comment]
https://packages.gentoo.org/packages/dev-haskell/integer-logarithms

Says it's maintained by `Gentoo Haskell`.

Is there some clashing package issue?

**Comment by solpeth** [comment]
@alecStewart1 I appreciate the find. Both packages list the exact same revision (-r1) yet they are different.

The `::haskell` package incorporates all of the upstream revisions to versions bounds for `base`  and `ghc-prim`, whereas the `::gentoo` package is largely untouched.

For whatever reason (expected or not), your system is pulling in or retaining the `::gentoo` package over the `::haskell` package.

I'll move `integer-logarithms` in the `::haskell` repo to `-r2` which should force your system to pull that in.

Thanks for letting us know!

**Comment by l29ah** [comment]
> I'll move `integer-logarithms` in the `::haskell` repo to `-r2` which should force your system to pull that in.

I don't think forcing an useless recursive rebuild of a bunch of packages for all users of ::haskell is a good policy for handling a misconfiguration (that will surely hit again) of one user's system.

**Comment by solpeth** [comment]
@l29ah, it is not ever the user's fault for enabling the ::haskell repo and consequently encountering an issue between the ::gentoo repo and the ::haskell repo. Everything should be automatic and just work.

The user has actually uncovered an issue that we will silently encounter again in the future. Not everyone reports bugs and some users may just give up all together instead of letting us know. So I'm glad we know about this.

It is technically correct to revbump, when you think about it. There are a few parts and our interoperation with ::gentoo is admittedly messy and contributes to the problem:

- Attracting the ire of many a Gentoo dev we have silent dependencies in `base`, `template-haskell` etc. which Portage doesn't see, which we therefore do not revbump for, unlike RDEPENDs
- We have no Gentoo devs that can keep ::gentoo as up to date as ::haskell
- We pull in a hackage revision in ::haskell which doesn't touch RDEPENDs, and therefore does not require a revbump
- When a user moves from ::gentoo only to ::gentoo + ::haskell, Portage sees no update for the package with the exact same revision in each repo. This is a problem, as it will silently fail as it did above.

The lesson here is we need to:

- Keep ::gentoo more tightly in sync with ::haskell (virtually impossible without a Gentoo dev or someone who can dedicate more of their life to opening PRs)
- Ensure we instruct Portage to update packages to the ::haskell version where they are materially more up-to-date, i.e. where there are hackage revisions to silent packages.

**Comment by l29ah** [comment]
It just works for me. The user has ::haskell repo priority set lower than ::gentoo, so ::gentoo packages are picked up instead and fail. Do you see a better fix for this problem than bumping the repo priority?

Revbumping for changed `base` deps in our case is pointless since it will get rebuilt due to subslot dep regardless.

When a user moves from ::gentoo only to ::gentoo + ::haskell, Portage doesn't need to see any updates for already installed packages: if `integer-logarithms-1.0.3.1` was already installed, there would be no issue like the above one.

**Comment by alecStewart1** [comment]
> > I'll move `integer-logarithms` in the `::haskell` repo to `-r2` which should force your system to pull that in.
> 
> I don't think forcing an useless recursive rebuild of a bunch of packages for all users of ::haskell is a good policy for handling a misconfiguration (that will surely hit again) of one user's system.

To clarify, I just followed what's [here](https://wiki.gentoo.org/wiki/Haskell#Getting_started). Nothing about repo priority is mentioned there. If you search "gentoo haskell" it's very likely you'll get that official Gentoo wiki page before anything.

Another thing I noticed is that the [README](https://github.com/gentoo-haskell/gentoo-haskell#overlay-priority) mentions the use of layman, which I think it's recommended (or at least when I installed Gentoo almost a year ago) that one uses `app-eselect/eselect-repository`.

**Comment by alecStewart1** [comment]
Also, and maybe this is just me, why does it make sense that one would put the ::haskell repo at a higher priority? It begs the question as to why I wouldn't set GURU's repo higher, and considering that @solpeth mentioned:

> We have no Gentoo devs that can keep ::gentoo as up to date as ::haskell

Then a user risks installing potentially outdated packages, no? Or even newer/older versions of packages requiring the modification of `package.accepted_keywords` that a user might not want, or possible even new USE flags as well, no? I don't know how high of a possibility that is, though.

Really, I don't understand why there's a package for `integer-logarithms` in `::gentoo` if the idea is that `::haskell` should be where one would stop for Haskell packages, especially something so Haskell specific. But I haven't used Gentoo long so I'll defer to those with more expertise.

**Comment by solpeth** [comment]
@l29ah I take your point on repo priority being the main issue, here. I'm not sure why `::haskell` is being deprioritised by default unless someone is manually deprioritising it (in which case you would be right to leave it at 'not our problem, defaults work')

@alecStewart1 the haskell ecosystem is finicky. It's best to enable the `::haskell` repo in full and I think it should by default be prioritised over ::gentoo packages (although I'm now going to check that). `::gentoo` falls out of date and is purposely a very limited subset of packages from `::haskell`.

**Comment by alecStewart1** [comment]
@solpeth I'm guessing it's just what `eselect-repository` does. :man_shrugging: I didn't do any other configuration besides what's on the Gentoo Wiki.

**Comment by alecStewart1** [comment]
@solpeth yea, looking at the file `/etc/portage/repos.conf/eselect-repo.conf` none of the repos I've added over the past year have any priority set. I just changed all of them so I'll see if that also fixes my issue.

**Comment by solpeth** [comment]
@alecStewart1 by default ::Gentoo should be the lowest priority so I'm not sure why it didn't pull in the ::Haskell version of integer-logarithms (unless you already had it installed from ::Gentoo first).

**Comment by alecStewart1** [comment]
@solpeth It was set to 1000 in `/etc/portage/repos.conf/gentoo.conf`. I don't ever recall setting it to that.

**Comment by solpeth** [comment]
@alecStewart1 according to upstream documentation it should have been set to `-1000` by default. Either that has changed or something else is up.

In any case, @l29ah you're right about the repo priorities and user configuration being the issue and I apologise for dismissing that earlier in the way I did. I don't know why the user's ::gentoo priority is set the way it is without their recollection.

**Comment by alecStewart1** [comment]
@solpeth hm, maybe I did set it at some point. Would it but set to something higher if one is on a hardened profile? Because I am on a hardened profile.

**Comment by hololeap** [comment]
FWIW, another user hit issues regarding repo priority and added this:

https://github.com/gentoo-haskell/gentoo-haskell#overlay-priority

This issue isn't specific to any one repo, though.

**Comment by hololeap** [comment]
@solpeth I agree with @l29ah that this is a misconfigured system and a revbump isn't necessary. `::haskell` needs to have a higher priority than `::gentoo` to make any sense as an overlay, and everything seems to point to this being the default.

---



> @solpeth hm, maybe I did set it at some point. I definitely don't remember doing that. Would it but set to something higher if one is on a hardened profile? Because I am on a hardened profile.

@alecStewart1 I don't have any proof one way or the other, but this seems highly unlikely to me. The answer could be as simple as you accidentally deleted the `-` from `priority = -1000` when you were editing the file.
