### ISSUE TITLE
Metadata regeneration fails with latest pkgcraft-tools

### ISSUE THREAD

**Issue by vimproved** [gentoo-haskell/gentoo-haskell#1489]
When using the lastest version of `sys-apps/pkgcraft-tools`, `pk repo metadata haskell` fails with `Error: invalid repo: haskell: profiles/eapi: unsupported EAPI: 1`. Does this EAPI file need to be there in the first place, and if so could the value be increased?

**Comment by hololeap** [comment]
> 5.2.2 The eapi file
> A profile directory may contain an `eapi` file. This file, if it exists, must contain a single line with the name of an EAPI. This specifies the EAPI to use when handling the directory in question; a package manager must not attempt to use any profile using a directory which requires an EAPI it does not support. If no eapi file is present, EAPI 0 shall be used. The EAPI is neither inherited via the parent file nor in subdirectories.

https://dev.gentoo.org/~ulm/pms/head/pms.html#section-5.2.2

---

Does changing the value in the file to `7` fix it for you? I'm pretty sure at this point all the ebuilds are `EAPI=7` or higher.

**Comment by vimproved** [comment]
> > 5.2.2 The eapi file
> > A profile directory may contain an `eapi` file. This file, if it exists, must contain a single line with the name of an EAPI. This specifies the EAPI to use when handling the directory in question; a package manager must not attempt to use any profile using a directory which requires an EAPI it does not support. If no eapi file is present, EAPI 0 shall be used. The EAPI is neither inherited via the parent file nor in subdirectories.
> 
> https://dev.gentoo.org/~ulm/pms/head/pms.html#section-5.2.2
> 
> Does changing the value in the file to `7` fix it for you? I'm pretty sure at this point all the ebuilds are `EAPI=7` or higher.
> 
> Edit: Looks like there are some `EAPI=6` still. I'm not sure if the `eapi` file is relevant to the EAPI of the repo's ebuilds.

Yes, it does. Seems like `::gentoo` and most overlays have 5, so that's probably what I would go with.
