### ISSUE TITLE
`dev-haskell/gi-vte` fails to build

### ISSUE THREAD

**Issue by hololeap** [gentoo-haskell/gentoo-haskell#1493]
Hi,

I've encountered a similar issue in these days for this package:
```
GI/Vte/Objects/Terminal.hs:2002:1: error:
    Could not load module ‘GI.Cairo.Structs.FontOptions’
    It is a member of the hidden package ‘gi-cairo-1.0.29’.
    Perhaps you need to add ‘gi-cairo’ to the build-depends in your .cabal file.
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
     |
2002 | import qualified GI.Cairo.Structs.FontOptions as Cairo.FontOptions
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

But also if I set `GHC_BOOTSTRAP_PACKAGES="cairo"' it doesn't work.

_Originally posted by @open-antux in https://github.com/gentoo-haskell/gentoo-haskell/issues/1327#issuecomment-1782953113_

**Comment by hololeap** [comment]
@open-antux 

That seems like a different issue. If it needed `GHC_BOOTSTRAP_PACKAGES`, the failure would be during the configure phase when it tries to build `setup`. This looks like it wants `gi-cairo` in the build-depends for the library, but I don't know why it wouldn't be there already. Here's a patch if you want to try it. I can take a closer look later:

```patch
 gi-vte.cabal | 1 +
 1 file changed, 1 insertion(+)

diff --git a/gi-vte.cabal b/gi-vte.cabal
index e984b4e..73a8a25 100644
--- a/gi-vte.cabal
+++ b/gi-vte.cabal
@@ -36,6 +36,7 @@ library
                      haskell-gi-base >= 0.26 && < 0.27,
                      haskell-gi >= 0.26 && < 0.27,
                      haskell-gi-overloading < 1.1,
+                     gi-cairo == 1.0.*,
                      gi-pango == 1.0.*,
                      gi-gtk == 3.0.*,
                      gi-gio == 2.0.*,
-- 
2.41.0
```

**Comment by open-antux** [comment]
It worked but I applied this patch under `/var/tmp/portage/dev-haskell/gi-vte-2.91.29/work/gi-vte-2.91.29/gi-vte.cabal`, how can I apply this patch portage wide?

**Comment by hololeap** [comment]
You could add it as

```
/etc/portage/patches/dev-haskell/gi-vte-2.91.29/add-gi-cairo-dep.patch
```

But I'll add it to the ebuild since it's working for you.

**Comment by open-antux** [comment]
It worked! Thank you very much!
