### ISSUE TITLE
install ghc 9.6.4

### ISSUE THREAD

**Issue by max-grek** [gentoo-haskell/gentoo-haskell#1509]
Before asking, I want to say, that when I googled questions same to mine, I didn't find where to ask that question, so I decided to put that question here.

Hi guys, this question is rather stupid from some perspective, I guess, but anyway

Could you point me, please, how to install ghc 9.6.4 on gentoo? 

I see that there is new ebuild for new version but when I want to upgrade, portage doesn't see new ghc version and even older such as 9.4.8. 
And I'm wondering, is that overlay restricts pulling that version or that's I don't understand how to upgrade to newest version

sorry for english, if so - it's not my native

**Comment by l29ah** [comment]
I have this in my package.keywords:
```
# ghc 9.6
=dev-lang/ghc-9.6.2* **
=dev-lang/ghc-9.6.3* **
=dev-lang/ghc-9.6.4* **
=dev-haskell/hadrian-9.6.2* **
=dev-haskell/hadrian-9.6.3* **
=dev-haskell/hadrian-9.6.4* **
=dev-haskell/exceptions-0.10.7 **
=dev-haskell/haskeline-0.8.2.1 **
=dev-haskell/mtl-2.3.1 **
=dev-haskell/parsec-3.1.16.1 **
=dev-haskell/process-1.6.17.0 **
=dev-haskell/terminfo-0.4.1.6 **
=dev-haskell/transformers-0.6.1.0 **
=dev-haskell/haddock-api-2.27.0 **
=dev-haskell/haddock-library-1.11.0* **
=dev-haskell/cabal-3.10.1.0 **
=dev-haskell/cabal-install-3.10.1.0 **
=dev-haskell/cabal-install-solver-3.10.1.0 **
=dev-haskell/text-2.0.2 **
=dev-haskell/stm-2.5.1.0 **
app-admin/haskell-updater **
```
Generally you should read Gentoo documentation on dealing with masked packages.

**Comment by hololeap** [comment]
There's also this, which is a pretty sparse guide and was written for ghc-9.4, but it has a bit of info in it:

https://github.com/gentoo-haskell/gentoo-haskell/wiki/Building-experimental-ghc-9.4

The main point to take from that is that you'll need to bootstrap from an existing GHC that's already installed on your system. I would take it in steps:

1. Start with getting `ghc-9.2.8` and `hadrian-9.6.4` installed, only unmasking packages needed for that
2. Then work on getting `ghc-9.6.4` installed with `USE="ghcbootstrap"`
3. At that point @l29ah's `package.keywords` will be needed in order to install the latest compatible haskell packages using `ghc-9.6.4`.

**Comment by max-grek** [comment]
@hololeap Sorry, I don't understand why we need put that list of packages in package_keywords? If we've already set */*::haskell


And even if I set that list of packages, I have another packages as well such as xmonad, xmonad-contrib, haskell-language-server and so on. Should I put them there too?

I'm asking it, because I really don't understand why we have to set long list of packages and I didn't find any useful information in the internet about it

**Comment by hololeap** [comment]
@max-grek I will try to explain it, but you should probably also read some of the documentation on the subject:

- https://wiki.gentoo.org/wiki//etc/portage/package.accept_keywords
- https://devmanual.gentoo.org/keywording/index.html

---

- If you have this in `package.accept_keywords`:

  ```
  */*::haskell
  ```

  It is saying to accept package versions that are marked as _testing_ on your architecture.

  For instance, here are the `KEYWORDS` for `dev-lang/ghc-9.2.8`:

  https://github.com/gentoo-haskell/gentoo-haskell/blob/501d76bd60e935bc8bcd16ee292f9ddc863160b8/dev-lang/ghc/ghc-9.2.8.ebuild#L133

  This means that it is marked as a _testing_ version for `amd64` and `x86`. `*/*::haskell` in `package.accept_keywords` will be enough for portage to allow you to use it (assuming you're on `amd64` or `x86`.)

---

- All the packages in this overlay are marked as _testing_ at the very least (nothing in this overlay is marked as stable). However, some _very_ experimental versions go even farther by omitting `KEYWORDS` altogether.

  As you can see, the newest versions of `dev-lang/ghc` do not have any `KEYWORDS` set (the `KEYWORDS` line has been commented out in the ebuild):

  https://github.com/gentoo-haskell/gentoo-haskell/blob/501d76bd60e935bc8bcd16ee292f9ddc863160b8/dev-lang/ghc/ghc-9.6.4.ebuild#L129

  This means you need a line like this in `package.accept_keywords` for portage to accept that version:

  ```
  =dev-lang/ghc-9.6.4 **
  ```

  The `**` tells portage to accept that version, regardless of what architecture you're on.

---

- Also, some packages are directly tied to which GHC version you're using:

  https://github.com/gentoo-haskell/gentoo-haskell/blob/501d76bd60e935bc8bcd16ee292f9ddc863160b8/dev-haskell/mtl/mtl-2.3.1.ebuild#L28 

  The versions tied to the latest GHC also do not have any `KEYWORDS` set:

  https://github.com/gentoo-haskell/gentoo-haskell/blob/501d76bd60e935bc8bcd16ee292f9ddc863160b8/dev-haskell/mtl/mtl-2.3.1.ebuild#L19-L20

  This means you also need to tell portage to accept these versions:

  ```
  =dev-haskell/mtl-2.3.1 **
  ```

---

- The package versions in the list that @l29ah posted are all without `KEYWORDS` and also tied to the GHC version you are using in some way. The list is telling portage to accept those versions regardless of their `KEYWORDS` status.

**Comment by hololeap** [comment]
I also want to warn you that since many of the packages in @l29ah's list are tied to what GHC version you are using, I would not enable the whole list all at once. Like I mentioned earlier, I would recommend doing it in steps:

1. - Add `=dev-haskell/hadrian-9.6.4 **` to `package.accept_keywords`
   - Install `dev-haskell/hadrian-9.6.4` (needed to build ghc-9.6.4)
2. - Add `=dev-lang/ghc-9.6.4 **` to `package.accept_keywords`
   - Add `=dev-lang/ghc-9.6.4 ghcbootstrap` to `package.use`
   - Install `dev-lang/ghc-9.6.4`
3. At this point you can enable all of @l29ah's list since ghc-9.6.4 is installed.

**Comment by max-grek** [comment]
@hololeap man, thank you a lot, your explanation much better than gentoo's wiki has. I appreciate it

**Comment by max-grek** [comment]
@hololeap btw, one question, why that happened with ghc-9.6.4? I mean, ghc-9.2.8 has installed without that headache. Is that somehow related to that this version haven't tested properly or something? Can you explain it, please?

**Comment by max-grek** [comment]
@hololeap thank you for great explanation, I believe we can close that thread, thanks again

**Comment by max-grek** [comment]
thank you for great explanation, I believe we can close that thread, thanks again

**Comment by max-grek** [comment]
thank you for great explanation, I believe we can close that thread, thanks again
