### ISSUE TITLE
dev-lang/ghc-9.6.4 refuses to work with llvm-16

### ISSUE THREAD

**Issue by l29ah** [gentoo-haskell/gentoo-haskell#1519]
Even though it forces 16 in ::haskell-provided wrapper shell script.
ghc output observed with `-fllvm -O2` on 16 but not 15:
```
You are using an unsupported version of LLVM!
Currently only 11 up to 16 (non inclusive) is supported. System LLVM version: 16.0.6
We will try though...
Cannot use -O# with legacy PM.

<no location info>: error:
    `opt' failed in phase `LLVM Optimiser'. (Exit code: 1)
```

**Comment by hololeap** [comment]
It looks like the llvm-16 patch was not migrated to ghc-9.6:

```diff
diff --git a/./ghc-9.4.8.ebuild b/./ghc-9.6.4.ebuild
index 92a6fb3220ec..7fbdbab3922c 100644
--- a/./ghc-9.4.8.ebuild
+++ b/./ghc-9.6.4.ebuild
@@ -460,10 +460,6 @@ src_prepare() {
        #eapply "${FILESDIR}"/${PN}-9.0.2-llvm-13.patch
        #eapply "${FILESDIR}"/${PN}-9.0.2-llvm-14.patch
 
-       # https://gitlab.haskell.org/ghc/ghc/-/issues/22954
-       # https://gitlab.haskell.org/ghc/ghc/-/issues/21936
-       eapply "${FILESDIR}"/${PN}-9.4.5-llvm-16.patch
-
        # Fix issue caused by non-standard "musleabi" target in
        # https://gitlab.haskell.org/ghc/ghc/-/blob/ghc-9.4.5-release/m4/ghc_llvm_target.m4#L39
        eapply "${FILESDIR}"/${PN}-9.4.5-musl-target.patch
```

**Comment by hololeap** [comment]
@l29ah could you try https://github.com/hololeap/gentoo-haskell/commit/65a4543818b54c27f89337e85235b6cddf7b53d7?

I don't know what I'm doing, so I just adapted @vimproved's [old patch](https://github.com/gentoo-haskell/gentoo-haskell/blob/8f12e0e684804ccb898ea606592ccdd2a202995e/dev-lang/ghc/files/ghc-9.4.5-llvm-16.patch).

**Comment by l29ah** [comment]
> @l29ah could you try [hololeap@65a4543](https://github.com/hololeap/gentoo-haskell/commit/65a4543818b54c27f89337e85235b6cddf7b53d7)?

It works on a hello world at least, thanks.
