### ISSUE TITLE
`dev-haskell/hasktags` fails to build, setup: Encountered missing or private dependencies: bytestring >=0.9 && <0.11

### ISSUE THREAD

**Issue by LemonBreezes** [gentoo-haskell/gentoo-haskell#1536]
Hello. I'm new to Haskell and trying to get it set up with Gentoo and Emacs and I encountered this error while emerging `dev-haskell/hasktags`:
```text
setup: Encountered missing or private dependencies:
bytestring >=0.9 && <0.11
```

**Comment by hololeap** [comment]
I wrote a new wiki page that will hopefully explain why this happens:

https://github.com/gentoo-haskell/gentoo-haskell/wiki/Understanding-the-Hackage-ecosystem

Let me know if any of it is confusing.
