### ISSUE TITLE
Bump haskell-language-server-2.7.0.0 (ghc-9.8.2)

### ISSUE THREAD

**Issue by arbitrary-dev** [gentoo-haskell/gentoo-haskell#1538]
Hack-job attempt:
https://github.com/arbitrary-dev/gentoo-overlay/commit/402779701099f5c898f24938f1786203c80d879f

**Comment by hololeap** [comment]
Cool, I can take a look and see what needs to be tweaked before pulling it in. I ran into https://github.com/haskell/haskell-language-server/issues/4100 and so put `2.7.0.0` on hold, but I can take another look now.

**Comment by hololeap** [comment]
Also, it looks like `2.8.0.0` is out now: https://github.com/haskell/haskell-language-server/releases/tag/2.8.0.0
