### ISSUE TITLE
dev-lang/ghc-9.8.2-r1: Something is amiss

### ISSUE THREAD

**Issue by l29ah** [gentoo-haskell/gentoo-haskell#1542]
`The Glorious Glasgow Haskell Compilation System, version 9.8.2` here, can't compile it with `ghcbootstrap`:
```
ghc/Main.hs:18:1: error: [GHC-53693]
    Something is amiss; requested module  ghc-9.8.2:GHC differs from name found in the interface file ghc:GHC (if these names look the same, try again with -dppr-debug)
   |
18 | import qualified GHC
   | ^^^^^^^^^^^^^^^^^^^^
```

Full build log: https://tinystash.undef.im/il/3S7Kh8tRUqYU3m2p6CyY1eJXzjwbgjz8bey9UdeySCM13WBfSmVBdaDcVwUqkPCDEpZQc1HkAcA1LoeMYUnRgn8z.log

**Comment by l29ah** [comment]
https://gitlab.haskell.org/ghc/ghc/-/issues/24605

**Comment by l29ah** [comment]
Found a patch there, testing.

**Comment by hololeap** [comment]
Was this working before 82967505e7f59fff85f886c6202137bd4cfd9320 or c0ef31a2e98c8f9bb5248018aa5197eee5ce11b7 ?
