### ISSUE TITLE
to compile GHC 9.10 alex installed needed

### ISSUE THREAD

**Issue by Miezhiko** [gentoo-haskell/gentoo-haskell#1552]
can't compile 9.10 without alex

can limit to 9.8 and cabal syntax to prior last version then gen 9.8 ghc -> emerge alex

then 9.10 works

**Comment by hololeap** [comment]
Is https://github.com/gentoo-haskell/gentoo-haskell/commit/27185cb8c4e4cfe6b3c59114d6970268d553cdbf no longer working?

**Comment by hololeap** [comment]
You'll have to bootstrap `ghc-9.10` from an earlier version, since there isn't a good way to disable alex at this time.

**Comment by hololeap** [comment]
> This fix is not working properly and the proper solution is still not in an official cabal-install release. Building without `USE=ghcbootstrap` will not be feasible until the `--ignore-build-tools` flag for cabal makes its way into the [`hadrian-bootstrap-sources` tarball](https://downloads.haskell.org/~ghc/9.10.1/hadrian-bootstrap-sources/).
> 
> In the meantime, install ghc-9.8 and then bootstrap ghc-9.10 using the instructions found here:
> 
> https://github.com/gentoo-haskell/gentoo-haskell/wiki/Building-experimental-ghc#bootstrap-install

**Comment by hololeap** [comment]
You might have luck with [my cabal-3.10 branch](https://github.com/hololeap/hackport/commits/cabal-3.10/)
