### ISSUE TITLE
taffybar install fails due to downgrade conflict with dev-haskell/primitive

### ISSUE THREAD

**Issue by wolfwood** [gentoo-haskell/gentoo-haskell#1555]
it seems that dev-haskell/primitive < 0.8 is required by dev-haskell/byte-order-0.1.2.0 and dev-haskell/primitive-unaligned-0.1.1.1

but something like 23 packages depend on primitive >= 0.9.0.0

https://github.com/haskell-primitive/primitive-unaligned/issues/14 can address one with a version bump.

dev-haskell/byte-order 0.1.3.1 already supports primitive 0.9, it just needs an ebuild (PR at #1556 )

**Comment by wolfwood** [comment]
installed and working. thanks @hololeap !

**Comment by hololeap** [comment]
I had to update a few packages to get it installed. They're in `master` now.
