### ISSUE TITLE
`prettyprinter-ansi-terminal-1.1.3` fails to build with `Couldn't match type ‘[Char]’ with ‘Text``

### ISSUE THREAD

**Issue by Zelourses** [gentoo-haskell/gentoo-haskell#1558]
A couple of days ago I tried to build `haskell-language-server` (2.9.0) and one of the dependencies was `dev-haskell/prettyprinter-ansi-terminal-1.1.3` which fails to build

`build.log` https://gist.github.com/Zelourses/3a12cbc3a98cc889175e5cbe64693d4c

The particular error part:
```
    • Couldn't match type ‘[Char]’ with ‘Text’
      Expected: Text
        Actual: prettyprinter-1.7.1:Data.Text.Text
    • In the second argument of ‘T.hPutStr’, namely ‘t’
      In a stmt of a 'do' block: T.hPutStr h t
      In the expression:
        do T.hPutStr h t
           go rest
```

If there is a need for additional info, let me know.

**Comment by hololeap** [comment]
Are you using the profile `default/linux/amd64/23.0/llvm`? I'm assuming you are and setting up a sandbox with this profile to test with.

**Comment by Zelourses** [comment]
If I understood correctly, yes, it's this profile.

**Comment by hololeap** [comment]
I didn't word that properly. What I meant was that I am setting up a sandbox with the llvm profile to test with.

I set up the `default/linux/amd64/23.0/llvm` sandbox, and I wasn't able to reproduce this error (`prettyprinter-ansi-terminal-1.1.3` compiled with the llvm profile). That said, there were quite a few test failures for `ghc-9.4.8` on this profile.

---

```
      Expected: Text
        Actual: prettyprinter-1.7.1:Data.Text.Text
```

To me, this looks like there is a mismatch between:

1.  the `text` library that `prettyprinter` compiled with
2. the `text` library on your system

I'm not sure how this inconsistency would come about without it throwing an error during `src_configure`... but, have you tried `haskell-updater` to see if it pulls in `prettyprinter` to be rebuilt?
