### ISSUE TITLE
Question: how do you check if new version of packaged things is out?

### ISSUE THREAD

**Issue by Miezhiko** [gentoo-haskell/gentoo-haskell#1559]
I understand it's possible to subscribe on github for tags but is there script to check if ebuild version needs update based on hackage?

I wish there to be script to check for several packages I maintain/use for myself (or just for all in overlay)

**Comment by l29ah** [comment]
I guess the easiest way would be adapting `bump_hp` script to tell you the newest version before and after, or so.

**Comment by hololeap** [comment]
There actually is something for this. Try `hackport status --from-hackage`. The colors show you which packages are on hackage but not yet in the overlay.

```
Cyan: package only exist on hackage
```
