### ISSUE TITLE
Please drop app-emacs/haskell-mode

### ISSUE THREAD

**Issue by xgqt** [gentoo-haskell/gentoo-haskell#1561]
app-emacs/haskell-mode unnecessarily overwrites the ::gentoo's version.

All changes to app-emacs/haskell-mode can go straight into Gentoo - just send a PR and ping the GNU Emacs team and/or me. 
If you think otherwise, please discuss.

**Comment by hololeap** [comment]
I don't have any problem with this. I don't use emacs and don't have any idea of it's actual state, apart from occasionally making sure it builds successfully.

**Comment by xgqt** [comment]
> hololeap closed this as completed in c3f339e 1 hour ago

@hololeap Thank you!
