### ISSUE TITLE
leksah 0.12.1.3 uses ~/.leksah-0.13 as config directory

### ISSUE THREAD

**Issue by henriavelabarbe** [gentoo-haskell/gentoo-haskell#232]
Hi,
leskah is using ~/.leksah-0.13 as config directory, while the first run wizard is defaulting to ~/.leksah-0.12/packageSources

It makes the system metadata generation fail.

workaround : change to ~/.leksah-0.13/packageSources

Regards,
Henri

**Comment by trofi** [comment]
Should have been fixed upstream by: https://github.com/leksah/leksah/commit/6f5fcb5dc87d84a95d1db48e20efe84a8725f6e4

lease reopen if still broken.
