### ISSUE TITLE
ghc-mod/idris conflict re depended-on lens

### ISSUE THREAD

**Issue by 8573** [gentoo-haskell/gentoo-haskell#373]
`app-emacs/ghc-mod` and `dev-lang/idris` seem to conflict re the
versions of `dev-haskell/lens` on which they depend.

Running `emerge -DNu --backtrack=128 @world`, I get:

    Calculating dependencies... done!

    WARNING: One or more updates/rebuilds have been skipped due to a dependency conflict:

    dev-haskell/lens:0

      (dev-haskell/lens-4.6:0/4.6::gentoo-haskell, ebuild scheduled for merge) conflicts with
        <dev-haskell/lens-4.5:0/4.4.0.2= required by (dev-lang/idris-0.9.15.1:0/0.9.15.1::gentoo-haskell, installed)
        ^                 ^^^^^^^^^^^^^^
        >=dev-haskell/lens-4.1.1:0/4.4.0.2= required by (dev-lang/idris-0.9.15.1:0/0.9.15.1::gentoo-haskell, installed)
                                ^^^^^^^^^^^
        <dev-haskell/lens-4.5:= required by (dev-lang/idris-0.9.15.1:0/0.9.15.1::gentoo-haskell, installed)
        ^                 ^^^

    !!! The following update(s) have been skipped due to unsatisfied dependencies
    !!! triggered by backtracking:

    app-emacs/ghc-mod:0

    Nothing to merge; quitting.

**Comment by trofi** [comment]
Should be better now for current versions in overlay.
