### ISSUE TITLE
dev-haskell/http-4000.2.19-r1 depends on dev-haskell/old-time[profile]

### ISSUE THREAD

**Issue by bvtrach** [gentoo-haskell/gentoo-haskell#383]
After the latest changes, dev-haskell/http-4000.2.19-r1 requires dev-haskell/old-time with profile flag set unconditionally. Is it a typo or is there really such dependency? I currently use haskell-platform without this flag set, and I would like not to change it.

**Comment by orlitzky** [comment]
This should be fixed in the -r2 I just pushed, thanks for the report!
