### ISSUE TITLE
Dynamic library cannot be found with ghc 7.6.3

### ISSUE THREAD

**Issue by mircogiacobbe** [gentoo-haskell/gentoo-haskell#400]
The case pops up when installing hmatrix that fails with the following error:

Configuring hmatrix-0.16.1.5...
Flags chosen: openblas=False
Dependency array -any: using array-0.4.0.1
Dependency base ==4.*: using base-4.6.0.1
Dependency binary -any: using binary-0.7.1.0
Dependency bytestring -any: using bytestring-0.10.0.2
Dependency deepseq -any: using deepseq-1.3.0.1
Dependency random -any: using random-1.0.1.1
Dependency split -any: using split-0.2.2
Dependency storable-complex -any: using storable-complex-0.2.2
Dependency vector >=0.8: using vector-0.10.0.1
'/usr/bin/ghc' '--info'
Using Cabal-1.18.1.2 compiled by ghc-7.6
Using compiler: ghc-7.6.3
Using install prefix: /usr
Binaries installed in: /usr/bin
Libraries installed in: /usr/lib64/hmatrix-0.16.1.5/ghc-7.6.3
Private binaries installed in: /usr/libexec
Data files installed in: /usr/share/hmatrix-0.16.1.5/ghc-7.6.3
Documentation installed in: /usr/share/doc/hmatrix-0.16.1.5
Configuration files installed in: /etc
No alex found
Using ar found on system at: /usr/bin/ar
No c2hs found
No cpphs found
No ffihugs found
Using gcc version 4.8.3 found on system at: /usr/bin/gcc
Using ghc version 7.6.3 given by user at: /usr/bin/ghc
Using ghc-pkg version 7.6.3 given by user at: /usr/bin/ghc-pkg
No greencard found
No haddock found
No happy found
No hmake found
Using hpc version 0.6 found on system at: /usr/bin/hpc
Using hsc2hs version 0.67 found on system at: /usr/bin/hsc2hs
No hscolour found
No hugs found
No jhc found
Using ld found on system at: /usr/bin/ld
No lhc found
No lhc-pkg found
No nhc98 found
Using pkg-config version 0.28 found on system at: /usr/bin/pkg-config
Using ranlib found on system at: /usr/bin/ranlib
Using strip found on system at: /usr/bin/strip
Using tar found on system at: /bin/tar
No uhc found

...

[33 of 33] Compiling Numeric.LinearAlgebra.HMatrix ( src/Numeric/LinearAlgebra/HMatrix.hs, dist/build/Numeric/LinearAlgebra/HMatrix.o )

src/Data/Packed/Vector.hs:36:8:
    Could not find module \`Data.Binary'
    Perhaps you haven't installed the "dyn" libraries for package \`binary-0.7.1.0'?
    Use -v to see a list of the files searched for.
 ...

**Comment by markwright** [comment]
It might be easier to ask us on irc freenode in #gentoo-haskell

**Comment by trofi** [comment]
It's strage that you get an error only on such a late phase.
I'd expect any haskell package to fail to link against dynamic libs.

Can you post complete build.log to some gist? I'm mostly interested in ./setup arguments for that package and actual $ARCH gentoo runs on :)
Trying to reproduce in ghc-7.6 chroots.

**Comment by trofi** [comment]
OK, I've reproduced the issue.

It's a result of my recent eclass changes:
https://github.com/gentoo-haskell/gentoo-haskell/commit/656844fc601c96789788582261eaaf94e69e25f2

Unfortunately you'll have to rebuild everything, that asks for 'dyn' libs.
In this case it's a dev-haskell/binary package.

Or you can run ``haskell-updater -a``. It will rebuild all haskell stuff for you.

**Comment by mircogiacobbe** [comment]
Indeed, some of the dependencies were compiled before I added the haskell overlay. Recompiling everything solved the issue.

**Comment by trofi** [comment]
I've also fixed eclass so it won't accidentally pop up again:
    https://github.com/gentoo-haskell/gentoo-haskell/commit/0dcb1beb5329a5745be395cc352b98b63b43b090
    https://bugs.gentoo.org/show_bug.cgi?id=545174
