### ISSUE TITLE
Some packages are incompatible with pandoc-1.14

### ISSUE THREAD

**Issue by lierdakil** [gentoo-haskell/gentoo-haskell#416]
Most notably, Hakyll is not yet updated.

Please, keep pandoc-1.13.2.1 in tree for such cases.

**Comment by trofi** [comment]
Pulled new hakyll compatible with pandoc-1.14: 641bce3aa71939236a14af5b1b48ee2c70fe9a02
I understand that dependency inconsistency is a major annoyance and we slowly porting/importing stuff compatible with pandoc-1.14 into overlay.

As a workaround we have pandoc-1.13.2 in the main tree.

**Comment by lierdakil** [comment]
Pandoc 1.13.2 in the main tree has somewhat restricted dependencies, which leads to a forced downgrade and massive breakage across the board, at least in my experience. Let's just say I'm not too stoked about that.

**Comment by trofi** [comment]
Pushed old version.

**Comment by lierdakil** [comment]
Thanks!
