### ISSUE TITLE
dev-haskell/hakyll depends on time-locale-compat missing version

### ISSUE THREAD

**Issue by limansky** [gentoo-haskell/gentoo-haskell#419]
Hi all,

  I've tried to install Hakyll, but it fail with message:
```
emerge -pv hakyll

These are the packages that would be merged, in order:

Calculating dependencies... done!

The following keyword changes are necessary to proceed:
 (see "package.accept_keywords" in the portage(5) man page for more details)
# required by hakyll (argument)
=dev-haskell/hakyll-4.7.0.0 ~amd64

emerge: there are no ebuilds to satisfy "<dev-haskell/time-locale-compat-0.1.1.0:=[profile?]".
(dependency required by "dev-haskell/hakyll-4.7.0.0::haskell" [ebuild])
(dependency required by "hakyll" [argument])                                            
```

The ebuild dependency is:
```
 >=dev-haskell/time-locale-compat-0.1.0.0:=[profile?] <dev-haskell/time-locale-compat-0.1.1.0:=[profile?]
```

But there is only time-locale-compat-0.1.1.0.

**Comment by limansky** [comment]
I've found that Hakyll-4.7.1.0 was released yesterday, and it doesn't have this dependency. So the solution is just bump new Hakyll version.

**Comment by trofi** [comment]
Fixed in-overlay version to allow latest time-locale-compat.

Bumping hakyll will allow slight backporting to time-1.4 or ghc-7.10 as a lower bound (we don't allow upgrading packages used by ghc library).

**Comment by limansky** [comment]
I've installed hakyll-4.7.1.0 with ghc-7.10.1. It was not easy because there no dependencies for maximal ghc version supported in the ebuilds.

**Comment by limansky** [comment]
Hakyll-4.7.2.2 added in pull request #429 is building successfully both with ghc 4.8 and 4.10. Closing this one.
