### ISSUE TITLE
taffybar depends on masked dev-haskell/gtk

### ISSUE THREAD

**Issue by qrilka** [gentoo-haskell/gentoo-haskell#428]
And taffybar is not yet ported to gtk3 in upstream repo - https://github.com/travitch/taffybar/issues/121

**Comment by trofi** [comment]
It's a problem of weird interaction of ':=' slot operator picking latest installed slot.
You'll need to unmerge dev-haskell/gtk:3 in favour of dev-haskell/gtk3 and rebuild
all packages that picked that SLOT=3. portage is not very smart about rebuilding them itself.

I've revbumped a package to mention SLOT=2 explicitly, but there is likely more packages like that.
