### ISSUE TITLE
bump app-emacs/ghc-mod to v5.3.0.0

### ISSUE THREAD

**Issue by TheJJ** [gentoo-haskell/gentoo-haskell#434]
https://github.com/kazu-yamamoto/ghc-mod/commit/acbb7211ac3c191a7da66348e9196829051960af

* Re-license majority of code under the AGPL-3
* Add support for GHC 7.10 and Cabal 1.22
* Remove `cabalDependPackages', `cabalAllTargets'
* Fix finding sandbox config file and directory.
* Re-add output line separator global option for expand command.
* Support for overriding the package-db stack
* Fix ineffective cache invalidation for `find`

**Comment by trofi** [comment]
8ba306dc4cab3a8aaec2f22952ee0286e4b96025 Added 5.4.0.0 version t the overlay.

Thanks for the report!
