### ISSUE TITLE
PORTDIR_OVERLAY

### ISSUE THREAD

**Issue by y-usuzumi** [gentoo-haskell/gentoo-haskell#435]
PORTDIR_OVERLAY is deprecated in favor of /etc/portage/repos.conf/

Please update.

**Comment by trofi** [comment]
It should be easy to update if dropping PORTDIR_OVERLAY is compatible with most tools.
Last time i checked it was not.

Does layman support it?
Does eix support it?

**Comment by mimi1vx** [comment]
layman , yes from 2.3.0  -> https://wiki.gentoo.org/wiki/Layman#Using_.27repos.conf.27_method_.28default_method_for_app-portage.2Flayman-2.3.0_or_later_.29

eix, from 0.30.4 -> https://github.com/vaeth/eix/blob/master/ChangeLog#L82

**Comment by trofi** [comment]
Ugh. Took me less than 2 years. Thanks for the report!
