### ISSUE TITLE
Update datetime ebuild

### ISSUE THREAD

**Issue by Altai-man** [gentoo-haskell/gentoo-haskell#437]
With ghc 7.10.1 build of datetime package fails. Here is log of build: [click here](http://pastebin.com/hMuH4d3X).
On github exists patched/updated version of datetime and it compiles with new ghc - [link](https://github.com/stackbuilders/datetime). Also page of datetime package on hackage refers to new version of package(from slackbuilders). It would be nice to update ebuilds for datetime package with new version that supports new ghc.

**Comment by trofi** [comment]
Bumped to latest version from hackage:

https://github.com/gentoo-haskell/gentoo-haskell/commit/c07b33ab61da81217fbd8cecb8ef94ea007ec7ce

Thank you!

**Comment by Altai-man** [comment]
Thank you for quick fix.
