### ISSUE TITLE
Failed to emerge dev-haskell/hmatrix-0.16.1.5

### ISSUE THREAD

**Issue by ivan-timokhin** [gentoo-haskell/gentoo-haskell#446]
Build log here: https://gist.github.com/ivan-timokhin/f9b1f3ae045552db5fa9

Sadly, `cabal install hmatrix --flags="openblas"` also fails, even though OpenBLAS is installed from `science` overlay; I didn't check with reference blas and lapack though.

**Comment by trofi** [comment]
```
setup: Missing dependencies on foreign libraries:
* Missing C libraries: blas, lapack
This problem can usually be solved by installing the system packages that
provide these libraries (you may need the "-dev" versions). If the libraries
are already installed but in a non-standard location then you can use the
flags --extra-include-dirs= and --extra-lib-dirs= to specify where they are.
```
Does openblas provide 'eselect' wrapper to make libblas.so and liblapack.so symlinks visible?

**Comment by ivan-timokhin** [comment]
It does provide a eselect alternative, but unfortunately only adds pkg-config metadata:
```
$ eselect blas files
/usr/lib64/pkgconfig/blas.pc
```
It's probably also worth noting that science overlay has own eselect version as well; IIRC, openblas doesn't quite work with the one from the main tree.

**Comment by ivan-timokhin** [comment]
So... I guess that means I should file a bug for openblas ebuild instead?

**Comment by ivan-timokhin** [comment]
Or maybe no. https://wiki.gentoo.org/wiki/User_talk:Houseofsuns seems to imply that that's by design:
> You should also check for potential links named libclas.so and liblapack.so. With the science stack you shouldn't have any files or links named libblas.so, llibclas.so or liblapack.so under /usr/lib or /usr/lib64. Similarly you shouldn't have any static library counterpart (.a file).

**Comment by trofi** [comment]
hmatrix.cabal file has rudimentary support for openblas:
```
        if flag(openblas)
            extra-lib-dirs:     /usr/lib/openblas/lib
            extra-libraries:    openblas
```
which can be enabled by cabal's:
    cabal install hmatrix --flag=openblas
or 
    CABAL_EXTRA_CONFIGURE_FLAGS=--flag=openblas emerge -1 hmatrix

Didn't try if it really work.

If openblas way is to use pkg-config then hmathix.cabal file should contain
```
        if flag(openblas)
            pkg-config: openblas -- or the actual lib name it installs
```

**Comment by trofi** [comment]
Apparently I can't read. You've already replied to all my questions even before I asked. My apologies.

Does this change makes things better for you?
https://github.com/gentoo-haskell/gentoo-haskell/commit/0a84bf416da31c102348ee465ca59030c6ba6d4a

**Comment by ivan-timokhin** [comment]
Thanks! All works now.

**Comment by trofi** [comment]
Thanks for the report!
