### ISSUE TITLE
Compilation failure for bos/text

### ISSUE THREAD

**Issue by Gooberpatrol66** [gentoo-haskell/gentoo-haskell#458]
Dunno where the best place to report this is. See my issue here https://github.com/bos/text/issues/140

Reproduced:
[25 of 43] Compiling Data.Text ( Data/Text.hs, dist/build/Data/Text.o )

Data/Text.hs:335:10:
No instance for (GHC.Generics.Generic Text)
arising from a use of ‘Control.DeepSeq.$gdmrnf’
In the expression: Control.DeepSeq.$gdmrnf
In an equation for ‘rnf’: rnf = Control.DeepSeq.$gdmrnf
In the instance declaration for ‘NFData Text’

ERROR: dev-haskell/text-1.1.1.3::gentoo failed (compile phase):
setup build failed
Call stack:
ebuild.sh, line 93: Called src_compile
environment, line 2830: Called haskell-cabal_src_compile
environment, line 1944: Called cabal_src_compile
environment, line 755: Called cabal-build
environment, line 504: Called die
The specific snippet of code:
./setup "$@" || die "setup build failed"
If you need support, post the output of emerge --info '=dev-haskell/text-1.1.1.3::gentoo',
the complete build log and the output of emerge -pqv '=dev-haskell/text-1.1.1.3::gentoo'.
The complete build log is located at '/var/tmp/portage/dev-haskell/text-1.1.1.3/temp/build.log'.
The ebuild environment file is located at '/var/tmp/portage/dev-haskell/text-1.1.1.3/temp/environment'.
Working directory: '/var/tmp/portage/dev-haskell/text-1.1.1.3/work/text-1.1.1.3'
S: '/var/tmp/portage/dev-haskell/text-1.1.1.3/work/text-1.1.1.3'

**Comment by trofi** [comment]
Please post a full build log. It will contain USE flags and actual GHC version.

**Comment by Gooberpatrol66** [comment]
[32;01m * [39;49;00mPackage:    dev-haskell/text-1.1.1.3
[32;01m * [39;49;00mRepository: gentoo
[32;01m * [39;49;00mMaintainer: haskell@gentoo.org
[32;01m * [39;49;00mUSE:        abi_x86_64 amd64 elibc_glibc kernel_linux userland_GNU
[32;01m * [39;49;00mFEATURES:   preserve-libs sandbox userpriv usersandbox
>>> Unpacking source...
>>> Unpacking text-1.1.1.3.tar.gz to /var/tmp/portage/dev-haskell/text-1.1.1.3/work
>>> Source unpacked in /var/tmp/portage/dev-haskell/text-1.1.1.3/work
>>> Preparing source in /var/tmp/portage/dev-haskell/text-1.1.1.3/work/text-1.1.1.3 ...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/dev-haskell/text-1.1.1.3/work/text-1.1.1.3 ...
 [32;01m*[0m Using cabal-1.22.5.0.
 [32;01m*[0m Prepending /usr/lib64/ghc-7.10.2 to LD_LIBRARY_PATH
/usr/bin/ghc -package Cabal-1.22.5.0 --make /var/tmp/portage/dev-haskell/text-1.1.1.3/work/text-1.1.1.3/Setup.lhs -threaded -dynamic -o setup
[1 of 1] Compiling Main             ( /var/tmp/portage/dev-haskell/text-1.1.1.3/work/text-1.1.1.3/Setup.lhs, /var/tmp/portage/dev-haskell/text-1.1.1.3/work/text-1.1.1.3/Setup.o )
Linking setup ...
./setup configure --ghc --prefix=/usr --with-compiler=/usr/bin/ghc --with-hc-pkg=/usr/bin/ghc-pkg --prefix=/usr --libdir=/usr/lib64 --libsubdir=text-1.1.1.3/ghc-7.10.2 --datadir=/usr/share/ --datasubdir=text-1.1.1.3/ghc-7.10.2 --disable-tests --ghc-option=-j4 --ghc-option=-optc-march=native --ghc-option=-optc-Os --ghc-option=-optc-pipe --ghc-option=-optl-Wl,-O1 --ghc-option=-optl-Wl,--as-needed --disable-executable-stripping --docdir=/usr/share/doc/text-1.1.1.3 --verbose --enable-shared --enable-executable-dynamic --sysconfdir=/etc --disable-library-stripping --flag=-developer
Configuring text-1.1.1.3...
Flags chosen: integer-simple=False, developer=False
Dependency array >=0.3: using array-0.5.1.0
Dependency base >=4.2 && <5: using base-4.8.1.0
Dependency bytestring >=0.10.4.0: using bytestring-0.10.6.0
Dependency deepseq >=1.1.0.0: using deepseq-1.4.1.1
Dependency ghc-prim >=0.2: using ghc-prim-0.4.0.0
Dependency integer-gmp >=0.2: using integer-gmp-1.0.0.0
Using Cabal-1.22.5.0 compiled by ghc-7.10
Using compiler: ghc-7.10.2
Using install prefix: /usr
Binaries installed in: /usr/bin
Libraries installed in: /usr/lib64/text-1.1.1.3/ghc-7.10.2
Private binaries installed in: /usr/libexec
Data files installed in: /usr/share/text-1.1.1.3/ghc-7.10.2
Documentation installed in: /usr/share/doc/text-1.1.1.3
Configuration files installed in: /etc
No alex found
Using ar found on system at: /usr/bin/ar
No c2hs found
No cpphs found
Using gcc version 4.9.3 found on system at: /usr/bin/gcc
Using ghc version 7.10.2 given by user at: /usr/bin/ghc
Using ghc-pkg version 7.10.2 given by user at: /usr/bin/ghc-pkg
No ghcjs found
No ghcjs-pkg found
No greencard found
No haddock found
No happy found
Using haskell-suite found on system at: haskell-suite-dummy-location
Using haskell-suite-pkg found on system at: haskell-suite-pkg-dummy-location
No hmake found
Using hpc version 0.67 found on system at: /usr/bin/hpc
Using hsc2hs version 0.67 found on system at: /usr/bin/hsc2hs
No hscolour found
No jhc found
Using ld found on system at: /usr/bin/ld
No lhc found
No lhc-pkg found
Using pkg-config version 0.28 found on system at: /usr/bin/pkg-config
Using strip version 2.25 found on system at: /usr/bin/strip
Using tar found on system at: /bin/tar
No uhc found
>>> Source configured.
>>> Compiling source in /var/tmp/portage/dev-haskell/text-1.1.1.3/work/text-1.1.1.3 ...
./setup build
Building text-1.1.1.3...
Preprocessing library text-1.1.1.3...
[ 1 of 43] Compiling Data.Text.Internal.Read ( Data/Text/Internal/Read.hs, dist/build/Data/Text/Internal/Read.o )

Data/Text/Internal/Read.hs:21:1: Warning:
    The import of ‘Control.Applicative’ is redundant
      except perhaps to import instances from ‘Control.Applicative’
    To import instances alone, use: import Control.Applicative()
[ 2 of 43] Compiling Data.Text.Internal.Encoding.Utf32 ( Data/Text/Internal/Encoding/Utf32.hs, dist/build/Data/Text/Internal/Encoding/Utf32.o )
[ 3 of 43] Compiling Data.Text.Internal.Fusion.Size ( Data/Text/Internal/Fusion/Size.hs, dist/build/Data/Text/Internal/Fusion/Size.o )
[ 4 of 43] Compiling Data.Text.Internal.Builder.RealFloat.Functions ( Data/Text/Internal/Builder/RealFloat/Functions.hs, dist/build/Data/Text/Internal/Builder/RealFloat/Functions.o )
[ 5 of 43] Compiling Data.Text.Internal.Builder.Int.Digits ( Data/Text/Internal/Builder/Int/Digits.hs, dist/build/Data/Text/Internal/Builder/Int/Digits.o )
[ 6 of 43] Compiling Data.Text.Internal.Fusion.Types ( Data/Text/Internal/Fusion/Types.hs, dist/build/Data/Text/Internal/Fusion/Types.o )
[ 7 of 43] Compiling Data.Text.Internal.Fusion.CaseMapping ( Data/Text/Internal/Fusion/CaseMapping.hs, dist/build/Data/Text/Internal/Fusion/CaseMapping.o )
[ 8 of 43] Compiling Data.Text.Encoding.Error ( Data/Text/Encoding/Error.hs, dist/build/Data/Text/Encoding/Error.o )

Data/Text/Encoding/Error.hs:3:14: Warning:
    ‘Data.Text.Encoding.Error’ is marked as Trustworthy but has been inferred as safe!
[ 9 of 43] Compiling Data.Text.Internal.Unsafe.Shift ( Data/Text/Internal/Unsafe/Shift.hs, dist/build/Data/Text/Internal/Unsafe/Shift.o )
[10 of 43] Compiling Data.Text.Internal.Encoding.Utf16 ( Data/Text/Internal/Encoding/Utf16.hs, dist/build/Data/Text/Internal/Encoding/Utf16.o )
[11 of 43] Compiling Data.Text.Internal.Functions ( Data/Text/Internal/Functions.hs, dist/build/Data/Text/Internal/Functions.o )
[12 of 43] Compiling Data.Text.Internal.Unsafe ( Data/Text/Internal/Unsafe.hs, dist/build/Data/Text/Internal/Unsafe.o )
[13 of 43] Compiling Data.Text.Internal.Fusion.Common ( Data/Text/Internal/Fusion/Common.hs, dist/build/Data/Text/Internal/Fusion/Common.o )
[14 of 43] Compiling Data.Text.Array  ( Data/Text/Array.hs, dist/build/Data/Text/Array.o )
[15 of 43] Compiling Data.Text.Internal.Unsafe.Char ( Data/Text/Internal/Unsafe/Char.hs, dist/build/Data/Text/Internal/Unsafe/Char.o )
[16 of 43] Compiling Data.Text.Internal ( Data/Text/Internal.hs, dist/build/Data/Text/Internal.o )
[17 of 43] Compiling Data.Text.Unsafe ( Data/Text/Unsafe.hs, dist/build/Data/Text/Unsafe.o )
[18 of 43] Compiling Data.Text.Internal.Private ( Data/Text/Internal/Private.hs, dist/build/Data/Text/Internal/Private.o )
[19 of 43] Compiling Data.Text.Internal.Fusion ( Data/Text/Internal/Fusion.hs, dist/build/Data/Text/Internal/Fusion.o )
[20 of 43] Compiling Data.Text.Internal.Encoding.Fusion.Common ( Data/Text/Internal/Encoding/Fusion/Common.hs, dist/build/Data/Text/Internal/Encoding/Fusion/Common.o )
[21 of 43] Compiling Data.Text.Internal.Encoding.Utf8 ( Data/Text/Internal/Encoding/Utf8.hs, dist/build/Data/Text/Internal/Encoding/Utf8.o )
[22 of 43] Compiling Data.Text.Internal.Encoding.Fusion ( Data/Text/Internal/Encoding/Fusion.hs, dist/build/Data/Text/Internal/Encoding/Fusion.o )
[23 of 43] Compiling Data.Text.Internal.Lazy.Encoding.Fusion ( Data/Text/Internal/Lazy/Encoding/Fusion.hs, dist/build/Data/Text/Internal/Lazy/Encoding/Fusion.o )
[24 of 43] Compiling Data.Text.Internal.Search ( Data/Text/Internal/Search.hs, dist/build/Data/Text/Internal/Search.o )
[25 of 43] Compiling Data.Text        ( Data/Text.hs, dist/build/Data/Text.o )

Data/Text.hs:335:10:
    No instance for (GHC.Generics.Generic Text)
      arising from a use of ‘Control.DeepSeq.$gdmrnf’
    In the expression: Control.DeepSeq.$gdmrnf
    In an equation for ‘rnf’: rnf = Control.DeepSeq.$gdmrnf
    In the instance declaration for ‘NFData Text’
 [31;01m*[0m ERROR: dev-haskell/text-1.1.1.3::gentoo failed (compile phase):
 [31;01m*[0m   setup build failed
 [31;01m*[0m 
 [31;01m*[0m Call stack:
 [31;01m*[0m     ebuild.sh, line   93:  Called src_compile
 [31;01m*[0m   environment, line 2830:  Called haskell-cabal_src_compile
 [31;01m*[0m   environment, line 1944:  Called cabal_src_compile
 [31;01m*[0m   environment, line  755:  Called cabal-build
 [31;01m*[0m   environment, line  504:  Called die
 [31;01m*[0m The specific snippet of code:
 [31;01m*[0m       ./setup "$@" || die "setup build failed"
 [31;01m*[0m 
 [31;01m*[0m If you need support, post the output of `emerge --info '=dev-haskell/text-1.1.1.3::gentoo'`,
 [31;01m*[0m the complete build log and the output of `emerge -pqv '=dev-haskell/text-1.1.1.3::gentoo'`.
 [31;01m*[0m The complete build log is located at '/var/tmp/portage/dev-haskell/text-1.1.1.3/temp/build.log'.
 [31;01m*[0m The ebuild environment file is located at '/var/tmp/portage/dev-haskell/text-1.1.1.3/temp/environment'.
 [31;01m*[0m Working directory: '/var/tmp/portage/dev-haskell/text-1.1.1.3/work/text-1.1.1.3'
 [31;01m*[0m S: '/var/tmp/portage/dev-haskell/text-1.1.1.3/work/text-1.1.1.3'

**Comment by trofi** [comment]
Pushed as:
    https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=abcc397e67a3f26bf05b88d4ac6e735748367b4c

Upstream fixed it a while ago as:
    https://github.com/bos/text/issues/100

Which leads to the question why you are using a mix of stable/unstable haskell packages?
It's not strictly bad, just wondering if it's your conscious decision.

We usually suggest keywording as ~arch the whole overlay with a single config line:
    https://github.com/gentoo-haskell/gentoo-haskell/#quickest-start

**Comment by Gooberpatrol66** [comment]
>Which leads to the question why you are using a mix of stable/unstable haskell packages?

I'm not really sure. I run a stable system except for using plasma, and I just change any keywords portage asks me to change.

**Comment by hvr** [comment]
Just for the record, on Hackage an upper bound on `deepseq` was edited in early on a year ago...

http://hackage.haskell.org/package/text-1.1.1.3/revisions/

**Comment by trofi** [comment]
Yeah, we'll need to build a tool support for detection of such inplace edits of hackage packages.
And update gentoo packages if they were based on previous incarnation of .cabal files.
