### ISSUE TITLE
Could an ebuild for pandoc-1.16.0.2 be added?

### ISSUE THREAD

**Issue by JelteF** [gentoo-haskell/gentoo-haskell#474]
A new version of pandoc has been released: http://pandoc.org/releases.html

**Comment by trofi** [comment]
I'll try to do it this weekend. Or you can do it before me :)
The main problem is usually try to port most pandoc users to new major versions.

**Comment by trofi** [comment]
Took me a while to get to it. My apologies. Pushed as:

$ git log --oneline 2ece125..5f6d9aa | cat
5f6d9aa dev-haskell/citeproc-hs: tweak for pandoc-1.16
06019cf dev-haskell/graphalyze: tweak for pandoc-1.16
da1e06f dev-haskell/yesod-markdown: bump up to 0.11.0
f03665e www-apps/gitit: tweak for pandoc-1.16
2e16d52 dev-haskell/pandoc-citeproc: bump up to 0.9
50d5631 app-text/pandoc: bump up to 1.16.0.2
ea71909 dev-haskell/pandoc-types: disable optimisations to avoid RAM blowup
09901f0 dev-haskell/cmark: bump up to 0.5.1
08aff9e dev-haskell/pandoc-types: bump up to 1.16.1

Thanks for the report!
