### ISSUE TITLE
ihaskell fails to determine the correct ghc version

### ISSUE THREAD

**Issue by madjestic** [gentoo-haskell/gentoo-haskell#486]
https://github.com/gibiansky/IHaskell/issues/645

ihaskell ebuild `/var/lib/layman/haskell/dev-haskell/ihaskell/` looks ok, but I don't see `ihaskell install` enywhere and, hence, don't understand how is the following achieved:

> The version of ghc being used is determined during ihaskell install

Is ebuild working as expected?  Or is the issue elsewhere?

Cheers,
Vlad

**Comment by trofi** [comment]
If you don't setup any symlinks, what do you run exactly to get an error?
AFAIU the bug suggests that troblem arises when you build different
components with different ghc versions.

haskell-updater run should fix this kind of problems.
