### ISSUE TITLE
doc use flag can cause package with no modules to fail during install

### ISSUE THREAD

**Issue by tim-m89** [gentoo-haskell/gentoo-haskell#492]
I had a go at getting ghc-8.0.1 installed (which worked fine), but trying to also install stack with this version was not so painless. There's quite a few things that need unmasking / accept keywords etc as you probably already know, but 1 thing I'd like to point out in particular is that I have in my package.use:
```
dev-haskell/* doc hscolour
```
Which is fine for the most part, except when I tried re-installing (somewhat ironically) *dev-haskell/fail*

This is a compatibility package for ghc<8, as such it exports 0 modules for ghc>=8. It failed to install because Haddock had no input files, and the quick workaround to get it to install was simply to also put this in my package.use:
```
dev-haskell/fail -doc
```
It would be nice if this use flag was a little more idiot proof, but perhaps low priority if it's not so straight forward to achieve.

**Comment by trofi** [comment]
Commit https://github.com/gentoo-haskell/gentoo-haskell/commit/4a4d1672c49ce474a2aedf461ec2de12e94330f9 was meant to fix it.

Do you still experience doc problems?

**Comment by tim-m89** [comment]
I most probably didn't have that particular commit when I experienced the issue, I think I synced up just a few hours before that.

**Comment by trofi** [comment]
Assume fixed.
