### ISSUE TITLE
Update dev-haskell/stack to 1.1.2

### ISSUE THREAD

**Issue by ivan-timokhin** [gentoo-haskell/gentoo-haskell#496]
Apart form being a bit outdated, `stack-1.0.2` restricts `persistent-template` to <2.2, which, now that 2.1.6 is gone, picks 2.1.3.4, which in turn requires `aeson-0.9.0.1`, which is incompatible with `liquidhaskell`.

**Comment by trofi** [comment]
Pushed 1.1.2. Thank you!

I'll need to implement proper blacklisting in hackport to notice bumps of stack.
We have phony 9.9.9 ebuild in tree and that hides `hackport status --from-hackage` output for stack.

**Comment by ivan-timokhin** [comment]
Thanks!
