### ISSUE TITLE
dev-lang/elm-reactor fails to build

### ISSUE THREAD

**Issue by kwohlfahrt** [gentoo-haskell/gentoo-haskell#507]
Building `dev-lang/elm-reactor` fails, with the following error message. Extracting the archive and running `python2 cabal-build.py` as a normal user works (and doesn't download any new dependencies). This is with paludis as my package manager, but I don't think this should affect the build phase.

```
[1 of 8] Compiling StaticFiles.Build ( src/backend/StaticFiles/Build.hs, dist/build/elm-reactor/elm-reactor-tmp/StaticFiles/Build.dyn_o )
[2 of 8] Compiling Socket           ( src/backend/Socket.hs, dist/build/elm-reactor/elm-reactor-tmp/Socket.dyn_o )

src/backend/Socket.hs:15:11: Warning:
    Defined but not used: `watchedFile'
[3 of 8] Compiling Generate.Help    ( src/backend/Generate/Help.hs, dist/build/elm-reactor/elm-reactor-tmp/Generate/Help.dyn_o )
[4 of 8] Compiling StaticFiles      ( src/backend/StaticFiles.hs, dist/build/elm-reactor/elm-reactor-tmp/StaticFiles.dyn_o )

Error:
  * In program cave perform install --hooks --managed-output --output-exclusivity with-others =dev-lang/elm-reactor-0.17.1:0::haskell --destination installed --x-of-y 1 of 2:
  * When installing 'dev-lang/elm-reactor-0.17.1:0::haskell':
  * When running an ebuild command on 'dev-lang/elm-reactor-0.17.1:0::haskell':
  * Install failed for 'dev-lang/elm-reactor-0.17.1:0::haskell' (paludis::ActionFailedError)


src/backend/StaticFiles.hs:50:5:
    Exception when trying to run compile-time code:
      fd:30: hGetContents: invalid argument (invalid byte sequence)
    Code: (=<<)
            bsToExp runIO (Build.compile ("src" </> "pages" </> "Errors.elm"))
    In the splice:
      $(bsToExp
        =<< runIO (Build.compile ("src" </> "pages" </> "Errors.elm")))

!!! ERROR in dev-lang/elm-reactor-0.17.1::haskell:
!!! In cabal-build at line 976
!!! setup build failed

!!! Call stack:
!!!    * cabal-build (/var/tmp/paludis/dev-lang-elm-reactor-0.17.1/temp/loadsaveenv:976)
!!!    * cabal_src_compile (/var/tmp/paludis/dev-lang-elm-reactor-0.17.1/temp/loadsaveenv:1211)
!!!    * haskell-cabal_src_compile (/var/tmp/paludis/dev-lang-elm-reactor-0.17.1/temp/loadsaveenv:3273)
!!!    * src_compile (/var/tmp/paludis/dev-lang-elm-reactor-0.17.1/temp/loadsaveenv:4455)
!!!    * ebuild_f_compile (/usr/libexec/paludis/2/src_compile.bash:56)
!!!    * ebuild_main (/usr/libexec/paludis/ebuild.bash:675)
!!!    * main (/usr/libexec/paludis/ebuild.bash:698)
```

**Comment by trofi** [comment]
```
src/backend/StaticFiles.hs:50:5:
    Exception when trying to run compile-time code:
      fd:30: hGetContents: invalid argument (invalid byte sequence)
```
Do you know which local paludis uses to run ebuilds under? Is it LANG=C by chance?

**Comment by kwohlfahrt** [comment]
Ah, got it! I'd tried setting `LANG`, but paludis (or the eclass or something, going to try and track it down) sets `LC_ALL=C` as well.

**Comment by kwohlfahrt** [comment]
Right, it is set by paludis (to make sure error messages are in a sane locale, which kind of makes sense). All the package manager specification requires is that the locale is POSIX compatible for ASCII characters.

I guess this should go upstream? If compilation requires UTF-8, it should just use UTF-8 and not something locale-dependent...

**Comment by trofi** [comment]
Yes, i'm not sure which upstream though. I've found a source of non-ASCII
in elm-package and pushed workaround as https://github.com/gentoo-haskell/gentoo-haskell/commit/dba334709f2c02766e59689841e3c39e2c0ce208

I've rebuild elm-make after upgrading elm-package to make sure inliner won't keep old value
in the caller.

Your fix also looks very nice. It should work as long as elm-make explicitly enables utf8
output. And it does: https://github.com/elm-lang/elm-package/blob/master/src/Main.hs#L14

Thanks for fixing that upstream!

**Comment by trofi** [comment]
I hope that works now.
