### ISSUE TITLE
timezone-olson depends on <dev-haskell/binary-0.9

### ISSUE THREAD

**Issue by waivio** [gentoo-haskell/gentoo-haskell#509]
Hi,
I noticed that timezone-olson-0.7.1 depends on less than dev-haskell/binary-0.9 according to hackage and the timezone-olson cabal file.  The hackage dependencies state binary >=0.4.1 && <0.9.  I noticed this during the GHC 8.0.1 upgrade process.  I had trouble navigating to the ebuild in github.

**Comment by trofi** [comment]
Tweaked upped depends. Don't know why I've missed this package.

Thank you!
