### ISSUE TITLE
Version bump: dev-haskell/stack-1.2.0

### ISSUE THREAD

**Issue by rdnetto** [gentoo-haskell/gentoo-haskell#510]
Stack 1.2 was released [last month](https://github.com/commercialhaskell/stack/releases) and adds support for Ncurses 6 - without it, the pre-built GHC binaries fail due to a linker error (see commercialhaskell/stack#2302).

I'm submitting an issue for this instead of a PR because it's a fairly substantial change that pulls in transitive updates for half the packages in this overlay (assuming I'm using hackport correctly) so I thought it might be better addressed by one of the maintainers.

**Comment by trofi** [comment]
Apologies, took me a while to get to it. Pulled latest stack 1.3.2 as: https://github.com/gentoo-haskell/gentoo-haskell/commit/3e32062b7e8aa1e942b18053687f6c2fe5e7aeb4

Thank for the report!
