### ISSUE TITLE
emerging stack fails due to connection-0.2.4

### ISSUE THREAD

**Issue by mrkgnao** [gentoo-haskell/gentoo-haskell#513]
Here are the logs:
- [emerge -pqv](https://paste.pound-python.org/show/C9e6dH0rmwcIPSLzdSSO/)
- [emerge --info](https://paste.pound-python.org/show/FmZwdNMEhhbxiBqylVz8/)
- [build.log](https://paste.pound-python.org/show/Chw2drYEk0H1x5JqicJG/)
- [output](https://paste.pound-python.org/show/0ThCUL9trxR60ZuMMoSv/) from the actual build (`emerge -av stack --backtrack=30`)  showing the particular code that fails

**Comment by trofi** [comment]
We usually suggest using ~arch keywording for whole ::haskell overlay.
There is unstable `connection-0.2.6` available that should be compatible with latest tls.

**Comment by mrkgnao** [comment]
Ah, how would I do that?

**Comment by trofi** [comment]
Simplest way is to have something like that in `package.accept_keywords`:
```
*/*::haskell
```

https://github.com/gentoo-haskell/gentoo-haskell/#quickest-start

**Comment by mrkgnao** [comment]
Thank you, stack installed without a hitch! :)

On Sun, Oct 30, 2016 at 2:57 PM Sergei Trofimovich <notifications@github.com>
wrote:

Simplest way is to have something like that in package.accept_keywords:

*/*::haskell

https://github.com/gentoo-haskell/gentoo-haskell/#quickest-start

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/gentoo-haskell/gentoo-haskell/issues/513#issuecomment-257140790>,
or mute the thread
