### ISSUE TITLE
Cannot update the system because of dev-haskell/highlighting-kate

### ISSUE THREAD

**Issue by Sireeni** [gentoo-haskell/gentoo-haskell#531]
I get this message when I run ` emerge --jobs=3 --keep-going -uavDN @world` : 
```
emerge: there are no ebuilds to satisfy "<dev-haskell/highlighting-kate-0.7:0/0.6.2.1=".
(dependency required by "app-text/pandoc-1.17.1-r1::haskell" [installed])
```

**Comment by trofi** [comment]
It's usually a cryptic way for emerge to say that either there is a conflict in another palce
or emerge just needs more time to resolve an upgrade path.

Try to give emerge a `--backtrack=1000` option first before exploring mask patterns.
It that will fail you can try to follow https://gentoohaskell.wordpress.com/2016/05/08/how-to-deal-with-portage-blockers/ and see if it will help you.

It it won't help we'll try more heavyweight mechanisms.

**Comment by Sireeni** [comment]
thanks @trofi! I'm trying the blog post =)
I'll let you know if it succeeds or fails. =)

**Comment by Sireeni** [comment]
Well, it's not working.More interesting : it seems that portage ignores my `package.mask` directives and tries to update some masked packages

**Comment by trofi** [comment]
Unless you have omited `--autounmask=n` it should not happen. Please post you full commandline and emerge output.

**Comment by mpkh** [comment]
fixed for me

**Comment by Sireeni** [comment]
@trofi I ran `eix-sync` today and everything went smooth :)

**Comment by trofi** [comment]
Cool!

**Comment by Sireeni** [comment]
yeah except that `emerge` has been running since yesterday to update my 400 packages :P
