### ISSUE TITLE
cabal helper wont compile

### ISSUE THREAD

**Issue by Treborius** [gentoo-haskell/gentoo-haskell#562]
hi, cabal-helper fails in configure stage at my system due a version conflict

a diff for a fix would be : 
```
diff test/cabal-helper-0.7.2.0.ebuild /var/lib/layman/haskell/dev-haskell/cabal-helper/cabal-helper-0.7.2.0.ebuild
27c27
<       dev-haskell/utf8-string:=[profile?]
---
>       =dev-haskell/utf8-string-1.0*:=[profile?]

```
sry, for not providing a pull-request
i am in a hurry :(

**Comment by trofi** [comment]
Please post full build log how it fails for you. I have `utf8-string-1.0.1.1` installed and `cabal-helper-0.7.2.0` builds fine for me.

**Comment by Treborius** [comment]
sry, i already build everything up to ghc-mod, wich cabal-helper is a dependency of
error message was something like :

> configure error 
> cabal-helper requires utf8-string>=1.0.11 && < 1.1

thus i edited the ebuild, started emerge of gch-mod and utf8-string-1.0.1.1 was pulled as dep,
build ran fine, from there
cant reproduce without a lot of work

**Comment by trofi** [comment]
Ah, I see. I guess you had utf8-string-0.3.8 installed before. Looks like our `cabal-helper` package was not generated by hackport and thus contained stale depends. I've regenerated it as:
    https://github.com/gentoo-haskell/gentoo-haskell/commit/4458ab0c8ac3f0da8f1d3d77fd9e52f865b93446

Now it has advertised lower bound.

Thank you!
