### ISSUE TITLE
dev-vcs/git-annex-6.20170101 fails to compile: "Failed to load interface for ‘Crypto.Random’"

### ISSUE THREAD

**Issue by atlaua** [gentoo-haskell/gentoo-haskell#568]
The latest two versions of git-annex (with USE="concurrentoutput cryptonite network-uri") fail to compile on my systems; the reported error is:

Utility/AuthToken.hs:29:1: error:
    Failed to load interface for ‘Crypto.Random’
    Perhaps you meant Crypto.Random (from cryptonite-0.21)

Other than that, the build log looks good; please tell me if you want to have a look at it.

According to haskell-updater, everything's fine; nevertheless I've re-emerged dev-haskell/cryptonite (to no avail). Setting USE=-cryptonite doesn't help either.

**Comment by atlaua** [comment]
Looking at the source code proved to be enlightning :)

It seems git-annex.cabal is missing a dependency on the crypto-api package. I'll report it upstream.

**Comment by trofi** [comment]
https://github.com/gentoo-haskell/gentoo-haskell/commit/9397f499cfd914eb0c075404de1afd45ee56468f fixes build for me on your USE flags.

Nice catch!
