### ISSUE TITLE
Add the option to build submodules of sci-mathematics/agda like fix-agda-whitespace with USE flags

### ISSUE THREAD

**Issue by turion** [gentoo-haskell/gentoo-haskell#584]
I'm starting to contribute to agda-stdlib and it turns out that you need a tool called [`fix-agda-whitespace`](https://github.com/agda/agda/tree/master/src/fix-agda-whitespace), which is a submodule of `sci-mathematics/agda`. It would be great if it could be installed optionally with a USE flag. How would I go about implementing that?

**Comment by trofi** [comment]
Pushed as: https://github.com/gentoo-haskell/gentoo-haskell/commit/18b8b132d14e63eceba90ba917464b00c308f4c0
