### ISSUE TITLE
ERROR: dev-lang/ghc-8.0.1::haskell failed (compile phase)

### ISSUE THREAD

**Issue by arbitrary-dev** [gentoo-haskell/gentoo-haskell#591]
[build.zip](https://github.com/gentoo-haskell/gentoo-haskell/files/769253/build.zip)
[info.txt](https://github.com/gentoo-haskell/gentoo-haskell/files/769254/info.txt)

```
"inplace/bin/ghc-stage1" -hisuf hi -osuf  o -hcsuf hc -static  -H32m -O -optc-march=native -opta-march=native -optl-Wl,-O1 -optl-Wl,--as-needed -optc-fno-stack-protector -Wall      -this-unit-id base-4.9.0.0 -hide-all-packages -i -ilibraries/base/. -ilibraries/base/dist-install/build -ilibraries/base/dist-install/build/autogen -Ilibraries/base/dist-install/build -Ilibraries/base/dist-install/build/autogen -Ilibraries/base/include   -optP-DOPTIMISE_INTEGER_GCD_LCM -optP-include -optPlibraries/base/dist-install/build/autogen/cabal_macros.h -package-id ghc-prim-0.5.0.0 -package-id integer-gmp-1.0.0.1 -package-id rts -this-unit-id base -XHaskell2010 -O2  -no-user-package-db -rtsopts -Wno-trustworthy-safe -Wno-deprecated-flags     -Wnoncanonical-monad-instances  -odir libraries/base/dist-install/build -hidir libraries/base/dist-install/build -stubdir libraries/base/dist-install/build -split-objs  -dynamic-too -c libraries/base/./GHC/Conc/Signal.hs -o libraries/base/dist-install/build/GHC/Conc/Signal.o -dyno libraries/base/dist-install/build/GHC/Conc/Signal.dyn_o
collect2: error: ld returned 1 exit status
`x86_64-pc-linux-gnu-gcc' failed in phase `Linker'. (Exit code: 1)
make[1]: *** [libraries/base/ghc.mk:4: libraries/base/dist-install/build/GHC/Event/PSQ.o] Error 1
make[1]: *** Waiting for unfinished jobs....
collect2: error: ld returned 1 exit status
`x86_64-pc-linux-gnu-gcc' failed in phase `Linker'. (Exit code: 1)
make[1]: *** [libraries/base/ghc.mk:4: libraries/base/dist-install/build/System/Posix/Types.o] Error 1
make: *** [Makefile:134: ghc/stage2/build/tmp/ghc-stage2] Error 2
 * ERROR: dev-lang/ghc-8.0.1::haskell failed (compile phase):
 *   emake failed
```

**Comment by trofi** [comment]
Can you reproduce it? Does the build fail in the same place?

**Comment by arbitrary-dev** [comment]
Tried different GCC -Ox options, all the same.

**Comment by trofi** [comment]
How did you get that build.log? It does not seem to contain actual
commands being ran at `./configure` and `make` time.

Does `dmesg` report any reason why ld crashed?

**Comment by arbitrary-dev** [comment]
>How did you get that build.log?

Got it from "The complete build log is located at '/var/tmp/portage/dev-lang/ghc-8.0.1/temp/build.log'"

>Does dmesg report any reason why ld crashed?

There are some strange messages...

```
[47517.386640] sd 6:0:0:0: [sdc] tag#0 FAILED Result: hostbyte=DID_ERROR driverbyte=DRIVER_SENSE
[47517.386642] sd 6:0:0:0: [sdc] tag#0 Sense Key : Hardware Error [current] [descriptor] 
[47517.386643] sd 6:0:0:0: [sdc] tag#0 Add. Sense: No additional sense information
[47517.386644] sd 6:0:0:0: [sdc] tag#0 CDB: ATA command pass through(16) 85 06 20 00 00 00 00 00 00 00 00 00 00 00 e5 00
```

**Comment by trofi** [comment]
I was wondering if you had OOMs but this looks like worse HDD problem.
Do you use `sdc` to host `/usr/` or `/var/tmp`?

To get more detailed linker erro you can go to a build dir and run failed command with `-v` appended, like

    "inplace/bin/ghc-stage1" -hisuf hi -osuf  o -hcsuf hc -static  -H32m -O -optc-march=native -opta-march=native -optl-Wl,-O1 -optl-Wl,--as-needed -optc-fno-stack-protector -Wall      -this-unit-id base-4.9.0.0 -hide-all-packages -i -ilibraries/base/. -ilibraries/base/dist-install/build -ilibraries/base/dist-install/build/autogen -Ilibraries/base/dist-install/build -Ilibraries/base/dist-install/build/autogen -Ilibraries/base/include   -optP-DOPTIMISE_INTEGER_GCD_LCM -optP-include -optPlibraries/base/dist-install/build/autogen/cabal_macros.h -package-id ghc-prim-0.5.0.0 -package-id integer-gmp-1.0.0.1 -package-id rts -this-unit-id base -XHaskell2010 -O2  -no-user-package-db -rtsopts -Wno-trustworthy-safe -Wno-deprecated-flags     -Wnoncanonical-monad-instances  -odir libraries/base/dist-install/build -hidir libraries/base/dist-install/build -stubdir libraries/base/dist-install/build -split-objs  -dynamic-too -c libraries/base/./GHC/Conc/Signal.hs -o libraries/base/dist-install/build/GHC/Conc/Signal.o -dyno libraries/base/dist-install/build/GHC/Conc/Signal.dyn_o -v

**Comment by arbitrary-dev** [comment]
It seems like OOM was the culprit. Have increases /var/tmp/portage from 2g to 12g and it compiled without issues. Perhaps ebuild requires some constraint on memory.
