### ISSUE TITLE
app-text/pandoc-1.19.2.1 version bump request

### ISSUE THREAD

**Issue by equaeghe** [gentoo-haskell/gentoo-haskell#593]
It uses another highlighting library, skylighting, which fixes some inaccuracies of highlighting-kate (I am hitting).

**Comment by trofi** [comment]
Bumped as: https://github.com/gentoo-haskell/gentoo-haskell/commit/3e28bf6f5f2c6d26c9e9c63ae505bd7ab080ed35

Thank you!
