### ISSUE TITLE
dev-haskell/glib compile failure

### ISSUE THREAD

**Issue by Benevolent** [gentoo-haskell/gentoo-haskell#611]
Hello, I have been trying to install the Leksah IDE but have hit the following issue upon compiling the Haskell glib package

<code>
 * ERROR: dev-haskell/glib-0.13.2.2::haskell failed (configure phase):
 *   compiling /var/tmp/portage/dev-haskell/glib-0.13.2.2/work/glib-0.13.2.2/Setup.hs failed
 * 
 * Call stack:
 *     ebuild.sh, line  115:  Called src_configure
 *   environment, line 2796:  Called haskell-cabal_src_configure '--flags=closure_signals'
 *   environment, line 1917:  Called cabal-bootstrap
 *   environment, line  454:  Called die
 * The specific snippet of code:
 *           } || make_setup "$@" || die "compiling ${setupmodule} failed";
 * 
 * If you need support, post the output of `emerge --info '=dev-haskell/glib-0.13.2.2::haskell'`,
 * the complete build log and the output of `emerge -pqv '=dev-haskell/glib-0.13.2.2::haskell'`.
 * The complete build log is located at '/var/tmp/portage/dev-haskell/glib-0.13.2.2/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/dev-haskell/glib-0.13.2.2/temp/environment'.
 * Working directory: '/var/tmp/portage/dev-haskell/glib-0.13.2.2/work/glib-0.13.2.2'
 * S: '/var/tmp/portage/dev-haskell/glib-0.13.2.2/work/glib-0.13.2.2'
</code>

I can reliably reproduce this issue with a simple
"sudo emerge --ask leksah"

Attached is the relevant build.log
[build.log.txt](https://github.com/gentoo-haskell/gentoo-haskell/files/975198/build.log.txt)

I notice that this log contains messages about a cabal version mismatch. I have tried this with the latest cabal package, and have used haskell-updater to update the version of cabal I have installed.

**Comment by trofi** [comment]
The error here is attempt to use unstable `Cabal-1.24` on stable `glib-0.13.2.2`. I suggest keywording whole haskell overlay as unstable (like here https://github.com/gentoo-haskell/gentoo-haskell/#quickest-start)

```plain
 ^[[32;01m*^[[0m Using cabal-1.24.2.0.
 ^[[32;01m*^[[0m Prepending /usr/lib64/ghc-7.10.3 to LD_LIBRARY_PATH
/usr/bin/ghc -package Cabal-1.24.2.0 --make /var/tmp/portage/dev-haskell/glib-0.13.2.2/work/glib-0.13.2.2/Setup.hs -j5 +RTS -A256M -qb0 -RTS -threaded -dynamic -o setup
[1 of 2] Compiling SetupWrapper     ( SetupWrapper.hs, SetupWrapper.o )
```

It's likely not enough to get leksah working. IIRC leksah needs a port recent ghc due to changes in `bin-package-db` package (or something like that).

**Comment by Benevolent** [comment]
Ah, I see. Thank you for the explanation :>
