### ISSUE TITLE
dev-haskell/path-io-1.2.2 dependency problem

### ISSUE THREAD

**Issue by donat-b** [gentoo-haskell/gentoo-haskell#612]
```
Configuring path-io-1.2.2...
setup: Encountered missing dependencies:
time >=1.4 && <1.7
```

Builds against `time-1.8.0.1`

**Comment by trofi** [comment]
Pushed https://github.com/gentoo-haskell/gentoo-haskell/commit/34d94dff5cc14e36ff2761c02246bae6bb034d5a to the overlay. Submitted dep loosening upstream as https://github.com/mrkkrp/path-io/pull/20

Thank you!
