### ISSUE TITLE
dev-haskell/tls requires <dev-haskell/cryptonite-0.23, but haskell overlay contains dev-haskell/cryptonite-0.23

### ISSUE THREAD

**Issue by crocket** [gentoo-haskell/gentoo-haskell#615]
When I execute `layman --sync-all; emerge --sync; emerge -putDN @world`, there is a package conflict because `dev-haskell/cryptonite-0.23::haskell` conflicts with `dev-haskell-/tls-0.3.10`.

I had to mask `>=dev-haskell/cryptonite-0.23` in `/etc/portage/package.mask`, but this is quite a hack.

Also, `emerge -putDN @world` took 8~18 minutes which is very long. Can I shave down the time it takes for emerge to calculate dependencies?

**Comment by NobbZ** [comment]
According to #614 the dependency problems should be fixed now.

Also you can use `emerge --regen` to shorten scan times during emerging. But maybe that will take a long time then, depending on your computer.

I do syncing and regenerating in a daily cron, but update manually. It dies only seldomly happen that I have to wait for more than 2 or 3 minutes, at least when I leave my computer alone for that time. It's a core2 2.4GHz and 4GiB of RAM, so not really a fast machine.

**Comment by crocket** [comment]
Is it like the following snippet?

```
emerge --sync
layman --sync-all
emerge --regen
```

**Comment by NobbZ** [comment]
yes

**Comment by crocket** [comment]
I executed

```
emerge --sync
layman --sync-all
emerge --regen
```

But, `emerge -putDN @world` still takes 8 minutes.

**Comment by trofi** [comment]
I believe version conflict should be fixed by https://github.com/gentoo-haskell/gentoo-haskell/commit/35470341bf6bba35b803af3e6d9ab4f0483ec275

**Comment by trofi** [comment]
As for slowness there might be various causes for it:
- One of them is portage's attempts to unmask a random package to allow the upgrade. `--autounmask=n` emerge's option helps in that
- Another is other packages that fail to upgrade due to unrelated conflicts. You can roughly see such packages in `eix -cu` output. But be careful: slotted packages are frequently fine to sit in old slot.

**Comment by crocket** [comment]
The conflict was fixed. I'll try `--autounmask=n`
