### ISSUE TITLE
persistent-sqlite ebuild tries to compile with mutually exclusive -pic and -r

### ISSUE THREAD

**Issue by thornecc** [gentoo-haskell/gentoo-haskell#619]
To reproduce, emerge `persistent-sqlite` (I tried all versions currently in the overlay). The build shortly fails with:
```
Building persistent-sqlite-2.2.1...
Preprocessing library persistent-sqlite-2.2.1...
[1 of 2] Compiling Database.Sqlite  ( Database/Sqlite.hs, dist/build/Database/Sqlite.o )
/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: -r and -pie may not be used together
collect2: error: ld returned 1 exit status
```

As far as I understand it, this linker flags are mutually exclusive. I am not sure why both are being set, nor am I sure which is the desirable one by default.

Neither `-r` nor `-pie` is in my `LDFLAGS`. I can provide the full build log if necessary.

**Comment by trofi** [comment]
Which gcc and ghc version you are using?

**Comment by trofi** [comment]
Ah, I've missed the gcc version in linker error. gentoo decides right now whether USE=pie should be enabled by default or not. Over past few days flag was flipped on and off.

ghc-8.0.2 should be able to cope with any pie mode, but GHC should be built against fresh enough gcc.
You can check if your GHC understands pie flags as:
```
$ ghc --info | grep pie
 ,("C compiler supports -no-pie","YES")
```

It should be `YES`.

**Comment by thornecc** [comment]
It said `NO`. After rebuilding GHC, it says `YES` and `persistent-sqlite` compiled successfully. Thanks!
