### ISSUE TITLE
Move dev-haskell/stack to ::gentoo

### ISSUE THREAD

**Issue by Moiman** [gentoo-haskell/gentoo-haskell#622]
Hello. It would be nice to have stack in ::gentoo.

**Comment by trofi** [comment]
Sounds good. Will require importing about 20 packages to main tree.

**Comment by trofi** [comment]
Pushed as: https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=be086dd1af05368a28a87e862c58372e0555e223
