### ISSUE TITLE
Missing dependencies for dev-haskell/reactive-banana-wx[buildexamples]

### ISSUE THREAD

**Issue by hololeap** [gentoo-haskell/gentoo-haskell#630]
emerging dev-haskell/reactive-banana-wx with the "buildexamples" USE flag enabled fails with the following error:

Configuring reactive-banana-wx-1.1.1.0...
setup: Encountered missing dependencies:
filepath >=1.1 && <=1.4.0.0, process >=1.0 && <1.4

**Comment by trofi** [comment]
Those packages are part of `ghc`. Which `ghc` version you were using? `build.log` should contain all relevant info.

**Comment by hololeap** [comment]
The Glorious Glasgow Haskell Compilation System, version 8.0.2


[build.log.txt](https://github.com/gentoo-haskell/gentoo-haskell/files/1191731/build.log.txt)

**Comment by trofi** [comment]
Aha! Pushed as https://github.com/gentoo-haskell/gentoo-haskell/commit/4fe7395fcd2fb8405c5fbe27640580ba12995770

Thanks for the report!
