### ISSUE TITLE
ebuild for ihaskell 0.9.0.1

### ISSUE THREAD

**Issue by Anrock** [gentoo-haskell/gentoo-haskell#632]
0.9.0.1 was recently pushed to hackage, could you release a ebuild for it?

**Comment by trofi** [comment]
Does upstream version compile for you with stack or cabal-install?
hackage release and git version lack proper dependency ranges and imports:

```
[3 of 3] Compiling Main             ( main/Main.hs, dist/build/ihaskell/ihaskell-tmp/Main.dyn_o )

main/Main.hs:268:11: error:
    Not in scope: data constructor ‘CommInfoRequest’

main/Main.hs:271:13: error:
    Not in scope: data constructor ‘CommInfoReply’

main/Main.hs:273:17: error: Not in scope: ‘commInfo’

```

**Comment by Anrock** [comment]
@trofi it builds throught `stack install ihaskell-0.9.0.1`. 
They've put `source-repository head` in a cabal file, so it sometimes builds, sometimes not, dependening on a current master of https://github.com/gibiansky/IHaskell. Maybe ebuild should be called ihaskell-0.9.0.1-live or something. Or better just make ihaskell-9999.

**Comment by vaibhavsagar** [comment]
How should we be doing it instead?

**Comment by JonathanFraser** [comment]
This looks to be a misnomer. source-repository head should point to the head of the repo. There is an optional source-repository this which and point at the specific version, but cabal should be installing from the archived tarball.

**Comment by solpeth** [comment]
@trofi @Anrock could this be considered resolved?

**Comment by Anrock** [comment]
@solpeth i guess so, thank you.
