### ISSUE TITLE
x11-misc/taffybar-9999 requires dev-haskell/tuple

### ISSUE THREAD

**Issue by iamjamestl** [gentoo-haskell/gentoo-haskell#636]
This new dependency was added two weeks ago in:

https://github.com/travitch/taffybar/commit/e0a3950696e084edd8054a24b49f69c6a5b9cd50#diff-75dc431070952ab70e4f3b87128b6c6f

**Comment by trofi** [comment]
Added missing depend as: https://github.com/gentoo-haskell/gentoo-haskell/commit/7223e869af5efb1f06028191b9ff3d99f3158f9b

Apologies for a late response.

Thanks for the report!
