### ISSUE TITLE
dev-haskell/linear compilation fails

### ISSUE THREAD

**Issue by madjestic** [gentoo-haskell/gentoo-haskell#654]
Hey guys,

After getting latest on Monday (Nov 20), an emerge of dev-haskell/linear failed with the [following error](http://lpaste.net/360188):

`
src/Linear/Instances.hs:30:10: error:
    Duplicate instance declarations:
      instance (Hashable k, Eq k) => Apply (HashMap k)
        -- Defined at src/Linear/Instances.hs:30:10
      instance [safe] (Hashable k, Eq k) => Apply (HashMap k)
        -- Defined in ‘Data.Functor.Bind.Class’

src/Linear/Instances.hs:33:10: error:
    Duplicate instance declarations:
      instance (Hashable k, Eq k) => Bind (HashMap k)
        -- Defined at src/Linear/Instances.hs:33:10
      instance [safe] (Hashable k, Eq k) => Bind (HashMap k)
        -- Defined in ‘Data.Functor.Bind.Class’

src/Linear/Instances.hs:41:10: error:
    Duplicate instance declarations:
      instance Apply Complex -- Defined at src/Linear/Instances.hs:41:10
      instance [safe] Apply Complex
        -- Defined in ‘Data.Functor.Bind.Class’

src/Linear/Instances.hs:44:10: error:
    Duplicate instance declarations:
      instance Bind Complex -- Defined at src/Linear/Instances.hs:44:10
      instance [safe] Bind Complex
        -- Defined in ‘Data.Functor.Bind.Class’

src/Linear/Instances.hs:56:10: error:
    Duplicate instance declarations:
      instance Foldable1 Complex
        -- Defined at src/Linear/Instances.hs:56:10
      instance [safe] Foldable1 Complex
        -- Defined in ‘Data.Semigroup.Foldable.Class’

src/Linear/Instances.hs:60:10: error:
    Duplicate instance declarations:
      instance Traversable1 Complex
        -- Defined at src/Linear/Instances.hs:60:10
      instance [safe] Traversable1 Complex
        -- Defined in ‘Data.Semigroup.Traversable.Class’
`
Here's the [emerge --info output](http://lpaste.net/8404572204460670976).

I think [there's a version bump on hackage](https://hackage.haskell.org/package/linear).  Maybe it's the matter of bumping the ebuild version?

Best regards,
Vlad

**Comment by trofi** [comment]
Gah, sorry about that!

I've forgot to push out locally the commit with linear bump. Should be landed now as: https://github.com/gentoo-haskell/gentoo-haskell/commit/3135dbdc328d65fa9269791ffbebf3fcd8be973f
