### ISSUE TITLE
Add ebuild for reflex?

### ISSUE THREAD

**Issue by ag-eitilt** [gentoo-haskell/gentoo-haskell#659]
Is there some reason reflex isn't in the repo yet? If not, I'm a bit surprised I'm the first to request it. Thanks so much for providing these, by the way!

**Comment by trofi** [comment]
Does it work upstream against `ghc-8`?

Looking at the depends at https://hackage.haskell.org/package/reflex it does not allow `ghc-8`'s base and `template-haskell`.

**Comment by Eitilt** [comment]
Ah, that *would* be a problem.

base seems fine, but the template-haskell doesn't work, so I've opened an issue at reflex-frp/reflex#149 to see about fixing it. In the mean time, is there a policy against it depending on ghc-8.0.2, seeing as that's the most recent version in the repo with any keywords on it?

**Comment by ag-eitilt** [comment]
0.4.0.1 with the updated dependency versions is now on Hackage. Not wanting to unmask a ghc without *any* keywords (I've only just enabled the unstable Haskell versions), I can't personally verify it works with 8.2.1, but I was the only one having problems with it, and that was only because I was installing template-haskell via cabal rather than getting it with ghc -- in normal use, everyone else was building it just fine.

**Comment by trofi** [comment]
No need to test on 8.2.1. As long as it works on ~arch ghc (8.0.2 presently) it's fine to be pulled in overlay.

**Comment by trofi** [comment]
And thanks for filing upstream bug! That is the most important bit :)

**Comment by ag-eitilt** [comment]
Agreed, unfortunately.  It's a nice package, but the development speed doesn't seem to be able to keep up.

**Comment by solpeth** [comment]
@ag-eitilt do you use reflex yourself? If it helps I'll push a live ebuild into the overlay while we wait on upstream.

**Comment by ag-eitilt** [comment]
I was, back when we were talking about it before, but I've since moved to a different project and probably won't resume the one using Reflex any time soon.  If I need it, I'll pull it in through Cabal for development, and figure out what to do for release when it comes to that -- who knows what may change between now and then.  Thanks for the offer, though!

**Comment by hololeap** [comment]
There is a new release in the works:
http://hackage.haskell.org/package/reflex-0.5/candidate

I suggest we re-open this ticket. A working Gentoo package may not be that far off...

**Comment by hololeap** [comment]
@ag-eitilt FYI a live ebuild has been added.

**Comment by solpeth** [comment]
Reflex-0.5 has been released upstream and is now in our repo.
