### ISSUE TITLE
One of the thirdpartymirrors redirects to an unencrypted HTTP site during fetch

### ISSUE THREAD

**Issue by hololeap** [gentoo-haskell/gentoo-haskell#660]
This concerns the second entry of the line in profiles/thirdpartymirrors
`hackage https://hackage.haskell.org/ https://dev.gentoo.org/~qnikst/hdiff.luite.com/`

Currently, all requests to `https://dev.gentoo.org/~qnikst/hdiff.luite.com/` are redirecting to `http://hdiff.luite.com/`. There is no functioning HTTPS on `hdiff.luite.com` and this leaves the downloaded tarballs vulnerable to MITM attacks. 

I would recommend removing the second entry and relying only on `https://hackage.haskell.org/` or finding another HTTPS mirror if that doesn't work.

**Comment by trofi** [comment]
The fallback was added in the days when hackage was not very stable and had no mirrors on it's own. I think it's reasonably more stable nowadays.

Did have any issues with `hdiff.luite.com` or just eyeballed it from logs?

**Comment by hololeap** [comment]
I noticed in the fetch logs that it kept redirecting to http://hdiff.luite.com/

**Comment by trofi** [comment]
Aha. Would you like to submit a pull request to `::haskell` and `::gentoo` or should I get to it at some point?

**Comment by hololeap** [comment]
I have also opened up a bug on Bugzilla:
https://bugs.gentoo.org/644382

**Comment by trofi** [comment]
Thank you!

I've cherry-picked commit from https://github.com/gentoo-haskell/gentoo-haskell/pull/661 with longest description as the branch history was a bit involved to merge directly.
