### ISSUE TITLE
Bumping dev-haskell/stack

### ISSUE THREAD

**Issue by cuklev** [gentoo-haskell/gentoo-haskell#664]
I tried to bump `dev-haskell/stack` to version 1.6.3. I emerged `app-portage/hackport` and started to generate ebuilds. After a while I realized that some of my installed packages still depend on older versions of `stack`'s dependencies, thus blocking `stack-1.6.3`. Is there something smart that I can do or do I need to bump a lot?

**Comment by trofi** [comment]
As I understand you need at least Cabal-2 which will likely break quite a bit of packages.

**Comment by trofi** [comment]
Forgot to mention: the alternative is to resort to `dev-haskell/stack-bin` package.

**Comment by cuklev** [comment]
Hadn't noticed there is `dev-haskell/stack-bin`. I suppose using it will be the most painless solution for now. Thanks!
