### ISSUE TITLE
dev-haskell/trifecta-1.6.2.1-r1 cannot build against dev-haskell/ansi-wl-pprint-0.6.8.2

### ISSUE THREAD

**Issue by crocket** [gentoo-haskell/gentoo-haskell#668]
I suspect the solution is to upgrade trifecta to 1.7.1.1

https://github.com/ekmett/trifecta/releases says `1.7.1.1 – support new ansi-wl-pprint and doctest`

**Comment by trofi** [comment]
Can you attach build log? It certainly builds for me.

**Comment by crocket** [comment]
After numerous attempts, it started building again.

It seems like a glitch in my upgrade process.
