### ISSUE TITLE
Stack requires nonexistent version of persistent

### ISSUE THREAD

**Issue by Hypoon** [gentoo-haskell/gentoo-haskell#672]
I mentioned this as a comment in another issue, but I should have created a new issue for it.

dev-haskell/stack-1.5.1-r1 has
RDEPEND=">=dev-haskell/persistent-2.1.2:=[profile?] <dev-haskell/persistent-2.8:=[profile?]"
but dev-haskell/persistent only has version 2.8.0 in the overlay.

There are probably other dependency issues on my system, but I'm at work and can't investigate now. I'll edit this post if I find more.

**Comment by trofi** [comment]
I've restored older versions. Older versions are also through ::gentoo.
