### ISSUE TITLE
stack-1.5.1-r1 depends on <dev-haskell/http-conduit-2.3

### ISSUE THREAD

**Issue by Hypoon** [gentoo-haskell/gentoo-haskell#676]
Please revert commit d4cb38ed98f92c59f39e8bc2e0b7cbc2abc6a3cd (which removed all atoms satisfying <dev-haskell/http-conduit-2.3).

Am I doing the right thing by reporting these dependency issues?

**Comment by Hypoon** [comment]
eix-test-obsolete caught dev-haskell/conduit, dev-haskell/conduit-extra, and dev-haskell/resourcet with analogous problems.

stack-1.5.1-r1 requires <dev-haskell/conduit-1.3, <dev-haskell/conduit-extra-1.2, and <dev-haskell/resourcet-1.2

These dependencies were removed from the tree by commits 6de8ca80bf057bbf18f98260728613aa5bc4081c, cf627dfe669a73686bd64778d51588c299f13de5, and bf6e558384a8d3875dfda22ce5a3237ed0c61a2b.

**Comment by Hypoon** [comment]
I think this should be reopened, because there is still a dependency issue between the current versions of http-conduit and stack.

**Comment by trofi** [comment]
How does it manifest?

**Comment by Hypoon** [comment]
On my system, I reverted the commit (d4cb38ed98f92c59f39e8bc2e0b7cbc2abc6a3cd), so portage does not present the error on *my* system anymore. The repository still has the inconsistency though.

=dev-haskell/stack-1.5.1-r1 has:
RDEPEND=">=dev-haskell/http-conduit-2.2.3:=[profile?] <dev-haskell/http-conduit-2.3:=[profile?]"

but =dev-haskell/http-conduit-2.3.0 is the only version of http-conduit available. There is no version to satisfy <dev-haskell/http-conduit-2.3, so without mixing in packages from ::gentoo, one cannot install =dev-haskell/stack-1.5.1-r1 after updating http-conduit.
