### ISSUE TITLE
Testing for Dependency Problems

### ISSUE THREAD

**Issue by Hypoon** [gentoo-haskell/gentoo-haskell#677]
I discovered a way to possibly check for dependency issues. I've noticed that I don't notice anything wrong until I update some package which causes other packages to rebuild. Here's the timeline, using http-conduit as an example:

1. http-conduit gets version-bumped to 2.3.x and old versions get deleted
2. I update @world, but portage knows that stack-1.5.1-r1 needs <http-conduit-2.3, so it doesn't update http-conduit. (All goes well.)
3. other packages get version-bumped
4. I update @world, and some update requires portage to rebuild http-conduit and stack. Portage can't find an ebuild for the version of http-conduit I have installed, so it skips rebuilding it (This seems bad... shouldn't it yield an error instead?). Rebuilding stack-1.5.1-r1 fails.

I've noticed that after step 2, eix-test-obsolete will catch if there are any installed packages without matching ebuilds. This is an early-indicator for potential issues.

**Comment by solpeth** [comment]
@Hypoon is there a specific issue in relation to this or is this more of a suggestion for catching dependency conflicts? Just want to make sure that I'm understanding you properly. Thanks!
