### ISSUE TITLE
=dev-haskell/tls-1.4.1 interferes with =dev-haskell/stack-1.5.1-r1

### ISSUE THREAD

**Issue by Hypoon** [gentoo-haskell/gentoo-haskell#697]
commit e6bc5961a45721f085f389159927265dab207265 bumped dev-haskell/tls to version 1.4.1, with RDEPEND=">=dev-haskell/cryptonite-0.24:=[profile?]", but this conflicts with the latest unmasked version or dev-haskell/stack, which is 1.5.1-r1, with RDEPEND=">=dev-haskell/cryptonite-0.19:=[profile?] <dev-haskell/cryptonite-0.24:=[profile?]".

Specifically, you can't have a version of dev-haskell/cryptonite which is simultaneously both <0.24 and >=0.24, which makes =dev-haskell/tls-1.4.1 and =dev-haskell/stack-1.5.1-r1 incompatible.

UPDATE: just noticed that =dev-haskell/stack-1.5.1-r1 also has RDEPEND=">=dev-haskell/tls-1.3.8:=[profile?] <dev-haskell/tls-1.4:=[profile?]", which means version 1.4.1 is a direct conflict as well.

UPDATE 2: Actually, there are lots of updates which cause issues:
async-2.2.1
base-compat-0.10.1
cryptonite-0.25
either-5
generic-deriving-1.12.1
lifted-async-0.10.0.1
optparse-simple-0.1.0
streaming-commons-0.2.0.0
tls-1.4.1

NOTE: I have not done my homework regarding checking what other packages might depend on these updates, so there may be even more commits that need to be reverted.

I forget, should portage be aware enough to simply ignore these updates due to dependency issues with stack-1.5.1-r1?

**Comment by trofi** [comment]
Should be fixed now.
