### ISSUE TITLE
need some unmasking to get an eventually sucessful build plan

### ISSUE THREAD

**Issue by waivio** [gentoo-haskell/gentoo-haskell#700]
Hi All,
I had some difficult updates recently, had to unmask several things:

>  cat package.unmask
> # Unmask latest aeson to see if it fixes build plan for latest Criterion required base-compat-batteries requirement of base-compat-0.10  
> =dev-haskell/aeson-1.3.1.0  
> # Unmask latest resourcet to fix build plans for hlint because transformers-compat is limited  
> =dev-haskell/resourcet-1.2.1  
> # Unmask latest conduit to fix build plans for hlint to allow newer resourcet  
> =dev-haskell/conduit-1.3.0.2  
> # Unmask latest conduit-extra to fix build plans for conduit  
> =dev-haskell/conduit-extra-1.3.0  
> # Unmask latest http-conduit to fix build plans for "I don't know what"  
> =dev-haskell/http-conduit-2.3.1  

For some reason haskell-updater doesn't handle the rebuild.  I had to essentially:
emerge -tav @package-rebuild
emerge -tav1 \<whatever-first-listed-broken-package>

in a loop until everything was built, then:
emerge -tav --depclean

seemed to removed 50-some dependencies
and:
revdep-rebuild

until everything was consistent.

Thanks,
nwaiv

**Comment by trofi** [comment]
Many packages are masked because they cause major conflicts when trying to update world. I suggest not unmasking them for now and showing here what is trying to pull masked versions.

**Comment by waivio** [comment]
Okay, I'll try and poke around.  So should I be looking for a package that should be masked and isn't and that is causing the build issues?

**Comment by trofi** [comment]
Yes. The package that forces you to unmask other packages.

**Comment by waivio** [comment]
For some reason emerge wants to downgrade transformers-compat to:
dev-haskell/transformers-compat-0.3.3.4
from the ::gentoo repo.

Such an old version is not compatible (ironically) with higher lower bounds of these packages:

-  dev-haskell/base-compat-batteries-0.10.1
-  dev-haskell/bifunctors-5.5.2
-  dev-haskell/criterion-1.4.1.0
-  dev-haskell/lens-4.16.1
-  dev-haskell/linear-1.20.7
-  dev-haskell/microlens-mtl-0.1.11.1
-  dev-haskell/semigroupoids-5.2.2-r1
-  dev-haskell/semigroups-0.18.4
-  dev-haskell/tagged-0.8.5

Should I mask: 
=dev-haskell/*::gentoo

**Comment by trofi** [comment]
Please provide exact emerge command you run and exact output of emerge.

**Comment by waivio** [comment]
sudo emerge -tav --update --deep --newuse --with-bdeps=y --backtrack=99 --verbose-conflicts world
Password: 

These are the packages that would be merged, in reverse order:

Calculating dependencies... done!
[ebuild  rR   ~] dev-haskell/yaml-0.8.29:0/0.8.29::haskell  USE="doc hoogle hscolour no-examples no-exe -no-unicode -profile -system-libyaml {-test}" 0 KiB
[ebuild  rR   ~] dev-haskell/criterion-1.4.1.0:0/1.4.1.0::haskell  USE="doc hoogle hscolour -embed-data-files -profile {-test}" 0 KiB
[ebuild  rR   ~]  dev-haskell/statistics-0.14.0.2:0/0.14.0.2::haskell  USE="doc hoogle hscolour -profile {-test}" 0 KiB
[ebuild  rR   ~]  dev-haskell/microstache-1.0.1.1:0/1.0.1.1::haskell  USE="doc hoogle hscolour -profile {-test}" 0 KiB
[ebuild  r  UD~] dev-haskell/conduit-1.2.13:0/1.2.13::haskell [1.3.0.2:0/1.3.0.2::haskell] USE="doc hoogle hscolour -profile {-test}" 0 KiB
[ebuild  r  UD~]  dev-haskell/resourcet-1.1.9:0/1.1.9::haskell [1.2.1:0/1.2.1::haskell] USE="doc hoogle hscolour -profile {-test}" 0 KiB
[ebuild  N    ~]   dev-haskell/lifted-base-0.2.3.12:0/0.2.3.12::haskell  USE="doc hoogle hscolour -profile {-test}" 0 KiB
[ebuild  N    ~]    dev-haskell/monad-control-1.0.2.3:0/1.0.2.3::haskell  USE="doc hoogle hscolour -profile" 0 KiB
[ebuild  r  UD~] dev-haskell/aeson-1.0.2.1-r2:0/1.0.2.1::haskell [1.3.1.0:0/1.3.1.0::haskell] USE="doc hoogle hscolour -profile {-test} (-cffi%)" 0 KiB
[nomerge       ] dev-haskell/conduit-1.2.13:0/1.2.13::haskell [1.3.0.2:0/1.3.0.2::haskell] USE="doc hoogle hscolour -profile {-test}" 
[nomerge       ]  dev-haskell/monad-control-1.0.2.3:0/1.0.2.3::haskell  USE="doc hoogle hscolour -profile" 
[ebuild     UD#]   dev-haskell/transformers-compat-0.4.0.4-r1:0/0.4.0.4::haskell [0.6.1.6:0/0.6.1.6::haskell] USE="doc hoogle hscolour -profile" 12 KiB

Total: 10 packages (4 downgrades, 2 new, 4 reinstalls), Size of downloads: 12 KiB

!!! Multiple package instances within a single package slot have been pulled
!!! into the dependency graph, resulting in a slot conflict:

dev-haskell/transformers-compat:0

  (dev-haskell/transformers-compat-0.6.1.6:0/0.6.1.6::haskell, installed) pulled in by
    >=dev-haskell/transformers-compat-0.5:=[profile?] required by (dev-haskell/tagged-0.8.5:0/0.8.5::haskell, installed)
    ^^                                ^^^                                                                                                                                                         
    >=dev-haskell/transformers-compat-0.4:0/0.6.1.6= required by (dev-haskell/lens-4.16.1:0/4.16.1::haskell, installed)
                                         ^^^^^^^^^^^                                                                                                       
    >=dev-haskell/transformers-compat-0.3:0/0.6.1.6= required by (dev-haskell/adjunctions-4.4:0/4.4::haskell, installed)
                                         ^^^^^^^^^^^                                                                                                        
    >=dev-haskell/transformers-compat-0.5:0/0.6.1.6= required by (dev-haskell/semigroups-0.18.4:0/0.18.4::haskell, installed)
    ^^                                ^^^^^^^^^^^^^^                                                                                                                                                   
    >=dev-haskell/transformers-compat-0.5:=[profile?] required by (dev-haskell/semigroupoids-5.2.2-r1:0/5.2.2::haskell, installed)
    ^^                                ^^^                                                                                                                                                                   
    >=dev-haskell/transformers-compat-0.5:0/0.6.1.6= required by (dev-haskell/base-compat-batteries-0.10.1:0/0.10.1::haskell, installed)
    ^^                                ^^^^^^^^^^^^^^                                                                                                                                                              
    >=dev-haskell/transformers-compat-0.3:0/0.6.1.6= required by (dev-haskell/exceptions-0.8.3-r2:0/0.8.3::haskell, installed)
                                         ^^^^^^^^^^^                                                                                                              
    >=dev-haskell/transformers-compat-0.3:0/0.6.1.6= required by (dev-haskell/bytes-0.15.3:0/0.15.3::haskell, installed)
                                         ^^^^^^^^^^^                                                                                                        
    >=dev-haskell/transformers-compat-0.5:0/0.6.1.6= required by (dev-haskell/bifunctors-5.5.2:0/5.5.2::haskell, installed)
    ^^                                ^^^^^^^^^^^^^^                                                                                                                                                 
    <dev-haskell/transformers-compat-1:0/0.6.1.6= required by (dev-haskell/linear-1.20.7:0/1.20.7::haskell, installed)
                                      ^^^^^^^^^^^                                                                                                         
    >=dev-haskell/transformers-compat-0.4:0/0.6.1.6= required by (dev-haskell/microlens-mtl-0.1.11.1:0/0.1.11.1::haskell, installed)
                                         ^^^^^^^^^^^                                                                                                                    
    >=dev-haskell/transformers-compat-0.3:0/0.6.1.6= required by (dev-haskell/kan-extensions-5.1:0/5.1::haskell, installed)
                                         ^^^^^^^^^^^                                                                                                           
    <dev-haskell/transformers-compat-1:0/0.6.1.6= required by (dev-haskell/microlens-mtl-0.1.11.1:0/0.1.11.1::haskell, installed)
                                      ^^^^^^^^^^^                                                                                                                    
    >=dev-haskell/transformers-compat-0.5:0/0.6.1.6= required by (dev-haskell/semigroupoids-5.2.2-r1:0/5.2.2::haskell, installed)
    ^^                                ^^^^^^^^^^^^^^                                                                                                                                                       
    >=dev-haskell/transformers-compat-0.5:=[profile?] required by (dev-haskell/base-compat-batteries-0.10.1:0/0.10.1::haskell, installed)
    ^^                                ^^^                                                                                                                                                                          
    >=dev-haskell/transformers-compat-0.2:0/0.6.1.6= required by (dev-haskell/transformers-base-0.4.4:0/0.4.4::haskell, installed)
                                         ^^^^^^^^^^^                                                                                                                  
    <dev-haskell/transformers-compat-1:0/0.6.1.6= required by (dev-haskell/comonad-5.0.3:0/5.0.3::haskell, installed)
                                      ^^^^^^^^^^^                                                                                                        
    >=dev-haskell/transformers-compat-0.3:0/0.6.1.6= required by (dev-haskell/optparse-applicative-0.14.2.0:0/0.14.2.0::haskell, installed)
                                         ^^^^^^^^^^^                                                                                                                           
    >=dev-haskell/transformers-compat-0.3:0/0.6.1.6= required by (dev-haskell/mmorph-1.1.2:0/1.1.2::haskell, installed)
                                         ^^^^^^^^^^^                                                                                                       
    >=dev-haskell/transformers-compat-0.3:0/0.6.1.6= required by (dev-haskell/comonad-5.0.3:0/5.0.3::haskell, installed)
                                         ^^^^^^^^^^^                                                                                                        
    >=dev-haskell/transformers-compat-0.4:0/0.6.1.6= required by (dev-haskell/linear-1.20.7:0/1.20.7::haskell, installed)
                                         ^^^^^^^^^^^                                                                                                         
    <dev-haskell/transformers-compat-1:0/0.6.1.6= required by (dev-haskell/adjunctions-4.4:0/4.4::haskell, installed)
                                      ^^^^^^^^^^^                                                                                                        
    <dev-haskell/transformers-compat-1:0/0.6.1.6= required by (dev-haskell/semigroups-0.18.4:0/0.18.4::haskell, installed)
                                      ^^^^^^^^^^^                                                                                                             
    <dev-haskell/transformers-compat-0.7:0/0.6.1.6= required by (dev-haskell/glob-0.9.2:0/0.9.2::haskell, installed)
                                        ^^^^^^^^^^^                                                                                                     
    <dev-haskell/transformers-compat-1:0/0.6.1.6= required by (dev-haskell/contravariant-1.4.1:0/1.4.1::haskell, installed)
                                      ^^^^^^^^^^^                                                                                                              
    >=dev-haskell/transformers-compat-0.3:0/0.6.1.6= required by (dev-haskell/contravariant-1.4.1:0/1.4.1::haskell, installed)
                                         ^^^^^^^^^^^                                                                                                              
    >=dev-haskell/transformers-compat-0.3:0/0.6.1.6= required by (dev-haskell/glob-0.9.2:0/0.9.2::haskell, installed)
                                         ^^^^^^^^^^^                                                                                                     
    <dev-haskell/transformers-compat-1:0/0.6.1.6= required by (dev-haskell/bytes-0.15.3:0/0.15.3::haskell, installed)
                                      ^^^^^^^^^^^                                                                                                        
    >=dev-haskell/transformers-compat-0.3:0/0.6.1.6= required by (dev-haskell/distributive-0.5.3:0/0.5.3::haskell, installed)
                                         ^^^^^^^^^^^                                                                                                             
    <dev-haskell/transformers-compat-0.7:0/0.6.1.6= required by (dev-haskell/mmorph-1.1.2:0/1.1.2::haskell, installed)
                                        ^^^^^^^^^^^                                                                                                       
    <dev-haskell/transformers-compat-1:0/0.6.1.6= required by (dev-haskell/distributive-0.5.3:0/0.5.3::haskell, installed)
                                      ^^^^^^^^^^^                                                                                                             
    <dev-haskell/transformers-compat-0.7:0/0.6.1.6= required by (dev-haskell/kan-extensions-5.1:0/5.1::haskell, installed)
                                        ^^^^^^^^^^^                                                                                                           
    >=dev-haskell/transformers-compat-0.5:=[profile?] required by (dev-haskell/bifunctors-5.5.2:0/5.5.2::haskell, installed)
    ^^                                ^^^                                                                                                                                                             
    <dev-haskell/transformers-compat-1:0/0.6.1.6= required by (dev-haskell/free-5.0.1:0/5.0.1::haskell, installed)
                                      ^^^^^^^^^^^                                                                                                     
    <dev-haskell/transformers-compat-1:0/0.6.1.6= required by (dev-haskell/lens-4.16.1:0/4.16.1::haskell, installed)
                                      ^^^^^^^^^^^                                                                                                       
    >=dev-haskell/transformers-compat-0.5:0/0.6.1.6= required by (dev-haskell/tagged-0.8.5:0/0.8.5::haskell, installed)
    ^^                                ^^^^^^^^^^^^^^                                                                                                                                             
    >=dev-haskell/transformers-compat-0.5:=[profile?] required by (dev-haskell/semigroups-0.18.4:0/0.18.4::haskell, installed)
    ^^                                ^^^                                                                                                                                                               
    >=dev-haskell/transformers-compat-0.3:0/0.6.1.6= required by (dev-haskell/free-5.0.1:0/5.0.1::haskell, installed)
                                         ^^^^^^^^^^^                                                                                                     
    <dev-haskell/transformers-compat-1:0/0.6.1.6= required by (dev-haskell/tagged-0.8.5:0/0.8.5::haskell, installed)
                                      ^^^^^^^^^^^                                                                                                       
    <dev-haskell/transformers-compat-0.7:0/0.6.1.6= required by (dev-haskell/optparse-applicative-0.14.2.0:0/0.14.2.0::haskell, installed)
                                        ^^^^^^^^^^^                                                                                                                           

  (dev-haskell/transformers-compat-0.4.0.4-r1:0/0.4.0.4::haskell, ebuild scheduled for merge) pulled in by
    <dev-haskell/transformers-compat-0.6:=[profile?] required by (dev-haskell/resourcet-1.1.9:0/1.1.9::haskell, ebuild scheduled for merge)
    ^                                ^^^ ^                                                                                                                                                                           


It may be possible to solve this problem by using package.mask to
prevent one of those packages from being selected. However, it is also
possible that conflicting dependencies exist such that they are
impossible to satisfy simultaneously.  If such a conflict exists in
the dependencies of two different packages, then those packages can
not be installed simultaneously.

For more information, see MASKED PACKAGES section in the emerge man
page or refer to the Gentoo Handbook.


The following packages are causing rebuilds:

  (dev-haskell/conduit-1.2.13:0/1.2.13::haskell, ebuild scheduled for merge) causes rebuilds for:
    (dev-haskell/yaml-0.8.29:0/0.8.29::haskell, ebuild scheduled for merge)
  (dev-haskell/resourcet-1.1.9:0/1.1.9::haskell, ebuild scheduled for merge) causes rebuilds for:
    (dev-haskell/conduit-1.2.13:0/1.2.13::haskell, ebuild scheduled for merge)
    (dev-haskell/yaml-0.8.29:0/0.8.29::haskell, ebuild scheduled for merge)
  (dev-haskell/transformers-compat-0.4.0.4-r1:0/0.4.0.4::haskell, ebuild scheduled for merge) causes rebuilds for:
    (dev-haskell/criterion-1.4.1.0:0/1.4.1.0::haskell, ebuild scheduled for merge)
  (dev-haskell/aeson-1.0.2.1-r2:0/1.0.2.1::haskell, ebuild scheduled for merge) causes rebuilds for:
    (dev-haskell/criterion-1.4.1.0:0/1.4.1.0::haskell, ebuild scheduled for merge)
    (dev-haskell/statistics-0.14.0.2:0/0.14.0.2::haskell, ebuild scheduled for merge)
    (dev-haskell/microstache-1.0.1.1:0/1.0.1.1::haskell, ebuild scheduled for merge)
    (dev-haskell/yaml-0.8.29:0/0.8.29::haskell, ebuild scheduled for merge)

The following mask changes are necessary to proceed:
 (see "package.unmask" in the portage(5) man page for more details)
# required by dev-haskell/resourcet-1.1.9::haskell
# required by dev-haskell/yaml-0.8.29::haskell
# required by @__auto_slot_operator_replace_installed__ (argument)
# /etc/portage/package.mask:
#freedom from systemd
#::gentoo repo interfearing with ::haskell repo mask old versions of transformers-compat less than 0.5
=dev-haskell/transformers-compat-0.4.0.4-r1

NOTE: The --autounmask-keep-masks option will prevent emerge
      from creating package.unmask or ** keyword changes.

**Comment by trofi** [comment]
Most of conflicts for you are caused by `resourcet-1.1.9` trying to pull older `transformers-compat`:
```
  (dev-haskell/transformers-compat-0.4.0.4-r1:0/0.4.0.4::haskell, ebuild scheduled for merge) pulled in by
    <dev-haskell/transformers-compat-0.6:=[profile?] required by (dev-haskell/resourcet-1.1.9:0/1.1.9::haskell, ebuild scheduled for merge)
    ^                                ^^^ ^       
```

It's caused by `resourcet` dependencies:
```
        >=dev-haskell/transformers-compat-0.3:=[profile?] <dev-haskell/transformers-compat-0.6:=[profile?]
```

We need to:
- either fix `resourcet` (and others) to allow `transformers-compat-0.6`
- or mask `>=transformers-compat-0.6` until all users are fixed.

You can try masking for now until this bug is fixed.

**Comment by trofi** [comment]
I've masked `transformers-compat-0.6` as https://github.com/gentoo-haskell/gentoo-haskell/commit/8791e090efc97589562e853884b94968d96be121 . Please try again and check what blocks your update now. We will likely have to fix quite a few depends.

**Comment by waivio** [comment]
Thanks for the support.
That did the trick.
I updated the repo and all builds with no issues and no need to unmask the latest versions.

Thanks,
N.
