### ISSUE TITLE
LDFLAGS="${LDFLAGS} -Wl,--relax" do not work for several packages

### ISSUE THREAD

**Issue by wmyrda** [gentoo-haskell/gentoo-haskell#704]
By default on my system I use following setup for the linker
```
LDFLAGS="-Wl,-O1 -Wl,--hash-style=both -Wl,--as-needed"
LDFLAGS="${LDFLAGS} -Wl,--relax"
LDFLAGS="${LDFLAGS} -Wl,--sort-common"
```
From about 1000 packages I have installed it didn't work for me only for glibc, grub and ocaml where `-Wl,--relax` is prohibited. Now using ::haskel I found a number of packages falling to link with that flag. They include following:
```
app-portage/hackport
dev-haskell/basement
dev-haskell/cryptohash-sha256
dev-haskell/foundation
dev-haskell/hackage-security
dev-haskell/persistent-sqlite
dev-haskell/unicode-transforms
dev-lang/ghc
```
I resolved it localy by editing package.env to filter that flag, but adding `flag-o-matic` to inherit seems like a better solution.

I am not sure would `filter-flags --relax` would be enough or `filter-flags  -Wl,--relax` should be used but either way seems easy to implement and useful.

**Comment by trofi** [comment]
If it's a rare failure then maybe it's an easy to address package-specific bug. Can you post example built.log of a failure?

**Comment by wmyrda** [comment]
It looks very similar for all those packages. For bigger once it just happens later.

> emerge -1 dev-haskell/cryptohash-sha256
> Calculating dependencies... done!
> 
> >>> Verifying ebuild manifests
> 
> >>> Emerging (1 of 1) dev-haskell/cryptohash-sha256-0.11.101.0::haskell
>  * cryptohash-sha256-0.11.101.0.tar.gz BLAKE2B SHA512 size ;-) ...                                                                                                                                          [ ok ]
> >>> Unpacking source...
> >>> Unpacking cryptohash-sha256-0.11.101.0.tar.gz to /tmp/portage/dev-haskell/cryptohash-sha256-0.11.101.0/work
> >>> Source unpacked in /tmp/portage/dev-haskell/cryptohash-sha256-0.11.101.0/work
> >>> Preparing source in /tmp/portage/dev-haskell/cryptohash-sha256-0.11.101.0/work/cryptohash-sha256-0.11.101.0 ...
>  * CHDEP: 'base             >= 4.5   && < 4.11' -> 'base             >= 4.5'
>  * CHDEP: 'tasty             == 0.11.*' -> 'tasty             >= 0.11'
>  * CHDEP: 'tasty-quickcheck  == 0.8.*' -> 'tasty-quickcheck  >= 0.8'
>  * CHDEP: 'tasty-hunit       == 0.9.*' -> 'tasty-hunit       >= 0.9'
> >>> Source prepared.
> >>> Configuring source in /tmp/portage/dev-haskell/cryptohash-sha256-0.11.101.0/work/cryptohash-sha256-0.11.101.0 ...
>  * Using cabal-1.24.2.0.
>  * Prepending /usr/lib64/ghc-8.0.2 to LD_LIBRARY_PATH
> /usr/bin/ghc -package Cabal-1.24.2.0 --make /tmp/portage/dev-haskell/cryptohash-sha256-0.11.101.0/work/cryptohash-sha256-0.11.101.0/Setup.hs -j5 +RTS -A256M -qb0 -RTS -threaded -dynamic -o setup
> [1 of 1] Compiling Main             ( /tmp/portage/dev-haskell/cryptohash-sha256-0.11.101.0/work/cryptohash-sha256-0.11.101.0/Setup.hs, /tmp/portage/dev-haskell/cryptohash-sha256-0.11.101.0/work/cryptohash-sha256-0.11.101.0/Setup.o )
> Linking setup ...
> ./setup configure --ghc --prefix=/usr --with-compiler=/usr/bin/ghc --with-hc-pkg=/usr/bin/ghc-pkg --prefix=/usr --libdir=/usr/lib64 --libsubdir=cryptohash-sha256-0.11.101.0/ghc-8.0.2 --datadir=/usr/share/ --datasubdir=cryptohash-sha256-0.11.101.0/ghc-8.0.2 --disable-tests --ghc-options=-j5 +RTS -A256M -qb0 -RTS --with-ar=x86_64-pc-linux-gnu-ar --ghc-option=-optc-march=native --ghc-option=-optc-O2 --ghc-option=-optc-pipe --ghc-option=-optc-fgcse-sm --ghc-option=-optc-fgcse-las --ghc-option=-optc-fgcse-after-reload --ghc-option=-optc-ftree-vectorize --ghc-option=-optl-Wl,-O1 --ghc-option=-optl-Wl,--hash-style=both --ghc-option=-optl-Wl,--as-needed --ghc-option=-optl-Wl,--relax --ghc-option=-optl-Wl,--sort-common --disable-executable-stripping --docdir=/usr/share/doc/cryptohash-sha256-0.11.101.0 --verbose --enable-shared --enable-executable-dynamic --sysconfdir=/etc --disable-library-stripping --flag=-exe
> Configuring cryptohash-sha256-0.11.101.0...
> Flags chosen: exe=False
> Dependency base >=4.5: using base-4.9.1.0
> Dependency bytestring >=0.9.2 && <0.11: using bytestring-0.10.8.1
> Using Cabal-1.24.2.0 compiled by ghc-8.0
> Using compiler: ghc-8.0.2
> Using install prefix: /usr
> Binaries installed in: /usr/bin
> Libraries installed in: /usr/lib64/cryptohash-sha256-0.11.101.0/ghc-8.0.2
> Dynamic libraries installed in: /usr/lib64/x86_64-linux-ghc-8.0.2
> Private binaries installed in: /usr/libexec
> Data files installed in: /usr/share/cryptohash-sha256-0.11.101.0/ghc-8.0.2
> Documentation installed in: /usr/share/doc/cryptohash-sha256-0.11.101.0
> Configuration files installed in: /etc
> No alex found
> Using ar given by user at: /usr/bin/x86_64-pc-linux-gnu-ar
> No c2hs found
> No cpphs found
> Using gcc version 7.3.0 found on system at: /usr/bin/x86_64-pc-linux-gnu-gcc
> Using ghc version 8.0.2 given by user at: /usr/bin/ghc
> Using ghc-pkg version 8.0.2 given by user at: /usr/bin/ghc-pkg
> No ghcjs found
> No ghcjs-pkg found
> No greencard found
> Using haddock version 2.17.3 found on system at: /usr/bin/haddock-ghc-8.0.2
> No happy found
> Using haskell-suite found on system at: haskell-suite-dummy-location
> Using haskell-suite-pkg found on system at: haskell-suite-pkg-dummy-location
> No hmake found
> Using hpc version 0.67 found on system at: /usr/bin/hpc
> Using hsc2hs version 0.68.1 found on system at: /usr/bin/hsc2hs
> No hscolour found
> No jhc found
> Using ld found on system at: /usr/bin/x86_64-pc-linux-gnu-ld
> No lhc found
> No lhc-pkg found
> Using pkg-config version 0.29.2 found on system at: /usr/bin/pkg-config
> Using strip version 2.30 found on system at: /usr/bin/strip
> Using tar found on system at: /bin/tar
> No uhc found
> >>> Source configured.
> >>> Compiling source in /tmp/portage/dev-haskell/cryptohash-sha256-0.11.101.0/work/cryptohash-sha256-0.11.101.0 ...
> ./setup build
> Building cryptohash-sha256-0.11.101.0...
> Preprocessing library cryptohash-sha256-0.11.101.0...
> [1 of 2] Compiling Crypto.Hash.SHA256.FFI ( src/Crypto/Hash/SHA256/FFI.hs, dist/build/Crypto/Hash/SHA256/FFI.o )
> /usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: --relax and -r may not be used together
> collect2: error: ld returned 1 exit status
> 
> <no location info>: error:
>     `x86_64-pc-linux-gnu-gcc' failed in phase `Linker'. (Exit code: 1)
>  * ERROR: dev-haskell/cryptohash-sha256-0.11.101.0::haskell failed (compile phase):
>  *   setup build failed
>  * 
>  * Call stack:
>  *     ebuild.sh, line  124:  Called src_compile
>  *   environment, line 2746:  Called haskell-cabal_src_compile
>  *   environment, line 1944:  Called cabal_src_compile
>  *   environment, line  661:  Called cabal-build
>  *   environment, line  419:  Called die
>  * The specific snippet of code:
>  *       ./setup "$@" || die "setup build failed"
>  * 
>  * If you need support, post the output of `emerge --info '=dev-haskell/cryptohash-sha256-0.11.101.0::haskell'`,
>  * the complete build log and the output of `emerge -pqv '=dev-haskell/cryptohash-sha256-0.11.101.0::haskell'`.
>  * The complete build log is located at '/tmp/logs/dev-haskell:cryptohash-sha256-0.11.101.0:20180424-194342.log'.
>  * For convenience, a symlink to the build log is located at '/tmp/portage/dev-haskell/cryptohash-sha256-0.11.101.0/temp/build.log'.
>  * The ebuild environment file is located at '/tmp/portage/dev-haskell/cryptohash-sha256-0.11.101.0/temp/environment'.
>  * Working directory: '/tmp/portage/dev-haskell/cryptohash-sha256-0.11.101.0/work/cryptohash-sha256-0.11.101.0'
>  * S: '/tmp/portage/dev-haskell/cryptohash-sha256-0.11.101.0/work/cryptohash-sha256-0.11.101.0'
> 
> >>> Failed to emerge dev-haskell/cryptohash-sha256-0.11.101.0

**Comment by wmyrda** [comment]
and yes enabling it only for affected packages should be enough as about 100 other packages installed just fine.

**Comment by trofi** [comment]
> [1 of 2] Compiling Crypto.Hash.SHA256.FFI ( src/Crypto/Hash/SHA256/FFI.hs, dist/build/Crypto/Hash/SHA256/FFI.o )
> /usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: --relax and -r may not be used together
> collect2: error: ld returned 1 exit status

This happens because internally `GHC` uses partial linking for files with `foreign import capi` declarations like

```haskell
foreign import capi unsafe "hs_sha256.h hs_cryptohash_sha256_init"
    c_sha256_init :: Ptr Ctx -> IO ()
```

This causes `ghc` to generate two object files: `.hs -> .o`, `stub.c -> o` and then partially link them together with `ld -r`. `ld -r` is not compatible with `-Wl,--relax` option. Which makes sense given that `--relax` is a global optimizer.

It does not sound maintainable to track down each linker flag and silently rip it off `LDFLAGS`. `ghc` might be a better place to try to fix it.

ghc's driver joins objects around here: https://github.com/ghc/ghc/blob/master/compiler/main/DriverPipeline.hs#L2134 . Looks like flag precedence here is already in order.

```haskell
                     ++ (if platformArch (targetPlatform dflags)
                                `elem` [ArchSPARC, ArchSPARC64]
                         && ldIsGnuLd
                            then [SysTools.Option "-Wl,-no-relax"]
else [])
```

You can try something like that instead:

```haskell
                     ++ (if ldIsGnuLd then [SysTools.Option "-Wl,-no-relax"] else [])
```

**Comment by trofi** [comment]
Pushed the patch to `ghc-8.0.2` and above: https://github.com/gentoo-haskell/gentoo-haskell/commit/872551a1b333e8677b78a0852a88e3585a0e04fc

Please try to rebuild ghc and verify if it works now.

**Comment by wmyrda** [comment]
After removing special setting for those ebuilds from /etc/portage/package.env I compile tested 
`dev-haskell/cryptohash-sha256 `and `dev-haskell/foundation`. They both emerged just fine, so I can confirm patch is working.

**Comment by trofi** [comment]
Proposed the change upstream as https://phabricator.haskell.org/D4888

**Comment by trofi** [comment]
https://gitlab.haskell.org/ghc/ghc/-/commit/53ce0db5a06598c88c6b8cb32043b878e7083dd4 removed -no-relax option upstream. Dropping the tracking downstream.

**Comment by trofi** [comment]
https://sourceware.org/PR27837 should make binutils more tolerant to `-r` / `--relax` mix.
