### ISSUE TITLE
[dev-haskell/stack-1.5.1-r4::haskell] Issue using lts-11.9 resolver

### ISSUE THREAD

**Issue by dyamon** [gentoo-haskell/gentoo-haskell#712]
### Issue
Running `stack new <project> -resolver 11.9` results in the following:
```
Downloading lts-11.9 build plan ...
Downloaded lts-11.9 build plan.
AesonException "Error in $.packages.cassava.constraints.flags[bytestring--lt-0_10_4]: Invalid flag name: \"bytestring--lt-0_10_4\""
```
### How to reproduce
1. Emerge `dev-haskell/stack-1.5.1-r4::haskell` with USE flags `doc hoogle hscolour -profile`;
2. Run `stack new <project> -resolver 11.9`
### Additional info
* Resolver 9.21 does not lead to the same issue; it seems like any resolver >9.21 cause the error;
* As suggested in #gentoo-haskell using `dev-haskell/stack-bin-1.6.1::haskell` does not give any problem.

**Comment by waivio** [comment]
I ran into this issue and then a follow on issue with the newer ghc>8.0.2.
I had to upgrade to a more recent stack version like 1.7.1 and then run with a local stack: ~/.local/bin/stack 
I also had to rebuild ncurses with use flag `sys-libs/ncurses tinfo` as described in the [gentoo sub bullet in stack's install and upgrade guide](https://docs.haskellstack.org/en/stable/install_and_upgrade/)

**Comment by solpeth** [comment]
@dyamon `stack-1.7.1` is now available in ::haskell. If you've had the chance to upgrade, could you please tell me if this problem persists?

**Comment by solpeth** [comment]
`stack-1.7.1` has been available for a while now, and it appears to have resolved this issue. Closing.

**Comment by dyamon** [comment]
Hi, sorry for the delayed answer. Yes, the issue is resolved, thank you.
