### ISSUE TITLE
pandoc-2.2.1 incorrect yaml dependency

### ISSUE THREAD

**Issue by tgbugs** [gentoo-haskell/gentoo-haskell#725]
The minimum yaml dependency on [this line](https://github.com/gentoo-haskell/gentoo-haskell/blob/master/app-text/pandoc/pandoc-2.2.1.ebuild#L60) is greater than 0.8.8.2 but I do not know what the correct minimum version is.
Cross referencing these issues here.
https://github.com/jgm/pandoc/issues/4726
https://bugs.gentoo.org/645082

**Comment by trofi** [comment]
`yaml-0.8.81` is very old version. `::gentoo` and `::haskell` don't provide it. Do you still have this version installed?

**Comment by tgbugs** [comment]
No, I had yaml-0.8.10.1 installed, which was not sufficiently up to date.

**Comment by trofi** [comment]
Oh, right. I was confused by https://github.com/jgm/pandoc/commit/adbaaeaf9b8153568de3d9426e3bce968b583235 which did set lower bound to version you are running. Which means the lower bound is still incorrect.
