### ISSUE TITLE
fsnotify-0.2.1.1 fails to compile

### ISSUE THREAD

**Issue by kandiyohi** [gentoo-haskell/gentoo-haskell#758]
[fsnotify-0.2.1.1.build.log](https://github.com/gentoo-haskell/gentoo-haskell/files/2259760/fsnotify-0.2.1.1.build.log)
[fsnotify-0.2.1.1.pqv.log](https://github.com/gentoo-haskell/gentoo-haskell/files/2259761/fsnotify-0.2.1.1.pqv.log)
[fsnotify-0.2.1.1.info.log](https://github.com/gentoo-haskell/gentoo-haskell/files/2259762/fsnotify-0.2.1.1.info.log)

I'm not sure how to begin debugging this.  I'll play around and see what comes up.  This was on the way to trying to install idris, so I don't know how well that set of packages has really been tested.

**Comment by kandiyohi** [comment]
Looks like the hinotify patch is causing the failure.  It seems like several parts of the path are unneeded now, because that's what's causing the types clash.

**Comment by trofi** [comment]
Your build log uses `Dependency hinotify >=0.3.7: using hinotify-0.3.8.1`. Overlay has `0.3.10` as latest version. I think we need to increase lower bound of a depend.
