### ISSUE TITLE
Insecure RUNPATH QA warnings from portage

### ISSUE THREAD

**Issue by hololeap** [gentoo-haskell/gentoo-haskell#799]
It looks like Haskell packages that expose a binary are getting caught by portage's QA system:

    QA Notice: The following files contain insecure RUNPATHs                        
     Please file a bug about this at https://bugs.gentoo.org/                       
     with the maintainer of the package.                                            
      /var/tmp/portage/dev-haskell/hscolour-1.24.4/image/usr/bin/HsColour           
        RPATH: /usr/lib64/ghc-8.4.3/array-0.5.2.0:/usr/lib64/ghc-8.4.3/base-4.11.1.0:/usr/lib64/ghc-8.4.3/containers-0.5.11.0:/usr/lib64/ghc-8.4.3/deepseq-1.4.3.0:/usr/lib64/ghc-8.4.3/ghc-prim-0.5.2.0:/var/tmp/portage/dev-haskell/hscolour-1.24.4/work/hscolour-1.24.4/dist/build:/usr/lib64/ghc-8.4.3/integer-gmp-1.0.2.0:/usr/lib64/ghc-8.4.3/rts

Interestingly, `readelf` shows that this path is sanitized at some point by portage:

    # readelf -a /usr/bin/HsColour | grep 'var/tmp'
    # 
    # readelf -d /usr/bin/HsColour | grep -i PATH                       
     0x000000000000001d (RUNPATH)            Library runpath: [/usr/lib64/ghc-8.4.3/array-0.5.2.0:/usr/lib64/ghc-8.4.3/base-4.11.1.0:/usr/lib64/ghc-8.4.3/containers-0.5.11.0:/usr/lib64/ghc-8.4.3/deepseq-1.4.3.0:/usr/lib64/ghc-8.4.3/ghc-prim-0.5.2.0:/usr/lib64/ghc-8.4.3/integer-gmp-1.0.2.0:/usr/lib64/ghc-8.4.3/rts]

**Comment by hololeap** [comment]
This ticket appears to be relevant, although it was closed a while back:

https://github.com/haskell/cabal/issues/4025

**Comment by trofi** [comment]
I briefly tried `ghc-9999` and `hscolour`. The issue is still there.

I think it's reintroduction of https://github.com/haskell/cabal/issues/4025 , yes. Will try to build cabal-head again and report upstream.

**Comment by hololeap** [comment]
I haven't run into this in a while so I'm going to say it's resolved.

**Comment by solpeth** [comment]
This is still present with `ghc-8.6.3` and `hscolour`.

**Comment by trofi** [comment]
Filed upstream https://github.com/haskell/cabal/issues/7109

**Comment by hololeap** [comment]
I'm getting this now for [`hackport`](https://github.com/gentoo-haskell/hackport) as of [06fc0fbb99dcf29fea7683bb9d792df36fe952cd](https://github.com/gentoo-haskell/hackport/commit/06fc0fbb99dcf29fea7683bb9d792df36fe952cd).

```
 * Messages for package app-portage/hackport-9999:

 * Using EGIT_OVERRIDE_REPO_GENTOO_HASKELL_HACKPORT=https://github.com/hololeap/hackport
 * No support will be provided.
 * QA Notice: The following files contain insecure RUNPATHs
 *  Please file a bug about this at https://bugs.gentoo.org/
 *  with the maintainer of the package.
 *   /var/tmp/portage/app-portage/hackport-9999/image/usr/lib64/x86_64-linux-ghc-9.0.2/libHShackport-0.7.1.1.9999-6acToIgQuhm4WqVSXdvIk2-hackport-internal-ghc9.0.2.son    RPATH: /usr/lib64/ghc-9.0.2/Cabal-3.4.1.0:/usr/lib64/ghc-9.0.2/array-0.5.4.0:/usr/lib64/ghc-9.0.2/base-4.15.1.0:/usr/lib64/ghc-9.0.2/binary-0.8.8.0:/usr/lib64/ghc-9.0.2/bytestring-0.10.12.1:/usr/lib64/ghc-9.0.2/containers-0.6.4.1:/usr/lib64/ghc-9.0.2/deepseq-1.4.5.0:/usr/lib64/ghc-9.0.2/directory-1.3.6.2:/usr/lib64/ghc-9.0.2/exceptions-0.10.4:/usr/lib64/ghc-9.0.2/filepath-1.4.2.1:/usr/lib64/ghc-9.0.2/ghc-9.0.2:/usr/lib64/ghc-9.0.2/ghc-bignum-1.1:/usr/lib64/ghc-9.0.2/ghc-boot-9.0.2:/usr/lib64/ghc-9.0.2/ghc-boot-th-9.0.2:/usr/lib64/ghc-9.0.2/ghc-heap-9.0.2:/usr/lib64/ghc-9.0.2/ghc-prim-0.7.0:/usr/lib64/ghc-9.0.2/ghci-9.0.2:/var/tmp/portage/app-portage/hackport-9999/work/hackport-9999/dist/build/hackport-external-libs-hackage-security:/usr/lib64/ghc-9.0.2/hpc-0.6.1.0:/usr/lib64/ghc-9.0.2/mtl-2.2.2:/usr/lib64/ghc-9.0.2/parsec-3.1.14.0:/usr/lib64/ghc-9.0.2/pretty-1.1.3.6:/usr/lib64/ghc-9.0.2/process-1.6.13.2:/usr/lib64/ghc-9.0.2/rts:/usr/lib64/ghc-9.0.2/stm-2.5.0.0:/usr/lib64/ghc-9.0.2/template-haskell-2.17.0.0:/usr/lib64/ghc-9.0.2/terminfo-0.4.1.5:/usr/lib64/ghc-9.0.2/text-1.2.5.0:/usr/lib64/ghc-9.0.2/time-1.9.3:/usr/lib64/ghc-9.0.2/transformers-0.5.6.2:/usr/lib64/ghc-9.0.2/unix-2.7.2.2:/usr/lib64/x86_64-linux-ghc-9.0.2
 *   /var/tmp/portage/app-portage/hackport-9999/image/usr/bin/hackportn    RPATH: /usr/lib64/ghc-9.0.2/Cabal-3.4.1.0:/usr/lib64/ghc-9.0.2/array-0.5.4.0:/usr/lib64/ghc-9.0.2/base-4.15.1.0:/usr/lib64/ghc-9.0.2/binary-0.8.8.0:/usr/lib64/ghc-9.0.2/bytestring-0.10.12.1:/usr/lib64/ghc-9.0.2/containers-0.6.4.1:/usr/lib64/ghc-9.0.2/deepseq-1.4.5.0:/usr/lib64/ghc-9.0.2/directory-1.3.6.2:/usr/lib64/ghc-9.0.2/exceptions-0.10.4:/usr/lib64/ghc-9.0.2/filepath-1.4.2.1:/usr/lib64/ghc-9.0.2/ghc-9.0.2:/usr/lib64/ghc-9.0.2/ghc-bignum-1.1:/usr/lib64/ghc-9.0.2/ghc-boot-9.0.2:/usr/lib64/ghc-9.0.2/ghc-boot-th-9.0.2:/usr/lib64/ghc-9.0.2/ghc-heap-9.0.2:/usr/lib64/ghc-9.0.2/ghc-prim-0.7.0:/usr/lib64/ghc-9.0.2/ghci-9.0.2:/var/tmp/portage/app-portage/hackport-9999/work/hackport-9999/dist/build/hackport-external-libs-hackage-security:/usr/lib64/ghc-9.0.2/hpc-0.6.1.0:/usr/lib64/ghc-9.0.2/mtl-2.2.2:/usr/lib64/ghc-9.0.2/parsec-3.1.14.0:/usr/lib64/ghc-9.0.2/pretty-1.1.3.6:/usr/lib64/ghc-9.0.2/process-1.6.13.2:/usr/lib64/ghc-9.0.2/rts:/usr/lib64/ghc-9.0.2/stm-2.5.0.0:/usr/lib64/ghc-9.0.2/template-haskell-2.17.0.0:/usr/lib64/ghc-9.0.2/terminfo-0.4.1.5:/usr/lib64/ghc-9.0.2/text-1.2.5.0:/usr/lib64/ghc-9.0.2/time-1.9.3:/usr/lib64/ghc-9.0.2/transformers-0.5.6.2:/usr/lib64/ghc-9.0.2/unix-2.7.2.2:/usr/lib64/x86_64-linux-ghc-9.0.2
```

This seemed to be introduced by using [internal libraries](https://cabal.readthedocs.io/en/3.4/cabal-package.html#sublibs) to help try to better organize the project.

I'm not sure if this is related to https://github.com/haskell/cabal/issues/7109 or not.
