### ISSUE TITLE
hashable-1.2.7.0 build failed with USE="profile"

### ISSUE THREAD

**Issue by Vonfry** [gentoo-haskell/gentoo-haskell#818]
`dev-haskell/hashable-1.2.7.0` with `USE=profile`  is built failed. 

Build log, emerge info, environment and others,  please see [gist](https://gist.github.com/Vonfry/0bd740681a225bd15d8825e322d2c336)

By the way, this is depended by cabal with `USE="profile"`. 

Cabal can be built successfully without `profile`

**Comment by contrun** [comment]
Can anyone clarify how to solve this problem? I just encountered the same problem as OP's.

**Comment by trofi** [comment]
You need to rebuild ghc with USE=profile

**Comment by trofi** [comment]
That is unexpected. Can you post your full build log?

**Comment by trofi** [comment]
Can you also post your `emerge --info dev-lang/ghc`?

**Comment by trofi** [comment]
Also make sure you have profiling libraries installed:
```
$qlist dev-lang/ghc | fgrep Data/String.p_hi
/usr/lib64/ghc-8.4.4/base-4.11.1.0/Data/String.p_hi
```

If they are missing on your system we'll need to check ghc's build.log to get the idea why they are missing.

**Comment by contrun** [comment]
Here is my `emerge --info dev-lang/ghc`

[Paste #WXtleoNYspSAyi3njWa4 at spacepaste](https://paste.pound-python.org/show/WXtleoNYspSAyi3njWa4/)

I have tried `emerge --ask -e -DUNv dev-lang/ghc` a few times. On my machine, it actually downloads a binary and unpacks it. So I have no way to know how `ghc` is built.

Here is the emerge log.

[Paste #5CbVdBHLztbKUfYclQ9u at spacepaste](https://paste.pound-python.org/show/5CbVdBHLztbKUfYclQ9u/)

**Comment by trofi** [comment]
Yeah, USE=binary makes sense. I'll expand USE restricts to disallow USE="binary profile".
