### ISSUE TITLE
Please add super-user-spark to gentoo-haskell

### ISSUE THREAD

**Issue by Jemi** [gentoo-haskell/gentoo-haskell#823]
While searching for a way to deploy my dotfiles I ended up trying out a number of different solutions that seemed half-baked, and then I came upon this:

https://github.com/NorfairKing/super-user-spark

This looks to be a well architected and innovative solution to the problem of dotfile deployment. If it lives up to its promise --as it looks like it should-- then it should definitely be in gentoo-haskell.

I spent some time trying to figure out how to use hackport to generate ebuilds for super-user-spark, and I've been successful, at least insofar as the ebuilds are able to install the packages in question, although these ebuilds strangely cause repoman to complain about bad dependencies.  I'm probably doing something wrong, but even without experience with haskell or hackports I've been able get working ebuilds. If the devs here could produce ebuilds for this that actually pass muster, I think this program could end up being a boon to the gentoo community.

**Comment by trofi** [comment]
You can also show result of your work and I can try to help to make repoman happy.

**Comment by Jemi** [comment]
super-user-spark-0.4.0.0.ebuild - This was generated by 'hackport merge super-user-spark'. The dependencies, like genvalidity-0.3.2.0, genvalidity-hspec-0.3.1.0, iostring-0.0.0.0, and genvalidity-hspec-aeson-0.0.1.1, were created the same way only specifying specific version numbers that I found using the hackage online search tool. 
```

# Copyright 1999-2018 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

EAPI=6

# ebuild generated by hackport 0.5.5

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="Configure your dotfile deployment with a DSL"
HOMEPAGE="http://hackage.haskell.org/package/super-user-spark"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="MIT"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/aeson-0.11:=[profile?] <dev-haskell/aeson-1.2:=[profile?]
	>=dev-haskell/aeson-pretty-0.8:=[profile?] <dev-haskell/aeson-pretty-0.9:=[profile?]
	>=dev-haskell/hashable-1.2:=[profile?] <dev-haskell/hashable-1.3:=[profile?]
	>=dev-haskell/iostring-0.0:=[profile?] <dev-haskell/iostring-0.1:=[profile?]
	>=dev-haskell/mtl-2.2:=[profile?] <dev-haskell/mtl-2.3:=[profile?]
	>=dev-haskell/optparse-applicative-0.13:=[profile?] <dev-haskell/optparse-applicative-0.14:=[profile?]
	>=dev-haskell/parsec-3.1.9:=[profile?] <dev-haskell/parsec-3.2:=[profile?]
	>=dev-haskell/path-0.5:=[profile?] <dev-haskell/path-0.6:=[profile?]
	>=dev-haskell/path-io-1.2:=[profile?] <dev-haskell/path-io-1.3:=[profile?]
	>=dev-haskell/text-1.2:=[profile?] <dev-haskell/text-1.3:=[profile?]
	>=dev-haskell/validity-0.3.2:=[profile?] <dev-haskell/validity-0.4:=[profile?]
	>=dev-haskell/validity-path-0.1:=[profile?] <dev-haskell/validity-path-0.2:=[profile?]
	>=dev-lang/ghc-8.0.2:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.24.2.0
	test? ( >=dev-haskell/genvalidity-0.3.1 <dev-haskell/genvalidity-0.4
		>=dev-haskell/genvalidity-hspec-0.3.1 <dev-haskell/genvalidity-hspec-0.4
		>=dev-haskell/genvalidity-hspec-aeson-0.0 <dev-haskell/genvalidity-hspec-aeson-0.1
		>=dev-haskell/genvalidity-path-0.1 <dev-haskell/genvalidity-path-0.2
		>=dev-haskell/hspec-2.2 <dev-haskell/hspec-2.5
		>=dev-haskell/hspec-core-2.2 <dev-haskell/hspec-core-2.5
		>=dev-haskell/hunit-1.2 <dev-haskell/hunit-1.6
		>=dev-haskell/quickcheck-2.8 <dev-haskell/quickcheck-2.10 )
"
```

**Comment by Jemi** [comment]
This is the output repoman produces when called as 'repoman --include-dev' from /usr/local/portage/app-admin/super-user-spark:

RepoMan scours the neighborhood...
  dependency.bad [fatal]        62
   app-admin/super-user-spark/super-user-spark-0.4.0.0.ebuild: DEPEND: ~amd64(default/linux/amd64/17.0)
[     '<dev-haskell/validity-0.4:=[profile?]',
      '<dev-haskell/validity-path-0.2:=[profile?]',
      '>=dev-haskell/genvalidity-path-0.1',
      '<dev-haskell/genvalidity-path-0.2']
   app-admin/super-user-spark/super-user-spark-0.4.0.0.ebuild: RDEPEND: ~amd64(default/linux/amd64/17.0)
[     '<dev-haskell/validity-0.4:=[profile?]',
      '<dev-haskell/validity-path-0.2:=[profile?]']
   app-admin/super-user-spark/super-user-spark-0.4.0.0.ebuild: DEPEND: ~amd64(default/linux/amd64/17.0/desktop)
[     '<dev-haskell/validity-0.4:=[profile?]',
      '<dev-haskell/validity-path-0.2:=[profile?]',
      '>=dev-haskell/genvalidity-path-0.1',
      '<dev-haskell/genvalidity-path-0.2']
   app-admin/super-user-spark/super-user-spark-0.4.0.0.ebuild: RDEPEND: ~amd64(default/linux/amd64/17.0/desktop)
[     '<dev-haskell/validity-0.4:=[profile?]',
      '<dev-haskell/validity-path-0.2:=[profile?]']
   app-admin/super-user-spark/super-user-spark-0.4.0.0.ebuild: DEPEND: ~amd64(default/linux/amd64/17.0/desktop/gnome)
[     '<dev-haskell/validity-0.4:=[profile?]',
      '<dev-haskell/validity-path-0.2:=[profile?]',
      '>=dev-haskell/genvalidity-path-0.1',
      '<dev-haskell/genvalidity-path-0.2']
   app-admin/super-user-spark/super-user-spark-0.4.0.0.ebuild: RDEPEND: ~amd64(default/linux/amd64/17.0/desktop/gnome)
[     '<dev-haskell/validity-0.4:=[profile?]',
      '<dev-haskell/validity-path-0.2:=[profile?]']
   app-admin/super-user-spark/super-user-spark-0.4.0.0.ebuild: DEPEND: ~amd64(default/linux/amd64/17.0/desktop/gnome/systemd)
[     '<dev-haskell/validity-0.4:=[profile?]',
      '<dev-haskell/validity-path-0.2:=[profile?]',
      '>=dev-haskell/genvalidity-path-0.1',
      '<dev-haskell/genvalidity-path-0.2']
   app-admin/super-user-spark/super-user-spark-0.4.0.0.ebuild: RDEPEND: ~amd64(default/linux/amd64/17.0/desktop/gnome/systemd)
[     '<dev-haskell/validity-0.4:=[profile?]',
      '<dev-haskell/validity-path-0.2:=[profile?]']
   app-admin/super-user-spark/super-user-spark-0.4.0.0.ebuild: DEPEND: ~amd64(default/linux/amd64/17.0/desktop/plasma)
[     '<dev-haskell/validity-0.4:=[profile?]',
      '<dev-haskell/validity-path-0.2:=[profile?]',
      '>=dev-haskell/genvalidity-path-0.1',
      '<dev-haskell/genvalidity-path-0.2']
   app-admin/super-user-spark/super-user-spark-0.4.0.0.ebuild: RDEPEND: ~amd64(default/linux/amd64/17.0/desktop/plasma)
[     '<dev-haskell/validity-0.4:=[profile?]',
      '<dev-haskell/validity-path-0.2:=[profile?]']
   app-admin/super-user-spark/super-user-spark-0.4.0.0.ebuild: DEPEND: ~amd64(default/linux/amd64/17.0/desktop/plasma/systemd)
[     '<dev-haskell/validity-0.4:=[profile?]',
      '<dev-haskell/validity-path-0.2:=[profile?]',
      '>=dev-haskell/genvalidity-path-0.1',
      '<dev-haskell/genvalidity-path-0.2']
   app-admin/super-user-spark/super-user-spark-0.4.0.0.ebuild: RDEPEND: ~amd64(default/linux/amd64/17.0/desktop/plasma/systemd)
[     '<dev-haskell/validity-0.4:=[profile?]',
      '<dev-haskell/validity-path-0.2:=[profile?]']
   app-admin/super-user-spark/super-user-spark-0.4.0.0.ebuild: DEPEND: ~amd64(default/linux/amd64/17.0/developer)
[     '<dev-haskell/validity-0.4:=[profile?]',
      '<dev-haskell/validity-path-0.2:=[profile?]',
      '>=dev-haskell/genvalidity-path-0.1',
      '<dev-haskell/genvalidity-path-0.2']
   app-admin/super-user-spark/super-user-spark-0.4.0.0.ebuild: RDEPEND: ~amd64(default/linux/amd64/17.0/developer)
[     '<dev-haskell/validity-0.4:=[profile?]',
      '<dev-haskell/validity-path-0.2:=[profile?]']
   app-admin/super-user-spark/super-user-spark-0.4.0.0.ebuild: DEPEND: ~amd64(default/linux/amd64/17.0/hardened)
[     '<dev-haskell/validity-0.4:=[profile?]',
      '<dev-haskell/validity-path-0.2:=[profile?]',
      '>=dev-haskell/genvalidity-path-0.1',
      '<dev-haskell/genvalidity-path-0.2']
   app-admin/super-user-spark/super-user-spark-0.4.0.0.ebuild: RDEPEND: ~amd64(default/linux/amd64/17.0/hardened)
[     '<dev-haskell/validity-0.4:=[profile?]',
      '<dev-haskell/validity-path-0.2:=[profile?]']
   app-admin/super-user-spark/super-user-spark-0.4.0.0.ebuild: DEPEND: ~amd64(default/linux/amd64/17.0/hardened/selinux)
[     '<dev-haskell/validity-0.4:=[profile?]',
      '<dev-haskell/validity-path-0.2:=[profile?]',
      '>=dev-haskell/genvalidity-path-0.1',
      '<dev-haskell/genvalidity-path-0.2']
   app-admin/super-user-spark/super-user-spark-0.4.0.0.ebuild: RDEPEND: ~amd64(default/linux/amd64/17.0/hardened/selinux)
[     '<dev-haskell/validity-0.4:=[profile?]',
      '<dev-haskell/validity-path-0.2:=[profile?]']
   app-admin/super-user-spark/super-user-spark-0.4.0.0.ebuild: DEPEND: ~amd64(default/linux/amd64/17.0/no-multilib)
[     '<dev-haskell/validity-0.4:=[profile?]',
      '<dev-haskell/validity-path-0.2:=[profile?]',
      '>=dev-haskell/genvalidity-path-0.1',
      '<dev-haskell/genvalidity-path-0.2']
   app-admin/super-user-spark/super-user-spark-0.4.0.0.ebuild: RDEPEND: ~amd64(default/linux/amd64/17.0/no-multilib)
[     '<dev-haskell/validity-0.4:=[profile?]',
      '<dev-haskell/validity-path-0.2:=[profile?]']
   app-admin/super-user-spark/super-user-spark-0.4.0.0.ebuild: DEPEND: ~amd64(default/linux/amd64/17.0/no-multilib/hardened)
[     '<dev-haskell/validity-0.4:=[profile?]',
      '<dev-haskell/validity-path-0.2:=[profile?]',
      '>=dev-haskell/genvalidity-path-0.1',
      '<dev-haskell/genvalidity-path-0.2']
   app-admin/super-user-spark/super-user-spark-0.4.0.0.ebuild: RDEPEND: ~amd64(default/linux/amd64/17.0/no-multilib/hardened)
[     '<dev-haskell/validity-0.4:=[profile?]',
      '<dev-haskell/validity-path-0.2:=[profile?]']
   app-admin/super-user-spark/super-user-spark-0.4.0.0.ebuild: DEPEND: ~amd64(default/linux/amd64/17.0/no-multilib/hardened/selinux)
[     '<dev-haskell/validity-0.4:=[profile?]',
      '<dev-haskell/validity-path-0.2:=[profile?]',
      '>=dev-haskell/genvalidity-path-0.1',
      '<dev-haskell/genvalidity-path-0.2']
   app-admin/super-user-spark/super-user-spark-0.4.0.0.ebuild: RDEPEND: ~amd64(default/linux/amd64/17.0/no-multilib/hardened/selinux)
[     '<dev-haskell/validity-0.4:=[profile?]',
      '<dev-haskell/validity-path-0.2:=[profile?]']
   app-admin/super-user-spark/super-user-spark-0.4.0.0.ebuild: DEPEND: ~amd64(default/linux/amd64/17.0/selinux)
[     '<dev-haskell/validity-0.4:=[profile?]',
      '<dev-haskell/validity-path-0.2:=[profile?]',
      '>=dev-haskell/genvalidity-path-0.1',
      '<dev-haskell/genvalidity-path-0.2']
   app-admin/super-user-spark/super-user-spark-0.4.0.0.ebuild: RDEPEND: ~amd64(default/linux/amd64/17.0/selinux)
[     '<dev-haskell/validity-0.4:=[profile?]',
      '<dev-haskell/validity-path-0.2:=[profile?]']
   app-admin/super-user-spark/super-user-spark-0.4.0.0.ebuild: DEPEND: ~amd64(default/linux/amd64/17.0/systemd)
[     '<dev-haskell/validity-0.4:=[profile?]',
      '<dev-haskell/validity-path-0.2:=[profile?]',
      '>=dev-haskell/genvalidity-path-0.1',
      '<dev-haskell/genvalidity-path-0.2']
   app-admin/super-user-spark/super-user-spark-0.4.0.0.ebuild: RDEPEND: ~amd64(default/linux/amd64/17.0/systemd)
[     '<dev-haskell/validity-0.4:=[profile?]',
      '<dev-haskell/validity-path-0.2:=[profile?]']
   app-admin/super-user-spark/super-user-spark-0.4.0.0.ebuild: DEPEND: ~x86(default/linux/x86/17.0)
[     '<dev-haskell/validity-0.4:=[profile?]',
      '<dev-haskell/validity-path-0.2:=[profile?]',
      '>=dev-haskell/genvalidity-path-0.1',
      '<dev-haskell/genvalidity-path-0.2']
   app-admin/super-user-spark/super-user-spark-0.4.0.0.ebuild: RDEPEND: ~x86(default/linux/x86/17.0)
[     '<dev-haskell/validity-0.4:=[profile?]',
      '<dev-haskell/validity-path-0.2:=[profile?]']
   app-admin/super-user-spark/super-user-spark-0.4.0.0.ebuild: DEPEND: ~x86(default/linux/x86/17.0/desktop)
[     '<dev-haskell/validity-0.4:=[profile?]',
      '<dev-haskell/validity-path-0.2:=[profile?]',
      '>=dev-haskell/genvalidity-path-0.1',
      '<dev-haskell/genvalidity-path-0.2']
   app-admin/super-user-spark/super-user-spark-0.4.0.0.ebuild: RDEPEND: ~x86(default/linux/x86/17.0/desktop)
[     '<dev-haskell/validity-0.4:=[profile?]',
      '<dev-haskell/validity-path-0.2:=[profile?]']
   app-admin/super-user-spark/super-user-spark-0.4.0.0.ebuild: DEPEND: ~x86(default/linux/x86/17.0/desktop/gnome)
[     '<dev-haskell/validity-0.4:=[profile?]',
      '<dev-haskell/validity-path-0.2:=[profile?]',
      '>=dev-haskell/genvalidity-path-0.1',
      '<dev-haskell/genvalidity-path-0.2']
   app-admin/super-user-spark/super-user-spark-0.4.0.0.ebuild: RDEPEND: ~x86(default/linux/x86/17.0/desktop/gnome)
[     '<dev-haskell/validity-0.4:=[profile?]',
      '<dev-haskell/validity-path-0.2:=[profile?]']
   app-admin/super-user-spark/super-user-spark-0.4.0.0.ebuild: DEPEND: ~x86(default/linux/x86/17.0/desktop/gnome/systemd)
[     '<dev-haskell/validity-0.4:=[profile?]',
      '<dev-haskell/validity-path-0.2:=[profile?]',
      '>=dev-haskell/genvalidity-path-0.1',
      '<dev-haskell/genvalidity-path-0.2']
   app-admin/super-user-spark/super-user-spark-0.4.0.0.ebuild: RDEPEND: ~x86(default/linux/x86/17.0/desktop/gnome/systemd)
[     '<dev-haskell/validity-0.4:=[profile?]',
      '<dev-haskell/validity-path-0.2:=[profile?]']
   app-admin/super-user-spark/super-user-spark-0.4.0.0.ebuild: DEPEND: ~x86(default/linux/x86/17.0/desktop/plasma)
[     '<dev-haskell/validity-0.4:=[profile?]',
      '<dev-haskell/validity-path-0.2:=[profile?]',
      '>=dev-haskell/genvalidity-path-0.1',
      '<dev-haskell/genvalidity-path-0.2']
   app-admin/super-user-spark/super-user-spark-0.4.0.0.ebuild: RDEPEND: ~x86(default/linux/x86/17.0/desktop/plasma)
[     '<dev-haskell/validity-0.4:=[profile?]',
      '<dev-haskell/validity-path-0.2:=[profile?]']
   app-admin/super-user-spark/super-user-spark-0.4.0.0.ebuild: DEPEND: ~x86(default/linux/x86/17.0/desktop/plasma/systemd)
[     '<dev-haskell/validity-0.4:=[profile?]',
      '<dev-haskell/validity-path-0.2:=[profile?]',
      '>=dev-haskell/genvalidity-path-0.1',
      '<dev-haskell/genvalidity-path-0.2']
   app-admin/super-user-spark/super-user-spark-0.4.0.0.ebuild: RDEPEND: ~x86(default/linux/x86/17.0/desktop/plasma/systemd)
[     '<dev-haskell/validity-0.4:=[profile?]',
      '<dev-haskell/validity-path-0.2:=[profile?]']
   app-admin/super-user-spark/super-user-spark-0.4.0.0.ebuild: DEPEND: ~x86(default/linux/x86/17.0/developer)
[     '<dev-haskell/validity-0.4:=[profile?]',
      '<dev-haskell/validity-path-0.2:=[profile?]',
      '>=dev-haskell/genvalidity-path-0.1',
      '<dev-haskell/genvalidity-path-0.2']
   app-admin/super-user-spark/super-user-spark-0.4.0.0.ebuild: RDEPEND: ~x86(default/linux/x86/17.0/developer)
[     '<dev-haskell/validity-0.4:=[profile?]',
      '<dev-haskell/validity-path-0.2:=[profile?]']
   app-admin/super-user-spark/super-user-spark-0.4.0.0.ebuild: DEPEND: ~x86(default/linux/x86/17.0/hardened)
[     '<dev-haskell/validity-0.4:=[profile?]',
      '<dev-haskell/validity-path-0.2:=[profile?]',
      '>=dev-haskell/genvalidity-path-0.1',
      '<dev-haskell/genvalidity-path-0.2']
   app-admin/super-user-spark/super-user-spark-0.4.0.0.ebuild: RDEPEND: ~x86(default/linux/x86/17.0/hardened)
[     '<dev-haskell/validity-0.4:=[profile?]',
      '<dev-haskell/validity-path-0.2:=[profile?]']
   app-admin/super-user-spark/super-user-spark-0.4.0.0.ebuild: DEPEND: ~x86(default/linux/x86/17.0/hardened/selinux)
[     '<dev-haskell/validity-0.4:=[profile?]',
      '<dev-haskell/validity-path-0.2:=[profile?]',
      '>=dev-haskell/genvalidity-path-0.1',
      '<dev-haskell/genvalidity-path-0.2']
   app-admin/super-user-spark/super-user-spark-0.4.0.0.ebuild: RDEPEND: ~x86(default/linux/x86/17.0/hardened/selinux)
[     '<dev-haskell/validity-0.4:=[profile?]',
      '<dev-haskell/validity-path-0.2:=[profile?]']
   app-admin/super-user-spark/super-user-spark-0.4.0.0.ebuild: DEPEND: ~x86(default/linux/x86/17.0/selinux)
[     '<dev-haskell/validity-0.4:=[profile?]',
      '<dev-haskell/validity-path-0.2:=[profile?]',
      '>=dev-haskell/genvalidity-path-0.1',
      '<dev-haskell/genvalidity-path-0.2']
   app-admin/super-user-spark/super-user-spark-0.4.0.0.ebuild: RDEPEND: ~x86(default/linux/x86/17.0/selinux)
[     '<dev-haskell/validity-0.4:=[profile?]',
      '<dev-haskell/validity-path-0.2:=[profile?]']
   app-admin/super-user-spark/super-user-spark-0.4.0.0.ebuild: DEPEND: ~x86(default/linux/x86/17.0/systemd)
[     '<dev-haskell/validity-0.4:=[profile?]',
      '<dev-haskell/validity-path-0.2:=[profile?]',
      '>=dev-haskell/genvalidity-path-0.1',
      '<dev-haskell/genvalidity-path-0.2']
   app-admin/super-user-spark/super-user-spark-0.4.0.0.ebuild: RDEPEND: ~x86(default/linux/x86/17.0/systemd)
[     '<dev-haskell/validity-0.4:=[profile?]',
      '<dev-haskell/validity-path-0.2:=[profile?]']
   app-admin/super-user-spark/super-user-spark-0.4.0.0.ebuild: DEPEND: ~amd64(hardened/linux/amd64)
[     '<dev-haskell/validity-0.4:=[profile?]',
      '<dev-haskell/validity-path-0.2:=[profile?]',
      '>=dev-haskell/genvalidity-path-0.1',
      '<dev-haskell/genvalidity-path-0.2']
   app-admin/super-user-spark/super-user-spark-0.4.0.0.ebuild: RDEPEND: ~amd64(hardened/linux/amd64)
[     '<dev-haskell/validity-0.4:=[profile?]',
      '<dev-haskell/validity-path-0.2:=[profile?]']
   app-admin/super-user-spark/super-user-spark-0.4.0.0.ebuild: DEPEND: ~amd64(hardened/linux/amd64/no-multilib)
[     '<dev-haskell/validity-0.4:=[profile?]',
      '<dev-haskell/validity-path-0.2:=[profile?]',
      '>=dev-haskell/genvalidity-path-0.1',
      '<dev-haskell/genvalidity-path-0.2']
   app-admin/super-user-spark/super-user-spark-0.4.0.0.ebuild: RDEPEND: ~amd64(hardened/linux/amd64/no-multilib)
[     '<dev-haskell/validity-0.4:=[profile?]',
      '<dev-haskell/validity-path-0.2:=[profile?]']
   app-admin/super-user-spark/super-user-spark-0.4.0.0.ebuild: DEPEND: ~amd64(hardened/linux/amd64/no-multilib/selinux)
[     '<dev-haskell/validity-0.4:=[profile?]',
      '<dev-haskell/validity-path-0.2:=[profile?]',
      '>=dev-haskell/genvalidity-path-0.1',
      '<dev-haskell/genvalidity-path-0.2']
   app-admin/super-user-spark/super-user-spark-0.4.0.0.ebuild: RDEPEND: ~amd64(hardened/linux/amd64/no-multilib/selinux)
[     '<dev-haskell/validity-0.4:=[profile?]',
      '<dev-haskell/validity-path-0.2:=[profile?]']
   app-admin/super-user-spark/super-user-spark-0.4.0.0.ebuild: DEPEND: ~amd64(hardened/linux/amd64/selinux)
[     '<dev-haskell/validity-0.4:=[profile?]',
      '<dev-haskell/validity-path-0.2:=[profile?]',
      '>=dev-haskell/genvalidity-path-0.1',
      '<dev-haskell/genvalidity-path-0.2']
   app-admin/super-user-spark/super-user-spark-0.4.0.0.ebuild: RDEPEND: ~amd64(hardened/linux/amd64/selinux)
[     '<dev-haskell/validity-0.4:=[profile?]',
      '<dev-haskell/validity-path-0.2:=[profile?]']
   app-admin/super-user-spark/super-user-spark-0.4.0.0.ebuild: DEPEND: ~x86(hardened/linux/x86)
[     '<dev-haskell/validity-0.4:=[profile?]',
      '<dev-haskell/validity-path-0.2:=[profile?]',
      '>=dev-haskell/genvalidity-path-0.1',
      '<dev-haskell/genvalidity-path-0.2']
   app-admin/super-user-spark/super-user-spark-0.4.0.0.ebuild: RDEPEND: ~x86(hardened/linux/x86)
[     '<dev-haskell/validity-0.4:=[profile?]',
      '<dev-haskell/validity-path-0.2:=[profile?]']
   app-admin/super-user-spark/super-user-spark-0.4.0.0.ebuild: DEPEND: ~x86(hardened/linux/x86/selinux)
[     '<dev-haskell/validity-0.4:=[profile?]',
      '<dev-haskell/validity-path-0.2:=[profile?]',
      '>=dev-haskell/genvalidity-path-0.1',
      '<dev-haskell/genvalidity-path-0.2']
   app-admin/super-user-spark/super-user-spark-0.4.0.0.ebuild: RDEPEND: ~x86(hardened/linux/x86/selinux)
[     '<dev-haskell/validity-0.4:=[profile?]',
      '<dev-haskell/validity-path-0.2:=[profile?]']
  dependency.badindev           4
   app-admin/super-user-spark/super-user-spark-0.4.0.0.ebuild: DEPEND: ~amd64(default/linux/amd64/17.0/x32)
[     '<dev-haskell/validity-0.4:=[profile?]',
      '<dev-haskell/validity-path-0.2:=[profile?]',
      '>=dev-haskell/genvalidity-path-0.1',
      '<dev-haskell/genvalidity-path-0.2']
   app-admin/super-user-spark/super-user-spark-0.4.0.0.ebuild: RDEPEND: ~amd64(default/linux/amd64/17.0/x32)
[     '<dev-haskell/validity-0.4:=[profile?]',
      '<dev-haskell/validity-path-0.2:=[profile?]']
   app-admin/super-user-spark/super-user-spark-0.4.0.0.ebuild: DEPEND: ~amd64(hardened/linux/amd64/x32)
[     '<dev-haskell/validity-0.4:=[profile?]',
      '<dev-haskell/validity-path-0.2:=[profile?]',
      '>=dev-haskell/genvalidity-path-0.1',
      '<dev-haskell/genvalidity-path-0.2']
   app-admin/super-user-spark/super-user-spark-0.4.0.0.ebuild: RDEPEND: ~amd64(hardened/linux/amd64/x32)
[     '<dev-haskell/validity-0.4:=[profile?]',
      '<dev-haskell/validity-path-0.2:=[profile?]']
Please fix these important QA issues first.
RepoMan sez: "Make your QA payment on time and you'll never see the likes of me."
