### ISSUE TITLE
alsa-mixer fails installing: c2hs fails on glibc header

### ISSUE THREAD

**Issue by qrilka** [gentoo-haskell/gentoo-haskell#831]
From the build log
```
Preprocessing library for alsa-mixer-0.2.0.3..
c2hs: C header contains errors:

/usr/include/bits/floatn.h:73: (column 29) [ERROR]  >>> Syntax error !
  The symbol `;' does not fit here.
```

**Comment by qrilka** [comment]
Looks like it's caused by https://github.com/haskell/c2hs/issues/198

**Comment by solpeth** [comment]
@qrilka this seems to be the same as [bug #644200](https://bugs.gentoo.org/644200) in the Gentoo bugtracker.

**Comment by trofi** [comment]
Which versions `language-c` and `c2hs` you have installed? Maybe we need to bump them in `::gentoo`.

**Comment by qrilka** [comment]
i have `c2hs-0.28.5` and `dev-haskell/language-c` but how could it help when this bug is unresolved upstream?

**Comment by trofi** [comment]
I had impression most of `_Float* ` issues were fixed in `language-c` / `c2hs` upstreams.

**Comment by qrilka** [comment]
@solpeth I'll try switching to GCC 7, thanks

**Comment by qrilka** [comment]
It does help, thanks again @solpeth

**Comment by solpeth** [comment]
@qrilka you're welcome!
