### ISSUE TITLE
taffybar package is outdated

### ISSUE THREAD

**Issue by qrilka** [gentoo-haskell/gentoo-haskell#832]
Hackage has already version 3.0.0 and the current `x11-misc/taffybar-0.4.6-r1` fails to compile with GHC 8.4.3:

```
setup: Encountered missing dependencies:
time >=1.4 && <1.7
```

**Comment by qrilka** [comment]
BTW how did requirement for GHC 8.4 have appeared? I just have compiled `taffybar` locally using  `stack` with its current lts with GHC 8.2, the only thing which I had to do is to install `dev-libs/libdbusmenu` with useflag `gtk3` and then everything built fine

**Comment by trofi** [comment]
Gentoo's haskell packages usually do not allow multiple versions installed. This means that packages bundled with ghc (like `time`) can't be upgraded standalone and have to pull in new ghc. `hackport` usually reports why minimum `ghc` version was picked.

But in this case minimum `time` version is incorrect in `.cabal` file.

**Comment by qrilka** [comment]
It's understandable why `taffybar-0.4.6` is not compatible with GHC 8.4 but as I understand @solpeth was saying that version `2.1.2` requires GHC 8.4 and how that could be is not clear to me.
