### ISSUE TITLE
The latest *.cabal file revision needs to be fetched before build

### ISSUE THREAD

**Issue by hololeap** [gentoo-haskell/gentoo-haskell#861]
Some Hackage packages have one or more revisions of their `*.cabal` files, which can change their dependencies (and presumably other things as well.) [`servant-foreign`](http://hackage.haskell.org/package/servant-foreign) is an example of one such package. When you query `hackage.haskell.org`, the dependencies listed are those of the latest revision. However, when you fetch a tarball from one of the Hackage mirrors, the _original_ `*.cabal` file is included. You can see here that `cabal` takes an extra step to fetch the latest `*.cabal` revision before bulding: 

    kinetik@triton ~ $ cabal get -v3 servant-foreign                                                      
    no user package environment file found at /home/kinetik
    Reading available packages of hackage.haskell.org...
    Using most recent state specified from most recent cabal update
    index-state(hackage.haskell.org) = 2018-09-05T20:33:36Z
    Downloading servant-foreign-0.11.1...
    Writing
    /home/kinetik/.cabal/packages/hackage.haskell.org/servant-foreign/0.11.1/servant-foreign-0.11.1.tar.gz
    Selected mirror http://hackage.haskell.org/
    Downloading package servant-foreign-0.11.1
    Searching for curl in path.
    Found curl at /usr/bin/curl
    Searching for powershell in path.
    Cannot find powershell on the path
    Searching for wget in path.
    Found wget at /usr/bin/wget
    Selected http transport implementation: curl
    /usr/bin/curl 'http://hackage.haskell.org/package/servant-foreign-0.11.1.tar.gz' --output /tmp/transportAdapterGet7004-1 --location --write-out '%{http_code}' --user-agent 'cabal-install/2.2.0.0 (linux; x86_64)' --silent --show-error --dump-header /tmp/curl-headers7004-2.txt --header 'Cache-Control: no-transform'
    Unpacking to servant-foreign-0.11.1/
    Updating servant-foreign-0.11.1/servant-foreign.cabal with the latest revision from the index.

The last line here is the one to pay attention to. When I used `hackport` to generate `servant-foreign-0.11.1.ebuild`, it used the [latest revision](http://hackage.haskell.org/package/servant-foreign-0.11.1/revision/3.cabal) which includes this this dependency:

      build-depends:
          servant            == 0.13.* || ==0.14.*

However, when it comes time to prepare the build, portage simply unpacks the [tarball](https://hackage.haskell.org/packages/archive/servant-foreign/0.11.1/servant-foreign-0.11.1.tar.gz) which includes the [original revision](http://hackage.haskell.org/package/servant-foreign-0.11.1/revision/0.cabal) and this dependency:

      build-depends:
          servant            == 0.13.*

Because of this, portage thinks that `=dev-haskell/servant-0.14.1` is a valid dependency, but during the configure phase, an error is thrown:

    setup: Encountered missing dependencies:
    base-compat >=0.9.3 && <0.10, servant ==0.13.*

There needs to be a way to fetch this latest revision so that the dependencies in the `*.cabal` file and those from Hackage are in sync.

**Comment by solpeth** [comment]
I like the idea.

I'll have a look at how much work is in teaching `hackport` to detect changes between the `.cabal` dependencies in the tarball, and the latest metadata revisions on Hackage. Ideally, `hackport` could then proceed to automatically generate the relevant `cabal_chdeps` line under `src_prepare()`, according to the metadata revision.

(This proposed solution means that this issue probably belongs in the hackport repository).

**Comment by trofi** [comment]
Yes. hackport sounds like a correct place. WRT 'cabal_chdeps` call I'd suggest using a separate URI entry for that, like (example for `lens-3.5.1` package):

```
CABAL_REVISION=1

SRC_URI="
    mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz
    http://hackage.haskell.org/package/lens-3.5.1/revision/1.caball -> ${CATEGORY}-${PV}-${CABAL_REVISION}.cabal
"
...
src_prepare() {
    local cf=${WORKDIR}/${CATEGORY}-${PV}-${CABAL_REVISION}.cabal
    rm "${cf}" || die
    mv "${cf}" ${PV}.cabal || die
}
```
