### ISSUE TITLE
Dependency issues with dev-haskell/skylighting-core

### ISSUE THREAD

**Issue by hololeap** [gentoo-haskell/gentoo-haskell#873]
I'm running into an issue when I try to compile `dev-haskell/skylighting-core-0.7.4`. First of all, I get a warning during the configure phase:

    Warning:
        This package indirectly depends on multiple versions of the same package. This is very likely to cause a compile failure.
          package text (text-1.2.3.0) requires binary-0.8.5.1
          package uuid-types (uuid-types-1.0.3-AF2r8ZzQ8grAwMj1dMR16W) requires binary-0.8.6.0-Hp4QtENPVwc9YhoUEhfHbX
          package skylighting-core (skylighting-core-0.7.4) requires binary-0.8.6.0-Hp4QtENPVwc9YhoUEhfHbX
          package scientific (scientific-0.3.5.3-DNw0MVcraZbIXxry7lKBey) requires binary-0.8.6.0-Hp4QtENPVwc9YhoUEhfHbX
          package hxt (hxt-9.3.1.16-ETUGRG5nttz2SgANMBWij9) requires binary-0.8.6.0-Hp4QtENPVwc9YhoUEhfHbX

Then, during the compile phase, I actually get errors and the build fails. Right now I have `dev-haskell/text-1.2.3.0` and it isn't obvious to me why there is this version mismatch. According to Hackage, `text-1.2.3.0` doesn't have a version requirement for the `binary` dependency.

**Comment by hololeap** [comment]
After a bit more investigation, I see that I had `dev-haskell/binary-0.8.6.0` installed, but `ghc-pkg describe binary` reports that version `0.8.5.1` is installed. It seems like this package (in the Haskell sense) is bundled with GHC (`dev-lang/ghc-8.4.3` is installed), so this package (in the Portage sense) isn't really doing anything other than existing to make Portage happy and provide correct dependency resolution. I am going to try downgrading to `dev-haskell/binary-0.8.5.1` and try again.

**Comment by trofi** [comment]
Yes, many exposed haskell libraries must match version if ghc exposed to avoid diamond dependency problem. I think we need to mark such libraries explicitly to make it harder to break user's system by accident.

**Comment by solpeth** [comment]
`binary-0.8.6.0` should be masked and marked as bundled with `ghc-8.6.1`. Was this the case on your system, @hololeap?

We had this issue not long ago with someone's `transformers-compat`, for the same reason.

**Comment by solpeth** [comment]
Apologies, accidentally closed this. Reopening.

**Comment by hololeap** [comment]
I had `dev-haskell/binary **` in my `package.accept_keywords`, probably from when GHC 8.4 was masked.

**Comment by solpeth** [comment]
I'm closing this issue on the basis that there is no dependency issue with skylighting-core, but that `binary-0.8.6.0` was pulled in when it shouldn't have been under normal circumstances.

This doesn't invalidate @trofi's comment about explicitly marking libraries like `binary` to help prevent accidental breakages like this.
