### ISSUE TITLE
Travis CI - Maximum time limit reached

### ISSUE THREAD

**Issue by hololeap** [gentoo-haskell/gentoo-haskell#895]
If you take a look at the [history of pull requests](https://travis-ci.org/gentoo-haskell/gentoo-haskell/pull_requests) on Travis CI, you will see that the job time has been slowly increasing and has now hit an upper limit of 50 minutes for some recent tests.

These tests all have the same error message:

    ...
    
    $ cd travis-overlay
    $ ./../spinner.sh "python ../portage-portage-${PORTAGE_VER}/repoman/bin/repoman full -d"
    
    The job exceeded the maximum time limit for jobs, and has been terminated.

**Comment by trofi** [comment]
Yeah, ebuild count increase and profile count increase makes repoman very slow.

We can try omitting developer profiles as an immediate workaround. Should cut the load in half.

**Comment by solpeth** [comment]
Marking as solved. Trofi's workaround solves the issue, at least for now.

Tests now appear to sit around the 40 minute mark, which gives us a decent buffer for the forseeable future.
