### ISSUE TITLE
skylighting-core-0.7.6 cannot be built with GHC 8.4.4

### ISSUE THREAD

**Issue by buzden** [gentoo-haskell/gentoo-haskell#922]
`skylighting-core-0.7.6` fails to be built with ghc 8.4.4 (however, builds with 8.6.3) but its dependencies allow to be built with 8.4.4. Maybe, it should be fixed in the ebuild?

**Comment by solpeth** [comment]
Hi, thanks for the report.

Could you please post the failed build log so I can get a picture of what's failing? At first glance, there shouldn't be any incompatibilities with `ghc-8.6` based on the declared dependencies of the package.

**Comment by solpeth** [comment]
@buzden `skylighting-core-0.7.7` has been released, but I'll again note that there has been no mention of incompatibility with `ghc-8.4` (or fixing of any such incompatibility). Could you please retest, and given a failure, provide a build log? If all is well, could you please let us know? Thanks.

**Comment by solpeth** [comment]
Closing (need more info).
