### ISSUE TITLE
Weird build error regarding cabal

### ISSUE THREAD

**Issue by Hypoon** [gentoo-haskell/gentoo-haskell#923]
My world update failed on dev-haskell/tagged-0.8.6:

/usr/bin/ghc -package Cabal-2.2.0.1 --make /var/tmp/portage/dev-haskell/tagged-0.8.6/work/tagged-0.8.6/Setup.lhs -j18 +RTS -A256M -qb0 -RTS -threaded -dynamic -o setup
<command line>: cannot satisfy -package Cabal-2.2.0.1
    (use -v for more information)
/usr/bin/ghc -package Cabal-2.2.0.1 --make /var/tmp/portage/dev-haskell/tagged-0.8.6/work/tagged-0.8.6/Setup.lhs -j18 +RTS -A256M -qb0 -RTS -threaded -o setup
<command line>: cannot satisfy -package Cabal-2.2.0.1
    (use -v for more information)

GHC had been updated a few packages earlier. Haskell-updater did not help, reporting the same error as above.

The solution was to re-emerge cabal. Running "emerge -av1 dev-haskell/cabal" updated cabal from 2.2.0.1 to 2.4.0.1, and pulled in dev-haskell/cabal-doctest for a rebuild (or maybe an update, I can't remember). Haskell-updater worked correctly after that.

I also noticed that cabal 2.4.0.1 emerged very, very quickly. If it's a dummy package with the real cabal included somewhere else (ghc maybe?), then maybe that explains the issue? The real cabal was updated to 2.4.0.1, but the installed package was still 2.2.0.1, causing dev-haskell/tagged to look for the wrong version?

**Comment by trofi** [comment]
It's a disguised circular dependency of cabal on itself. We lost a fix from https://github.com/gentoo-haskell/gentoo-haskell/issues/810. Hopefully restored now.
