### ISSUE TITLE
fail to emerge dev-haskell/exceptions-0.10.0

### ISSUE THREAD

**Issue by mowgli** [gentoo-haskell/gentoo-haskell#924]
The issue #848 happened again with dev-haskell/transformers-0.5.6.2.

Please add some versioned dependencies to ghc to prevent such troubles.

**Comment by solpeth** [comment]
Hello,

Could you provide a build log please?

`transformers-0.5.6.2` was released in line with GHC 8.6.4, which is the latest keyworded GHC release. If the situation is that you are purposefully remaining on a previous GHC release you will need to create local package masks for bundled libraries as per #848. If this is otherwise unexpected then I'd like to take a look at a build log to see what the problem may be.

**Comment by mowgli** [comment]
Well, as recommended by some other users when I had troubles using haskell overlay as I needed current git-annex and pandoc, I have the following keyword:
```
dev-haskell/*
```

But I only have a versioned one for ghc.

So, yes, maybe using the latest ghc would solve the problem too. What would cost me a full weekend to solve all teh circular dependencies and not explicit mentioned dependencies. Recompiling haskell stuff is always a pain and very, very time comsuming.

But my point is that the dependencies are not correct for ghc as well as for many dev-haskell/* packages. If there would be a versioned dependency for packages that are bundled with ghc, no problem would occur. Furthermore it would tell a user that a mask change would be needed.

And a even better solution would be if ghc would not bundle any other package at all or if it bundles one, would not allow to install the same package as a separate package.

**Comment by solpeth** [comment]
The bundled packages are dummy packages. They do not install anything. They allow Portage to track them. We of course have no control over which packages ghc bundles internally, as you have alluded to.

I'm AFK, but ghc depending on internal libraries as explicit dependencies would create circular dependencies (ghc -> transformers -> ghc). We deal with circular cabal dependencies using `nocabaldep`, but that is not for the use case that is described in this issue.

You mention that you have masked certain ghc versions. You will also need to mask versions of packages that ghc bundles internally which Portage tracks, such as transformers. If you could post a build log, I can try and help with package masks for the version you're on.

**Comment by solpeth** [comment]
Closing (need more info). Please feel free to post a build log or other information so I can help you with your system.
