### ISSUE TITLE
Stack update

### ISSUE THREAD

**Issue by qrilka** [gentoo-haskell/gentoo-haskell#935]
Version 1.9.3.1 was released recently adding compatibility with `rio-0.1.9.2` which is already in `gentoo-haskell`

**Comment by CharlzKlug** [comment]
I have a problem with updating stack. My build log is [here](https://pastebin.com/7xFzDZFN). Updating is failed with messages like
`src/Stack/Setup.hs:1121:28: error:
    Ambiguous occurrence ‘exitFailure’
    It could refer to either ‘Stack.Prelude.exitFailure’,
                             imported from ‘Stack.Prelude’ at src/Stack/Setup.hs:81:1-55
                             (and originally defined in ‘rio-0.1.9.2:RIO.Prelude.Exit’)
                          or ‘System.Exit.exitFailure’,
                             imported from ‘System.Exit’ at src/Stack/Setup.hs:96:49-59
`
How can I fix that? Thank you!

**Comment by qrilka** [comment]
That's exactly what version 1.9.3.1 is aimed to solve @CharlzKlug

**Comment by Hypoon** [comment]
I'm having the same issue as CharlzKlug. For reference, this is `stack-1.9.3-r1` with `ghc-8.6.4` and `rio-0.1.9.2`. I noticed this issue last week, but I hadn't determined whether the bug report belonged here or upstream. I have not attempted any workarounds beyond the standard use of haskell-updater.

```
[ 92 of 127] Compiling Stack.Clean      ( src/Stack/Clean.hs, dist/build/Stack/Clean.o )

src/Stack/Clean.hs:30:33: error:
    Ambiguous occurrence ‘exitFailure’
    It could refer to either ‘Stack.Prelude.exitFailure’,
                             imported from ‘Stack.Prelude’ at src/Stack/Clean.hs:14:1-30
                             (and originally defined in ‘rio-0.1.9.2:RIO.Prelude.Exit’)
                          or ‘System.Exit.exitFailure’,
                             imported from ‘System.Exit’ at src/Stack/Clean.hs:22:31-41
   |
30 |     when (or failures) $ liftIO exitFailure
   |                                 ^^^^^^^^^^^
```
```
[102 of 127] Compiling Stack.Setup      ( src/Stack/Setup.hs, dist/build/Stack/Setup.o )

src/Stack/Setup.hs:1121:28: error:
    Ambiguous occurrence ‘exitFailure’
    It could refer to either ‘Stack.Prelude.exitFailure’,
                             imported from ‘Stack.Prelude’ at src/Stack/Setup.hs:81:1-55
                             (and originally defined in ‘rio-0.1.9.2:RIO.Prelude.Exit’)
                          or ‘System.Exit.exitFailure’,
                             imported from ‘System.Exit’ at src/Stack/Setup.hs:96:49-59
     |
1121 |                     liftIO exitFailure
     |                            ^^^^^^^^^^^
```

**Comment by solpeth** [comment]
I'll bump this shortly. Thanks for the report.
