### ISSUE TITLE
hashable-1.2.7.0 build failed; missing dependency: integer-gmp >= 0.2

### ISSUE THREAD

**Issue by toku-sa-n** [gentoo-haskell/gentoo-haskell#947]
Hello.

This problem isn't the same as #818 because I don't build hashable or ghc with `USE=profile`. (Or maybe the same but I couldn't confirm it because the build log of #818 is 404.)

[build.log](https://github.com/gentoo-haskell/gentoo-haskell/files/3399517/build.log)

**Comment by nl169** [comment]
Hi

Please try  

`USE="-gmp" emerge -1 hashable`

\
integer-gmp is a part of GMP linked GHC builds
LGPL-free alternative package is integer-simple 

That's not particularly possible to use both implementations  at the same time
GHC and all haskell-related stuff must use the same GMP flag 
+gmp is the default option tho
\
\
You should disable GMP globally if you're going to use GMP-free build

`echo "*/*::haskell -gmp" >> /etc/portage/package.use/haskell-gmp`

**Comment by toku-sa-n** [comment]
Tried `USE="-gmp" emerge -1 hashable` and I installed hashable successfully. Thank you for your support!
