### ISSUE TITLE
Port dev-lang/ghc to arm64.

### ISSUE THREAD

**Issue by crocket** [gentoo-haskell/gentoo-haskell#958]
Right now, it doesn't build on aarch64 systems such as raspberry pi 3 b+.

**Comment by trofi** [comment]
Probably not amd64 then.

Cross-compiling and cross-building a package (https://trofi.github.io/posts/200-ghc-as-a-crosscompiler-update.html) should work:

```
$ aarch64-unknown-linux-gnu-ghc --info
...
 ,("Project version","8.9.0.20190818")
 ,("Project Git commit id","d071627932f61a20223ff0875ed96452f9e81b34")
 ,("Booter version","8.6.3")
 ,("Stage","1")
 ,("Build platform","x86_64-unknown-linux")
 ,("Host platform","x86_64-unknown-linux")
 ,("Target platform","aarch64-unknown-linux")
```

**Comment by crocket** [comment]
Can `aarch64-unknown-linux-gnu-emerge` call `aarch64-unknown-linux-gnu-ghc` instead of `ghc`?

**Comment by necrose99** [comment]
ghc-8.4.1-aarch64-deb8-linux.tar.xz
On ghc , dev-lang/ghc-bin.  .. gmp is req.
/opt/bin/ghc.  Then could build ...

**Comment by trofi** [comment]
We don't have a nice way to pass ${CHOST}-ghc as a compiler today. Something like `CABAL_EXTRA_CONFIGURE_FLAGS=--with-compiler=${CHOST}-ghc` in target's make.conf might work. Worth a try.

It would make sense to pass `${HC}` (or `${GHC}`) to `haskell-cabal.eclass`.

**Comment by crocket** [comment]
I still think it's nicer to have native ghc on aarch64 systems because ARM single board computer are becoming powerful enough to build everything.

**Comment by pbarill** [comment]
I recently cross-built ghc 8.6.5 and 8.8.1 for aarch64. It works.

**Comment by necrose99** [comment]
Thats great if you have a crossdev server  setup.. however  most don't.. you average Epyc or Intel servers are $8-20k dep on n x 16-32 core count CPUs. 1-4 
If you have just a laptop,  its often powerful but constrained also. 
USE="BIN" emerge ghc , 
Debian arm64 gmp req  tarballs abound. 
However could be useful in bootstrapping ghc on SBC'S,  infact if i can get settled,  arm64 community binhost,  would be ok to me. As any new building,  could more easily do natively.. 

Or by putting the bins in build root to enable building..

**Comment by pbarill** [comment]
I don't know how it would do with Epyc and the like: I built those with a 10 years old Phenom II X4 (though plenty of ram for tmpfs). Now that's epic to me! It takes almost two hours each (vs. some ~40 minutes for an ordinary native build). Out of curiosity, I looked at building GHC pseudo natively through `qemu` on that same machine: I pulled the plug after a few hours of torture. It would have taken 40+ hours.

Remember (or note) that anything `template-haskell` does not work in cross-building (i.e. anything that calls for `lens`, that's a lot of stuff), so crossdev is pretty good to get ghc up and running, but that's the only haskell related thing I build with it. For the rest, better off going natively than qemu (except perhaps for the likes of pi zero).

I agree it would be a fine addition to have an available `ghc-bin-8.x.x-aarch64-unknown-linux-gnu.tbz2`. I don't think there's a big demand for each and every arch, but this one is definitely gaining traction. I would be happy to help with that (8.4, 8.6, 8.8) as I got the crossdev all set. @trofi ?

**Comment by trofi** [comment]
If you have native arm64 environment https://github.com/gentoo-haskell/gentoo-haskell/blob/master/projects/refresh-ghc-bin.bash might be good enough to build native binaries.

I'll be happy to copy binaries built by someone else and add it to ebuild.

**Comment by pbarill** [comment]
I'll look into building it natively on my Pi 4. So far I only used cross-built creatures on it and I was quite content with those, but it's a little quirky, so to speak. For example, when I cross-built ghc-8.8.1, it spammed with this, throughout the process:

```
You are using an unsupported version of LLVM!
Currently only 7 is supported.
We will try though...
```
What's wrong with that? I had only one version of llvm installed on the system: 7.1.0 (of course it had aarch64 flag enabled). I'm afraid it doesn't end there. In the case of 8.6.5, when using it on the Pi, it will harass me all the time with a similar message for llvm-6, unless I have that version installed and first on the path (that is unfortunate as this version is not anymore in `::gentoo`!!). Let's hope that a native build will be less temperamental.

**Comment by pbarill** [comment]
8.6.5 and 8.8.2 ghc-bin for aarch64 are now living in the overlay. Feel free to reopen the issue should you encounter problems.
