### ISSUE TITLE
GHC-8.8.1 needs Alex version 3.1.7 or later

### ISSUE THREAD

**Issue by TheSiege** [gentoo-haskell/gentoo-haskell#959]
error: checking for version of alex... 
configure: error: Alex version 3.1.7 or later is required to compile GHC.

is not pulled in by ghc-8.8.1 ebuild

**Comment by trofi** [comment]
Yeah, it's a https://gitlab.haskell.org/ghc/ghc/issues/17114 bug upstream.

Current workaround is to install alex (say, by using USE=binary ghc of previous version).

**Comment by trofi** [comment]
Reverted the fix as https://github.com/gentoo-haskell/gentoo-haskell/commit/9a59f8c70b1f7b0bf14787c9aecd85dd783996f4 as it broke `./configure` completely. Need better fix.

**Comment by InBetweenNames** [comment]
I was wondering what was going on with that!

**Comment by trofi** [comment]
Installing `dev-haskell/alex` and `dev-haskell/happy` from the overlay should be enough (at least it's what I did when tested initial 8.8.1 version).
