### ISSUE TITLE
dev-haskell/ihaskell incompatible with ghc-8.6.5

### ISSUE THREAD

**Issue by pbarill** [gentoo-haskell/gentoo-haskell#965]
Latest version of ihaskell in repo is 0.9.1.0, which is not compatible with ghc-8.6. The latest version (0.10.0.2) is compatible. I suspect a related required update is ipython-kernel to 0.10.1.0.

**Comment by trofi** [comment]
Sounds reasonable. Would you like to give it a go and try to bump it yourself? We have a few hints at https://github.com/gentoo-haskell/gentoo-haskell/blob/master/projects/doc/README.rst

**Comment by pbarill** [comment]
I'm quite green when it comes to editing ebuilds, but I find this hackport tool so interesting that I'll give it a try and get back to you on my adventures.

**Comment by pbarill** [comment]
Hackport is fun! I made a pull request. I tried my best to emulate the conventions in this repository, which appear to be: i) at most one ebuild per commit; ii) disclose portage and repoman version; iii) sign off.

If something is not up to specs, let me know and I'll take note of it.

**Comment by trofi** [comment]
The changes look good! Yeah, usually `repoman commit` generates the right form and tags.

Closing this bug as https://github.com/gentoo-haskell/gentoo-haskell/pull/967 is merged.
