### ISSUE TITLE
dev-lang/elm-compiler-0.19.0-r1 build failures

### ISSUE THREAD

**Issue by nissarin** [gentoo-haskell/gentoo-haskell#969]
Freshly installed overlay & emerge elm fails due to dependency on specific version of 'containers' library. 

When I "fixed" that locally using cabal_chdeps build failed because of network-sandbox violation, after adding RESTRICT="network-sandbox" emerge succeeded and it appears that everything works (tested with example project).

[build-1.log](https://github.com/gentoo-haskell/gentoo-haskell/files/3726037/build-1.log)
[build-2.log](https://github.com/gentoo-haskell/gentoo-haskell/files/3726038/build-2.log)

**Comment by trofi** [comment]
Yeah, let's leave network sandboxing issue to https://github.com/gentoo-haskell/gentoo-haskell/issues/618 and focus on containers dep here.

Would you like to craft a patch against the ebuild yourself?

**Comment by MarkusPettersson98** [comment]
Just made a pull request adding containers dependency to ebuild. Check it out! #970

**Comment by trofi** [comment]
Thank you!
