### ISSUE TITLE
dev-vcs/git-annex fails to build due to bumped dev-haskell/socks version

### ISSUE THREAD

**Issue by webstrand** [gentoo-haskell/gentoo-haskell#973]
`>=dev-haskell/socks-0.6` has changed the interface of `defaultSocksConf`.

The error reported at build time is:
```
[ 92 of 498] Compiling Utility.Tor      ( Utility/Tor.hs, dist/build/git-annex/git-annex-tmp/Utility/Tor.dyn_o )

Utility/Tor.hs:40:23: error:
    • Couldn't match expected type ‘Integer -> t’
                  with actual type ‘SocksConf’
    • The function ‘defaultSocksConf’ is applied to two arguments,
      but its type ‘SockAddr -> SocksConf’ has only one
      In the expression: defaultSocksConf "127.0.0.1" torsocksport
      In an equation for ‘torsockconf’:
          torsockconf = defaultSocksConf "127.0.0.1" torsocksport
    • Relevant bindings include
        torsockconf :: t (bound at Utility/Tor.hs:40:9)
   |
40 |         torsockconf = defaultSocksConf "127.0.0.1" torsocksport
   |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Utility/Tor.hs:40:40: error:
    • Couldn't match expected type ‘SockAddr’ with actual type ‘[Char]’
    • In the first argument of ‘defaultSocksConf’, namely ‘"127.0.0.1"’
      In the expression: defaultSocksConf "127.0.0.1" torsocksport
      In an equation for ‘torsockconf’:
          torsockconf = defaultSocksConf "127.0.0.1" torsocksport
   |
40 |         torsockconf = defaultSocksConf "127.0.0.1" torsocksport
   |                                        ^^^^^^^^^^^
```
Upstream has fixed the issue in [018b5b81736a321f3eb9762a2afb7124e19dbdf9](http://source.git-annex.branchable.com/?p=source.git;a=blobdiff;f=Utility/Tor.hs;h=094c91aacd24cff5394fed74a64bbbba77b7498b;hp=427fb100bc222ac58c4fd61059e02f606749f377;hb=018b5b81736a321f3eb9762a2afb7124e19dbdf9;hpb=9fd37e65d05c6169a81d066658776e0dc19e9495).

I've confirmed that applying the upstream commit as a user-patch against the packaged version of git-annex fixes the issue.

**Comment by solpeth** [comment]
Thanks for the report. Would you like to have a go at submitting a pull request with the above change? I can help you out if you get stuck.

**Comment by webstrand** [comment]
Sure, do you mean a pull request with a `dev-vcs/git-annex/files/git-annex-7.20190129-socks-0-6.patch` or something else?

**Comment by solpeth** [comment]
yep, pretty much!

Check out the [HOWTO-contribute guide](https://github.com/gentoo-haskell/gentoo-haskell/blob/master/projects/doc/HOWTO-contribute.rst) to get set up with your own working copy of the haskell overlay, and how to submit a pull request when you're done. Again, if you need any help let me know.

Once you're all set up, in your local copy of your haskell overlay go to the `dev-vcs/git-annex` directory, drop the patch in the `files` subdirectory, and add that path to the `PATCHES` array of the git-annex ebuild (an example of the `PATCHES` array is in the [cabal-2.4.0.1 ebuild](https://github.com/gentoo-haskell/gentoo-haskell/blob/7083ffb21cb805cd1fff9c7028984706ccdf905b/dev-haskell/cabal/cabal-2.4.0.1.ebuild#L37).

**Comment by webstrand** [comment]
pull request #974 merged
