### ISSUE TITLE
gtk2hs-buildtools-0.13.5.1 is broken with cabal<3.0

### ISSUE THREAD

**Issue by qrilka** [gentoo-haskell/gentoo-haskell#978]
emerging it fails with
```
src/Gtk2HsSetup.hs:106:61: error:
    Not in scope: ‘LBI.componentsConfigs’
    Perhaps you want to add ‘componentsConfigs’ to the import list
    in the import of ‘Distribution.Types.LocalBuildInfo’
    (src/Gtk2HsSetup.hs:36:1-68).
    |
106 | libraryConfig lbi = case [clbi | (LBI.CLibName, clbi, _) <- LBI.componentsConfigs lbi] of
    |                                                             ^^^^^^^^^^^^^^^^^^^^^

```
and it looks like this comes from gentoo-haskell patches bringing compatibility with Cabal-3 but at the same time cabal-3.0.0.0 doesn't even has `~amd64` yet.
@markwright it looks like you have added those patches recently, could you give your comment?

**Comment by solpeth** [comment]
@qrilka I've pushed a change which moves those patches to `-r1`, which will be unmasked when `cabal-3` is keyworded. Let me know if it still does not work for you.

**Comment by qrilka** [comment]
Seems to be fine, thanks
