### ISSUE TITLE
Add dev-haskell/time-1.9.3

### ISSUE THREAD

**Issue by crocket** [gentoo-haskell/gentoo-haskell#988]
I added dev-haskell/time-1.9.3 to my local overlay by executing

```
hackport merge time
```

**Comment by pbarill** [comment]
If I am not mistaken, the absence of `time` from the overlay is not an omission but a necessity. This library is part of built-in libraries that ship with GHC.

**Comment by trofi** [comment]
Correct, `time` is one of libraries bundled with ghc and is not safe to install in parallel as `unix`, `directory`, `Cabal` and `ghc` all depend on bundled `time`.

**Comment by crocket** [comment]
Without time-1.9.3, my little programs don't compile as gentoo packages.

**Comment by trofi** [comment]
In Gentoo you would have to require ghc version that ships that version or above. Or copy the functionality in the package.

**Comment by crocket** [comment]
How haven't I encountered a problem with time-1.9.3 on my system so far?

**Comment by trofi** [comment]
It depends on packages you have installed. The build will fail when both new time and old time are pulled in. Say, time directly and time via `ghc` package.
