### ISSUE TITLE
http-api-data: use-text-show flag

### ISSUE THREAD

**Issue by pbarill** [gentoo-haskell/gentoo-haskell#996]
This  looks like an incompatibility. Use flag:

    =dev-haskell/http-api-data-0.4.1-r1 use-text-show

Then try merging `=dev-haskell/persistent-2.10.4`

My experience: it won't work. Same thing with previous version of persistent, and although `http-api-data-0.4.1.1` is available, I gave it a quick bump and saw no difference (expectations met as I glanced at their last few commits).

Can you replicate the problem?

If so, what would be the best course of action here?

1. Kill `use-text-show` in `http-api-data`.

2. Set a conditional use flag in ebuilds for `persistent`
````
>=dev-haskell/http-api-data-0.3:=[-use-text-show]
````

3. Do nothing?

Related question: Haven't played before with this kind of constraint. [devmanual](https://devmanual.gentoo.org/general-concepts/dependencies/index.html) says that… EAPI=2 must be used in this case (?!?). Is devmanual up to date (maybe not), or is there another way that I should know?

**Comment by trofi** [comment]
Did not look at it yet. If the flag is disabled by default we can just unconditionally disable it.

**Comment by trofi** [comment]
Confirmed build failure locally:
```
[ 2 of 24] Compiling Database.Persist.Types.Base ( Database/Persist/Types/Base.hs, dist/build/Database/Persist/Types/Base.o )

Database/Persist/Types/Base.hs:82:18: error:
    • No instance for (text-show-3.8.2:TextShow.Classes.TextShow
                         Checkmark)
        arising from a use of ‘showTextData’
    • In the expression: showTextData
      In an equation for ‘toUrlPiece’: toUrlPiece = showTextData
      In the instance declaration for ‘ToHttpApiData Checkmark’
   |
82 |     toUrlPiece = showTextData
   |                  ^^^^^^^^^^^^

Database/Persist/Types/Base.hs:85:21: error:
    • No instance for (text-show-3.8.2:TextShow.Classes.TextShow
                         Checkmark)
        arising from a use of ‘parseBoundedTextData’
    • In the expression: parseBoundedTextData
      In an equation for ‘parseUrlPiece’:
          parseUrlPiece = parseBoundedTextData
      In the instance declaration for ‘FromHttpApiData Checkmark’
   |
85 |     parseUrlPiece = parseBoundedTextData
   |                     ^^^^^^^^^^^^^^^^^^^^
```
